In [15]:
import numpy as np

path_prefix = "./all/data/"
word_to_index = {} # map word to index
g_word_list = [] # sorted by frequence low to high
total_word_dict = {}
skip_words = set(['', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'as', 'an', 'and', 'are', 'at', 'by', 'down', 'for', 'from', 'front', 'has', 'in', 'is', 'it', 'near', 'next', 'of', 'on', 'out', 'over', 'several', 'sits', 'some', 'that', 'the', 'there', 'through', 'to', 'top', 'up', 'while', 'with'])
train_des = [] #0/1/2 array of word
test_des = [] #0/1/2 array of word
train_feature_list = [] # list of feature_array by index
test_feature_list = []
all_predict_test_des = []
train_g_category_tag = []
train_g_item_tag = []
test_g_category_tag = []
test_g_item_tag = []
MAX_INPUT = 10000
MAX_OUTPUT = 2000
COMPONENTS = 400 # need to run again
PCA_NUMBER = 2000 # need to run again
ITER = 500

In [16]:
def read_file_to_string(file_name, keep_colon):
    f = open(file_name, "r")
    content = f.read()
    f.close()
    content = content.lower()
    content = content.replace(",", " ").replace(".", " ").replace("'", " ").replace("\"", " ")
    if (keep_colon == False):
        content = content.replace(":", " ")
    return content

def read_file_to_total_word_dict(file_name, keep_colon):
    word_list = read_file_to_string(file_name, keep_colon).split()
    for name in word_list:
        if name in skip_words:
            continue
        if name in total_word_dict:
            total_word_dict[name] += 1
            continue
        else:
            total_word_dict[name] = 1
            continue

def print_word_in_array(a):
    ret = ""
    for i in range(len(a)):
        if a[i] != 0:
            ret = ret + str(a[i]) + g_word_list[i] + " "
    print(ret)

In [17]:
total_word_dict = {}
for i in range(MAX_INPUT):
    read_file_to_total_word_dict(path_prefix+"descriptions_train/"+str(i)+".txt", False)
    read_file_to_total_word_dict(path_prefix+"tags_train/"+str(i)+".txt", True)

In [18]:
import functools
def cmp(a, b):
    a_num = abs(float(a.split("___")[0]))
    b_num = abs(float(b.split("___")[0]))
    if (a_num < b_num):
        return -1
    return 1

In [19]:
# load g_word_list
g_word_list = []
word_to_index = {}
tmp_list = []
#TODO: maybe try filter on number
for word in total_word_dict:
    if total_word_dict[word] <= 0:
        continue
    tmp_list.append(str(total_word_dict[word])+"___"+word)

tmp_list = sorted(tmp_list, key=functools.cmp_to_key(cmp))

for i in range(len(tmp_list)):
    word = tmp_list[i].split("___")[1]
    g_word_list.append(word)
    word_to_index[word] = i

In [20]:
# read to tags
train_g_category_tag = [0] * MAX_INPUT
train_g_item_tag = [0] * MAX_INPUT
test_g_category_tag = [0] * MAX_OUTPUT
test_g_item_tag = [0] * MAX_OUTPUT

#TODO: add tags in descriptions
def is_in_tag(file_number, word, train):
    if train:
        return (word in train_g_category_tag[file_number]) or (word in train_g_item_tag[file_number])
    return (word in test_g_category_tag[file_number]) or (word in test_g_item_tag[file_number])

def read_tags(file_name, train):
    lines = read_file_to_string(file_name, True).split("\n")
    index = int(file_name.split("/")[-1].replace(".txt", ""))
    current_category_set = set([])
    current_item_set = set([])
    
    for line in lines:
        cat = line.split(":")[0].strip()
        if cat in word_to_index:
            current_category_set.add(cat)

        item = ''
        if (cat.strip() != line.replace(":", "").strip()):
            item = line.split(":")[1].strip()
        if item in word_to_index:
            current_item_set.add(item)
    if (train):
        train_g_category_tag[index] = current_category_set
        train_g_item_tag[index] = current_item_set
    else:
        test_g_category_tag[index] = current_category_set
        test_g_item_tag[index] = current_item_set
    

for i in range(MAX_INPUT):
    read_tags(path_prefix+"tags_train/"+str(i)+".txt", True)
for i in range(MAX_OUTPUT):
    read_tags(path_prefix+"tags_test/"+str(i)+".txt", False)

In [21]:
# where to make the change
# todo: remove count to match test output
# lenpi ci, yaoshi you dehua, jianfen
# also try norm

# count_max_weight = 2.0
# uniqueness_max_weight = 2.0
# TODO: add words in tag_item to pic
def my_weight_func(index, count, train, file_num):
    if (count <= 0):
        return 0
#     count_apply = 0
#     if is_in_tag(file_num, g_word_list[index], train):
#         count_apply = 1
#     elif count >= 3:
#         count_apply = 1
#     return 1 + (len(g_word_list)-index)*uniqueness_max_weight/len(g_word_list) + count_apply*count_max_weight

#     if count >= 5:
#         return count
#     if is_in_tag(file_num, g_word_list[index], train):
#         return 5
    return 1

def weight_occurance_array(occurance_array, train, file_num):
    ret = [0] * len(occurance_array)
    for index in range(len(occurance_array)):
        ret[index] = my_weight_func(index, occurance_array[index], train, file_num)
    return ret

def read_des_to_list(path, file_num):
    ret = []
    train = (path.find("train") != -1)
    for i in range(file_num):
        int_array = [0] * len(g_word_list)
        temp_list = read_file_to_string(path+str(i)+".txt", False).split()
        for word in temp_list:
            if not word in word_to_index:
                continue
            int_array[word_to_index[word]] += 1
        ret.append(weight_occurance_array(int_array, train, i))
    return ret

train_des = read_des_to_list(path_prefix+"descriptions_train/", MAX_INPUT)
test_des = read_des_to_list(path_prefix+"descriptions_test/", MAX_OUTPUT)

In [22]:
# add tag to desc list

#TODO: careful with tag number
def add_tag_to_train_des():
    for sentence_index in range(MAX_INPUT):
        array_to_add = [0] * len(g_word_list)
        for tag in train_g_item_tag[sentence_index]:
            array_to_add[word_to_index[tag]] = 1
        
        ret = train_des[sentence_index].copy()
        for word_index in range(len(g_word_list)):
            ret[word_index] = max(ret[word_index], array_to_add[word_index])
        train_des[sentence_index] = ret

def add_tag_to_test_des():
    for sentence_index in range(MAX_OUTPUT):
        array_to_add = [0] * len(g_word_list)
        for tag in test_g_item_tag[sentence_index]:
            array_to_add[word_to_index[tag]] = 1
        
        ret = all_predict_test_des[sentence_index].copy()
        print(all_predict_test_des[sentence_index])
        for word_index in range(len(g_word_list)):
            ret[word_index] = max(ret[word_index], array_to_add[word_index])
        all_predict_test_des[sentence_index] = ret


In [23]:
add_tag_to_train_des()

In [24]:
# load feature list
def load_feature_into_list(filename):
    f = open(filename, "r")
    content = f.readlines()
    f.close()
    train = filename.find("train")
    for line in content:
        name_index = int(line.split(".jpg,")[0].split("/")[1])
        feature_list = line.split(".jpg,")[1].split(",")
        if train != -1:
            if name_index >= MAX_INPUT:
                continue
            train_feature_list[name_index] = feature_list
        else:
            if name_index >= MAX_OUTPUT:
                continue
            test_feature_list[name_index] = feature_list

train_feature_list = [0] * MAX_INPUT
test_feature_list = [0] * MAX_OUTPUT
# load_feature_into_list(path_prefix+"features_train/features_resnet1000_train.csv")
# load_feature_into_list(path_prefix+"features_test/features_resnet1000_test.csv")
load_feature_into_list(path_prefix+"features_train/features_resnet1000intermediate_train.csv")
load_feature_into_list(path_prefix+"features_test/features_resnet1000intermediate_test.csv")

train_feature_list = np.asarray(train_feature_list, dtype=np.float64)
test_feature_list = np.asarray(test_feature_list, dtype=np.float64)

In [25]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components = PCA_NUMBER)
# pca.fit(train_des)
# train_des_pca = pca.transform(train_des)
# test_des_pca = pca.transform(test_des)
train_des_pca = np.asarray(train_des)
test_des_pca = np.asarray(test_des)

print(train_des_pca.shape)
print(test_des_pca.shape)

# pca2 = PCA(n_components = PCA_NUMBER)
# pca2.fit(train_feature_list)
# train_feature_list = pca2.transform(train_feature_list)
# test_feature_list = pca2.transform(test_feature_list)
train_feature_list = np.asarray(train_feature_list)
test_feature_list = np.asarray(test_feature_list)

print(train_feature_list.shape)
print(test_feature_list.shape)

from sklearn.cross_decomposition import PLSRegression
print("Done 0")
model = PLSRegression(COMPONENTS, max_iter=ITER)
print("Done 1")
model.fit(train_feature_list, train_des_pca)
print("Done 2")

(10000, 9900)
(2000, 9900)
(10000, 2048)
(2000, 2048)
Done 0
Done 1


C:\Users\ranji\Anaconda3\lib\site-packages\sklearn\cross_decomposition\pls_.py:77: UserWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached')


Done 2


In [26]:
print("Start 3")
all_predict_test_des = model.predict(test_feature_list)
print("Done 3")

Start 3
Done 3


In [27]:
add_tag_to_test_des()

[0.00039068 0.00039068 0.00039188 ... 0.25481488 0.         0.01829317]
[0.00148874 0.00148874 0.00263842 ... 0.20535961 0.         0.21424969]
[6.13923703e-04 6.13923703e-04 1.10122180e-03 ... 3.08805349e-02
 0.00000000e+00 6.19508848e-01]
[ 0.00181366  0.00181366 -0.00130097 ...  0.19642685  0.
  0.14371268]
[ 7.23436489e-04  7.23436489e-04  6.15061361e-04 ...  7.13720322e-01
  0.00000000e+00 -1.03645831e-01]
[ 0.00102108  0.00102108 -0.00087709 ...  0.14408809  0.
 -0.11707659]
[0.00159249 0.00159249 0.00422679 ... 0.56669561 0.         0.00453848]
[6.11947752e-04 6.11947752e-04 1.17506999e-03 ... 8.23954845e-02
 0.00000000e+00 7.04167724e-01]
[ 1.05484898e-03  1.05484898e-03 -4.16495521e-04 ...  5.35602896e-01
  0.00000000e+00 -1.10734802e-01]
[ 5.89893086e-06  5.89893086e-06 -2.44405441e-03 ...  6.99816033e-01
  0.00000000e+00  7.11174928e-02]
[ 0.00020326  0.00020326 -0.00204429 ...  0.11463974  0.
  0.13975026]
[ 1.80822457e-04  1.80822457e-04 -5.13947627e-04 ...  6.76687634e-01

[-7.00177750e-04 -7.00177750e-04 -1.46470405e-03 ...  8.91173391e-01
  0.00000000e+00  6.75189880e-01]
[ 3.61745935e-04  3.61745935e-04 -1.89072457e-03 ...  6.06097264e-02
  0.00000000e+00  8.90618823e-01]
[ 0.00217741  0.00217741 -0.00134727 ... -0.25217708  0.
  0.39138097]
[1.60482635e-04 1.60482635e-04 3.34674329e-03 ... 4.46659797e-01
 0.00000000e+00 3.55498116e-03]
[-0.00125768 -0.00125768 -0.00063992 ...  0.59690052  0.
 -0.05857415]
[ 0.00293526  0.00293526 -0.00082978 ...  0.13101852  0.
 -0.14163093]
[-1.40882892e-03 -1.40882892e-03  1.68761809e-04 ...  3.27560049e-01
  0.00000000e+00  4.81263568e-01]
[-0.00109947 -0.00109947 -0.00099187 ...  0.61158074  0.
 -0.06245206]
[-0.00034106 -0.00034106 -0.00110635 ...  0.14980579  0.
  0.33876841]
[ 0.00755134  0.00755134 -0.00078054 ...  0.3632466   0.
  0.41797617]
[-0.00110008 -0.00110008 -0.0016852  ...  0.47951154  0.
 -0.03870587]
[ 0.00412251  0.00412251 -0.00148495 ...  0.20214843  0.
  0.05256635]
[ 0.00343778  0.00343778 -

 -0.03910097]
[ 0.00046823  0.00046823 -0.00064516 ...  0.43809856  0.
  0.46149462]
[ 6.88861849e-04  6.88861849e-04 -3.43438412e-04 ... -6.07949016e-02
  0.00000000e+00  5.52345237e-01]
[ 1.90685504e-04  1.90685504e-04 -1.45967867e-03 ...  2.77729528e-01
  0.00000000e+00  6.43021698e-02]
[-0.00145977 -0.00145977  0.00213455 ...  0.09655388  0.
 -0.10959533]
[-5.27572565e-05 -5.27572565e-05 -1.43198307e-03 ...  1.67335976e-01
  0.00000000e+00  5.81589474e-01]
[ 1.15195489e-03  1.15195489e-03 -2.83143702e-03 ...  5.50395556e-01
  0.00000000e+00  2.48228414e-04]
[ 0.0011102   0.0011102  -0.00086596 ... -0.1278775   0.
  0.77690997]
[0.00032195 0.00032195 0.00062494 ... 0.07114495 0.         0.2766519 ]
[ 0.00218455  0.00218455 -0.00172845 ...  0.10597735  0.
  0.18909292]
[ 3.85153809e-04  3.85153809e-04 -6.28657712e-03 ...  4.51509922e-01
  0.00000000e+00 -9.94426521e-02]
[-0.00081475 -0.00081475  0.00238806 ...  0.49597571  0.
  0.30970419]
[0.00115649 0.00115649 0.00134661 ... 0.0871

[-1.63311233e-04 -1.63311233e-04  1.22535404e-03 ...  1.75478699e-01
  0.00000000e+00  6.45734412e-01]
[ 0.00223913  0.00223913 -0.00222085 ...  0.31009857  0.
  0.06233178]
[ 0.00057307  0.00057307 -0.00512552 ...  0.41152884  0.
 -0.06589478]
[0.00144374 0.00144374 0.0016205  ... 0.40253538 0.         0.08285271]
[ 0.00037273  0.00037273 -0.00031592 ...  0.27610543  0.
  0.05818018]
[0.00082564 0.00082564 0.00072116 ... 0.1673746  0.         0.26896843]
[ 0.00054605  0.00054605  0.00037366 ...  0.05669018  0.
 -0.10077511]
[-0.00152013 -0.00152013 -0.00019657 ...  0.05582599  0.
 -0.1409499 ]
[0.00037616 0.00037616 0.00138307 ... 0.05510684 0.         0.1228385 ]
[8.25846397e-04 8.25846397e-04 2.58829691e-04 ... 2.96098160e-01
 0.00000000e+00 4.49566965e-01]
[0.00145974 0.00145974 0.00305384 ... 0.08224067 0.         0.5582328 ]
[0.00041643 0.00041643 0.00032612 ... 0.07391921 0.         0.04057781]
[-0.00055062 -0.00055062  0.00322396 ...  0.19642234  0.
  0.02307656]
[ 0.00122119  

[-0.00084798 -0.00084798 -0.0008022  ...  0.10345157  0.
  0.00842212]
[-0.00361527 -0.00361527  0.00155648 ...  0.45234199  0.
  0.24620261]
[-0.00158223 -0.00158223  0.00082299 ...  0.04217712  0.
  0.1269343 ]
[-0.00264829 -0.00264829  0.00189914 ... -0.05879409  0.
  0.02526919]
[ 0.00557055  0.00557055 -0.00072693 ...  0.15161605  0.
  0.20593106]
[ 0.00433579  0.00433579 -0.00247526 ...  0.14888436  0.
  0.10310732]
[0.00220363 0.00220363 0.00263535 ... 0.36237339 0.         0.49349035]
[ 0.00214525  0.00214525 -0.0025693  ...  0.05138523  0.
  0.53497456]
[ 0.00283263  0.00283263  0.00462422 ...  0.74170013  0.
 -0.03997917]
[ 1.46283992e-03  1.46283992e-03  6.28969921e-04 ...  8.45381861e-01
  0.00000000e+00 -8.21177523e-02]
[-0.00333809 -0.00333809  0.00412737 ...  0.22579345  0.
 -0.05374634]
[2.38945211e-03 2.38945211e-03 5.86875017e-05 ... 1.30192507e-01
 0.00000000e+00 3.59870155e-01]
[-0.0003282  -0.0003282  -0.00247174 ...  0.18305146  0.
  0.10865104]
[ 5.90789952e-04  

  0.00000000e+00 -4.51758224e-02]
[0.002112   0.002112   0.00481092 ... 0.17978251 0.         0.05158858]
[ 0.00102076  0.00102076 -0.00030835 ...  0.00295392  0.
  0.24119277]
[-0.00125751 -0.00125751  0.0002425  ...  0.19236558  0.
  0.05377232]
[ 0.00079648  0.00079648 -0.00148237 ...  0.18767878  0.
 -0.06986606]
[-1.06169555e-03 -1.06169555e-03  2.33778510e-04 ...  2.40678079e-01
  0.00000000e+00  4.62576272e-01]
[2.57105603e-05 2.57105603e-05 1.01003257e-04 ... 1.89762672e-01
 0.00000000e+00 8.21294537e-01]
[0.00054619 0.00054619 0.00213959 ... 0.38646502 0.         0.0462261 ]
[-0.00089303 -0.00089303 -0.00258884 ... -0.15146004  0.
  0.16725332]
[ 1.68745773e-04  1.68745773e-04 -5.52982116e-05 ...  5.50532450e-01
  0.00000000e+00  1.93634011e-01]
[-0.00275861 -0.00275861 -0.00146369 ...  0.52208056  0.
  0.5506428 ]
[-0.00336968 -0.00336968  0.00337665 ...  0.59936827  0.
  0.14077096]
[0.00302276 0.00302276 0.00100609 ... 0.06392196 0.         0.08374456]
[-0.00109311 -0.00109

[0.00096409 0.00096409 0.00119781 ... 0.1786185  0.         0.01958409]
[-0.0024204  -0.0024204  -0.00126363 ...  0.37676785  0.
  0.07746885]
[2.58993190e-04 2.58993190e-04 3.24360783e-03 ... 2.45479935e-01
 0.00000000e+00 4.84573020e-01]
[-0.00075392 -0.00075392 -0.00139471 ...  0.12983886  0.
 -0.04124149]
[ 0.00230088  0.00230088 -0.00089181 ...  0.20398979  0.
  0.1464896 ]
[2.83935556e-03 2.83935556e-03 4.89671059e-04 ... 5.08505555e-01
 0.00000000e+00 3.18258900e-01]
[-5.54080340e-04 -5.54080340e-04 -3.73206144e-03 ...  1.75498210e-01
  0.00000000e+00  1.01308878e+00]
[-0.00076593 -0.00076593  0.00278127 ...  0.27004181  0.
  0.00317246]
[-0.00088362 -0.00088362  0.00242049 ...  0.17480928  0.
 -0.04509321]
[-2.12533955e-03 -2.12533955e-03  3.48801569e-04 ...  2.91473575e-01
  0.00000000e+00  4.15754585e-01]
[ 0.00186577  0.00186577  0.00182358 ... -0.01281543  0.
 -0.05966442]
[-5.72483796e-05 -5.72483796e-05 -2.09429182e-03 ...  5.06400428e-01
  0.00000000e+00  1.48258482e-02]

[0.00100506 0.00100506 0.00181001 ... 0.31324677 0.         0.61005064]
[ 0.00100656  0.00100656 -0.00446093 ...  0.02208849  0.
  0.38292859]
[-1.11234792e-03 -1.11234792e-03  1.16967139e-05 ... -2.88478366e-02
  0.00000000e+00  2.77528721e-01]
[ 0.00177833  0.00177833 -0.00328076 ...  0.11509759  0.
  0.25834306]
[-4.34309815e-04 -4.34309815e-04 -1.03555493e-04 ...  3.93098717e-01
  0.00000000e+00 -1.78222919e-02]
[ 0.00176816  0.00176816  0.00070232 ... -0.15220127  0.
  0.45123081]
[-2.97405699e-04 -2.97405699e-04 -2.69998746e-03 ...  2.35971498e-01
  0.00000000e+00  3.33861793e-01]
[-0.00165305 -0.00165305  0.00917798 ...  0.12670433  0.
  0.54313144]
[-3.60204887e-04 -3.60204887e-04  2.83037286e-04 ... -1.40667800e-01
  0.00000000e+00  8.32367710e-01]
[0.0008026  0.0008026  0.00234321 ... 0.52039571 0.         0.02583042]
[-0.00041626 -0.00041626 -0.00084982 ...  0.39814169  0.
  0.26512024]
[-0.00340816 -0.00340816 -0.00228753 ...  0.61634374  0.
  0.03086792]
[ 1.32150366e-03  

[-0.00139456 -0.00139456  0.00115455 ...  0.3998699   0.
  0.15399119]
[ 1.63748770e-03  1.63748770e-03  1.44431885e-04 ...  2.32362623e-01
  0.00000000e+00 -1.36011917e-02]
[ 5.22329864e-04  5.22329864e-04 -7.97108778e-05 ...  3.23670913e-01
  0.00000000e+00  1.86179967e-01]
[ 0.00191426  0.00191426 -0.00030499 ...  0.20549799  0.
  0.05023465]
[ 0.00028297  0.00028297 -0.00417015 ...  0.02320879  0.
  0.16600025]
[ 0.00106497  0.00106497 -0.00246423 ...  0.25436667  0.
  0.00188698]
[ 1.09108446e-04  1.09108446e-04 -3.04325485e-03 ...  2.13010035e-01
  0.00000000e+00  8.42741719e-02]
[-0.00094773 -0.00094773 -0.00053543 ...  0.42519984  0.
  0.08679687]
[ 0.00122621  0.00122621 -0.00288594 ...  0.18818656  0.
 -0.12593309]
[ 0.00451061  0.00451061 -0.00179666 ...  0.1795327   0.
  0.35814646]
[ 3.88009875e-04  3.88009875e-04 -8.46606617e-05 ...  4.18726508e-01
  0.00000000e+00  1.60323715e-01]
[-4.46184350e-04 -4.46184350e-04  6.56608243e-04 ...  2.50975573e-01
  0.00000000e+00  5.98

[0.00196696 0.00196696 0.00041145 ... 0.0423091  0.         0.24288128]
[-5.70076724e-05 -5.70076724e-05 -1.23010689e-03 ...  1.20507870e-01
  0.00000000e+00  2.38146888e-02]
[ 0.00136705  0.00136705  0.00158456 ... -0.14994657  0.
  1.18030541]
[-0.00124806 -0.00124806 -0.00058175 ... -0.07132571  0.
  0.51224729]
[-1.32936778e-03 -1.32936778e-03  1.53147948e-04 ...  1.88775214e-01
  0.00000000e+00  2.10082379e-01]
[ 0.00067997  0.00067997 -0.00310226 ...  0.30846389  0.
  0.36099457]
[ 0.00170522  0.00170522 -0.00155097 ...  0.01496008  0.
  0.68850964]
[-0.00106036 -0.00106036 -0.00044788 ...  0.12620847  0.
  0.3189533 ]
[-5.46345269e-04 -5.46345269e-04 -1.91591122e-04 ...  4.46901465e-01
  0.00000000e+00 -9.63138314e-02]
[-4.38799513e-05 -4.38799513e-05  1.98955437e-03 ...  4.70754901e-01
  0.00000000e+00  1.79237853e-02]
[5.57550702e-04 5.57550702e-04 2.53181254e-03 ... 1.64709642e-01
 0.00000000e+00 6.57478530e-01]
[-0.00091738 -0.00091738  0.00295559 ...  0.42882383  0.
  0.353

[-0.0021801  -0.0021801  -0.00088373 ...  0.35147665  0.
  0.04285343]
[2.86901873e-04 2.86901873e-04 2.59306788e-03 ... 1.84509181e-01
 0.00000000e+00 6.06396584e-01]
[-0.00147014 -0.00147014 -0.00084579 ...  0.16740104  0.
  0.43499384]
[-0.00118395 -0.00118395 -0.00044098 ...  0.12700481  0.
  0.03243117]
[-0.00115425 -0.00115425  0.00081692 ...  0.60164924  0.
 -0.09719344]
[ 0.0013707   0.0013707  -0.00061957 ... -0.06558026  0.
  0.43933732]
[ 0.00073905  0.00073905  0.00469169 ...  0.55872739  0.
 -0.17583894]
[-0.00038508 -0.00038508 -0.00382489 ...  0.32891161  0.
  0.11933   ]
[0.00183954 0.00183954 0.00078204 ... 0.09348186 0.         0.17086189]
[ 0.0017099   0.0017099  -0.00167198 ...  0.35153699  0.
 -0.09613806]
[-3.84097337e-05 -3.84097337e-05  5.98736766e-04 ...  5.39259185e-01
  0.00000000e+00 -9.33502928e-03]
[-0.00352911 -0.00352911  0.00436498 ...  0.07045064  0.
  0.06383432]
[-0.00193586 -0.00193586 -0.00470856 ...  0.26798457  0.
  0.21024564]
[-0.00135157 -0.00

[-0.00277964 -0.00277964 -0.00303195 ...  0.37747133  0.
  0.55024977]
[1.30438960e-03 1.30438960e-03 1.37887263e-04 ... 5.56414783e-01
 0.00000000e+00 6.07096582e-02]
[-0.00036146 -0.00036146  0.00242146 ...  0.11037249  0.
  0.07259831]
[4.04684557e-04 4.04684557e-04 1.27137763e-03 ... 6.69509450e-01
 0.00000000e+00 9.07700627e-02]
[ 9.67275511e-04  9.67275511e-04  7.37734778e-05 ...  1.90185954e-01
  0.00000000e+00 -5.73056196e-02]
[-2.02766586e-06 -2.02766586e-06 -5.56280013e-04 ...  4.49280773e-02
  0.00000000e+00  4.98872101e-01]
[-1.24867634e-04 -1.24867634e-04 -1.45763675e-03 ... -2.16884288e-02
  0.00000000e+00  8.00992491e-01]
[-0.00188197 -0.00188197  0.00336718 ...  0.19250277  0.
  0.31468487]
[-3.29957415e-04 -3.29957415e-04  3.12956015e-04 ...  2.69016613e-02
  0.00000000e+00  4.62866022e-01]
[ 0.0039514   0.0039514  -0.00178732 ... -0.01556668  0.
  0.00196546]
[ 0.00265539  0.00265539 -0.00120481 ...  0.64455361  0.
 -0.12355082]
[ 0.00106493  0.00106493 -0.00138296 ..

[-0.00170834 -0.00170834 -0.00324121 ... -0.14798116  0.
  0.56221076]
[ 6.34537196e-05  6.34537196e-05  2.76171127e-03 ...  2.45730243e-01
  0.00000000e+00 -2.89792049e-02]
[-0.00184575 -0.00184575  0.00284486 ...  0.62182998  0.
 -0.15762342]
[-0.00152811 -0.00152811  0.00066006 ...  0.35433849  0.
  0.07353021]
[-0.00147159 -0.00147159  0.00537137 ... -0.05631166  0.
  0.92686108]
[-0.00324148 -0.00324148  0.00354548 ...  0.37802308  0.
  0.00810228]
[-0.00154766 -0.00154766  0.00045406 ...  0.10774479  0.
 -0.12702821]
[ 1.06668581e-04  1.06668581e-04 -4.56453932e-04 ...  2.93920477e-01
  0.00000000e+00 -2.92782383e-02]
[-0.00210596 -0.00210596  0.00118613 ...  0.08361107  0.
  0.68121879]
[-0.0013016  -0.0013016   0.00066693 ...  0.48083158  0.
  0.19249539]
[-0.00239964 -0.00239964 -0.00059915 ...  0.34560585  0.
 -0.00944663]
[ 0.0013485   0.0013485  -0.00375929 ...  0.28600491  0.
  0.10957972]
[-1.13166330e-03 -1.13166330e-03  4.56131125e-04 ...  2.69613547e-01
  0.00000000e+0

[0.00168378 0.00168378 0.00224688 ... 0.07160989 0.         0.80204185]
[0.00123204 0.00123204 0.00076448 ... 0.05737541 0.         0.54464232]
[-3.30113615e-04 -3.30113615e-04 -3.94747807e-03 ...  3.95866054e-01
  0.00000000e+00 -9.57117280e-02]
[ 1.56386044e-03  1.56386044e-03 -2.86787042e-04 ...  3.32510270e-01
  0.00000000e+00  6.58637564e-01]
[ 1.95932784e-04  1.95932784e-04 -3.20083198e-03 ...  2.38652041e-01
  0.00000000e+00  2.13351749e-01]
[-7.51980425e-04 -7.51980425e-04  1.59481925e-03 ...  7.87577396e-05
  0.00000000e+00  1.45529881e-01]
[-0.00214774 -0.00214774  0.00079099 ... -0.07011119  0.
  0.09231665]
[-2.91455181e-04 -2.91455181e-04  4.43482163e-04 ...  1.12148558e-01
  0.00000000e+00  5.96206096e-01]
[ 0.00575812  0.00575812  0.00473159 ... -0.10899077  0.
  0.01157297]
[-9.96273485e-05 -9.96273485e-05  8.08473022e-03 ...  4.20657917e-01
  0.00000000e+00  1.18445448e-01]
[-0.00057286 -0.00057286  0.00179983 ...  0.32685304  0.
  0.06339486]
[-0.00248018 -0.00248018 

[-0.00438813 -0.00438813 -0.00178423 ...  0.16058925  0.
  0.41253387]
[-0.00273472 -0.00273472  0.00463388 ...  0.21004037  0.
 -0.05843223]
[ 0.00150695  0.00150695 -0.00134247 ...  0.32074526  0.
  0.12515364]
[ 1.14270562e-03  1.14270562e-03 -4.88525436e-04 ...  4.26243880e-01
  0.00000000e+00  6.76904415e-01]
[2.10925871e-04 2.10925871e-04 1.63143359e-03 ... 3.67550388e-01
 0.00000000e+00 5.22840465e-01]
[ 0.00121267  0.00121267 -0.00301104 ...  0.55620454  0.
  0.1644853 ]
[-3.72930556e-04 -3.72930556e-04 -7.33238174e-04 ...  1.36032147e-01
  0.00000000e+00  4.65157633e-01]
[-1.13741004e-03 -1.13741004e-03  6.90016353e-05 ...  1.71252694e-01
  0.00000000e+00  4.98890033e-01]
[ 4.18663987e-04  4.18663987e-04 -1.33817691e-04 ...  3.07283754e-01
  0.00000000e+00 -3.31600005e-02]
[-0.0015574  -0.0015574   0.00310313 ...  0.63004385  0.
 -0.05711508]
[-0.00371204 -0.00371204 -0.00217177 ... -0.04959496  0.
 -0.07665976]
[ 2.74511408e-03  2.74511408e-03 -5.74259621e-04 ...  1.46277345e

[0.00187559 0.00187559 0.00258346 ... 0.31467094 0.         0.43557598]
[ 1.76327078e-04  1.76327078e-04 -7.64609118e-04 ...  2.66420038e-01
  0.00000000e+00  3.31411896e-01]
[-0.00020197 -0.00020197  0.00541689 ...  0.17181412  0.
  0.052558  ]
[ 1.92318075e-04  1.92318075e-04 -3.04345593e-03 ...  3.09285531e-01
  0.00000000e+00 -7.48924705e-02]
[ 1.05693913e-03  1.05693913e-03 -3.67240245e-04 ...  7.10916405e-01
  0.00000000e+00  4.70976086e-01]
[ 0.00484004  0.00484004 -0.00099843 ...  0.11290742  0.
  0.6618241 ]
[0.00063237 0.00063237 0.0015869  ... 0.44626849 0.         0.06264734]
[ 0.0003633   0.0003633  -0.00072701 ...  0.3447513   0.
  0.02463275]
[-4.20557691e-04 -4.20557691e-04  1.66471693e-03 ... -5.61211345e-02
  0.00000000e+00  8.81071004e-01]
[0.00198362 0.00198362 0.00086425 ... 0.59286275 0.         0.10357954]
[ 0.00456854  0.00456854 -0.00243662 ...  0.40258506  0.
  0.12064363]
[-0.00274806 -0.00274806 -0.00406622 ...  0.52151266  0.
  0.59627771]
[ 1.92255583e-04 

[-0.00179368 -0.00179368  0.01222403 ...  0.26388899  0.
  0.27420828]
[ 5.60422995e-04  5.60422995e-04  1.54981516e-04 ...  4.22117176e-01
  0.00000000e+00 -1.44918393e-01]
[-0.0016711  -0.0016711  -0.00166016 ...  0.4345232   0.
 -0.00384957]
[ 0.00056841  0.00056841 -0.00053164 ...  0.52153011  0.
  0.21518125]
[-0.00194124 -0.00194124 -0.00281316 ...  0.69453333  0.
  0.05990613]
[0.00062861 0.00062861 0.0036382  ... 0.3980912  0.         0.152005  ]
[ 3.83642352e-03  3.83642352e-03 -1.58611182e-04 ...  4.25811531e-01
  0.00000000e+00  9.73642418e-02]
[ 0.00286372  0.00286372  0.00110232 ...  0.39952177  0.
 -0.16912284]
[-0.00234094 -0.00234094 -0.00242765 ...  0.01999888  0.
  0.77852798]
[ 0.00084275  0.00084275 -0.00121804 ...  0.14603278  0.
  0.07480896]
[-4.39810136e-04 -4.39810136e-04 -1.92045973e-03 ...  4.93871244e-01
  0.00000000e+00  4.10441350e-01]
[-7.86481598e-05 -7.86481598e-05  8.18598885e-04 ...  2.64448001e-01
  0.00000000e+00  3.29372580e-01]
[-0.00408243 -0.004

[-0.00300355 -0.00300355  0.00065737 ...  0.44657076  0.
  0.31945699]
[-0.00065234 -0.00065234 -0.00157738 ...  0.29940627  0.
  0.01893687]
[-0.00219023 -0.00219023  0.00206225 ...  0.3032082   0.
  0.11330785]
[ 0.00466008  0.00466008 -0.00090979 ...  0.22514111  0.
  0.25655673]
[0.0015265  0.0015265  0.00216676 ... 0.36490503 0.         0.241788  ]
[0.00262266 0.00262266 0.00162438 ... 0.43431194 0.         0.01463287]
[ 0.00057629  0.00057629  0.00094225 ...  0.38892377  0.
 -0.03959919]
[-0.00154688 -0.00154688 -0.00056404 ...  0.11925277  0.
  0.48870397]
[-0.00136464 -0.00136464  0.00761877 ...  0.09441549  0.
  0.08401541]
[-0.00068349 -0.00068349 -0.00311233 ...  0.21885741  0.
  0.2409959 ]
[-0.00116551 -0.00116551  0.00063728 ...  0.22486454  0.
  0.56068773]
[4.48725472e-04 4.48725472e-04 3.78866222e-03 ... 7.86650797e-02
 0.00000000e+00 6.50002226e-01]
[ 0.00043462  0.00043462  0.00265406 ... -0.06246895  0.
  0.32260828]
[-0.00056863 -0.00056863  0.003764   ...  0.50821

  0.57556516]
[ 0.00068867  0.00068867 -0.00221756 ... -0.013041    0.
 -0.05799137]
[ 1.15050159e-03  1.15050159e-03 -1.84878349e-04 ...  4.45195899e-01
  0.00000000e+00  1.63862594e-01]
[ 0.00274819  0.00274819 -0.00242305 ...  0.3099215   0.
 -0.18407106]
[ 0.00177685  0.00177685  0.00066688 ...  0.50786703  0.
 -0.20061531]
[-0.00214134 -0.00214134  0.00455215 ...  0.29995084  0.
  0.11095297]
[ 0.00138519  0.00138519 -0.00086442 ...  0.38760671  0.
  0.22074816]
[ 0.00483117  0.00483117 -0.00220214 ...  0.27308661  0.
  0.08134694]
[-0.00151789 -0.00151789  0.00183281 ...  0.42962626  0.
 -0.16153948]
[ 0.00136691  0.00136691  0.00326281 ...  0.06946875  0.
 -0.06661511]
[-1.54911577e-04 -1.54911577e-04 -3.01042762e-03 ...  3.70990001e-01
  0.00000000e+00 -8.91528945e-03]
[ 0.00088999  0.00088999 -0.00133975 ...  0.02282372  0.
  0.19556799]
[7.12383468e-04 7.12383468e-04 2.00289086e-04 ... 2.51808592e-02
 0.00000000e+00 2.20262810e-01]
[0.00200125 0.00200125 0.00711891 ... 0.5716

[ 0.00146707  0.00146707 -0.0011431  ...  0.13974095  0.
  0.67394038]
[0.00102011 0.00102011 0.00055341 ... 0.23728513 0.         0.24590781]
[ 0.00129713  0.00129713 -0.001633   ...  0.23367589  0.
  0.35304769]
[0.00269714 0.00269714 0.00041914 ... 0.37243893 0.         0.03771517]
[0.00247206 0.00247206 0.00127799 ... 0.17332957 0.         0.23069157]
[ 1.06810106e-03  1.06810106e-03 -9.74564038e-05 ...  4.38040266e-01
  0.00000000e+00  1.57688091e-02]
[ 0.00128906  0.00128906 -0.00266941 ...  0.34682928  0.
  0.13268469]
[-2.37341163e-03 -2.37341163e-03  3.32804713e-04 ...  3.46210359e-01
  0.00000000e+00  5.29223444e-02]
[-0.00109144 -0.00109144  0.0021844  ...  0.68685207  0.
 -0.01071344]


In [28]:
import sklearn.metrics

# return a score
def compare_feature(target, given):
    return float(sklearn.metrics.pairwise.cosine_distances([np.array(target, dtype=float)], [np.array(given, dtype=float)]))
#     return float(np.linalg.norm(np.array(target, dtype=float) - np.array(given, dtype=float)))

def get_top_20(target):
    ret = []
    for index in range(MAX_OUTPUT):
        given = all_predict_test_des[index]
        score = compare_feature(target, given)
        item = str(score) + "___" + str(index)
        ret.append(item)
    return sorted(ret, key=functools.cmp_to_key(cmp))[:20]

# f = open("reverse_count_"+str(count_max_weight)+"unique"+str(uniqueness_max_weight)+".csv", "w")
f = open("reverse_count_weight_canary.csv", "w")
f.write("Descritpion_ID,Top_20_Image_IDs\n")
for index in range(MAX_OUTPUT):
    target_desc = test_des_pca[index]
    twenty_image_list = get_top_20(target_desc)
    string_to_write = "" + str(index) + ".txt,"
    for name in twenty_image_list:
        file_name = name.split("___")[1] + ".jpg"+" "
        string_to_write += file_name
    string_to_write = string_to_write.strip() + "\n"
    print(string_to_write)
    f.write(string_to_write)

f.close()

0.txt,1105.jpg 1702.jpg 93.jpg 1420.jpg 1648.jpg 860.jpg 338.jpg 714.jpg 1107.jpg 1574.jpg 561.jpg 1480.jpg 1135.jpg 1344.jpg 292.jpg 1033.jpg 700.jpg 375.jpg 255.jpg 1962.jpg

1.txt,833.jpg 589.jpg 818.jpg 1529.jpg 457.jpg 1116.jpg 1807.jpg 80.jpg 508.jpg 169.jpg 809.jpg 1742.jpg 1071.jpg 314.jpg 1156.jpg 948.jpg 1820.jpg 1143.jpg 331.jpg 1199.jpg

2.txt,1724.jpg 1840.jpg 598.jpg 649.jpg 1030.jpg 1208.jpg 838.jpg 1421.jpg 159.jpg 1713.jpg 332.jpg 445.jpg 1665.jpg 1084.jpg 1059.jpg 1437.jpg 42.jpg 1366.jpg 1471.jpg 1866.jpg

3.txt,1101.jpg 1024.jpg 26.jpg 1514.jpg 770.jpg 1778.jpg 1215.jpg 1609.jpg 1035.jpg 1765.jpg 374.jpg 1620.jpg 207.jpg 469.jpg 1415.jpg 1207.jpg 1513.jpg 750.jpg 71.jpg 843.jpg

4.txt,742.jpg 292.jpg 1816.jpg 1263.jpg 922.jpg 594.jpg 413.jpg 1231.jpg 712.jpg 1203.jpg 1131.jpg 359.jpg 484.jpg 1187.jpg 1620.jpg 1269.jpg 1258.jpg 549.jpg 1105.jpg 1423.jpg

5.txt,771.jpg 51.jpg 492.jpg 1991.jpg 330.jpg 1693.jpg 1335.jpg 814.jpg 1874.jpg 703.jpg 1660.jpg 846.jpg 1426.jpg

47.txt,1767.jpg 223.jpg 148.jpg 1536.jpg 925.jpg 441.jpg 234.jpg 1928.jpg 1632.jpg 1149.jpg 986.jpg 174.jpg 817.jpg 874.jpg 1661.jpg 1133.jpg 340.jpg 1731.jpg 573.jpg 709.jpg

48.txt,445.jpg 1713.jpg 953.jpg 1866.jpg 1840.jpg 1724.jpg 159.jpg 634.jpg 1665.jpg 934.jpg 1033.jpg 1664.jpg 883.jpg 696.jpg 838.jpg 904.jpg 1183.jpg 979.jpg 1641.jpg 1242.jpg

49.txt,892.jpg 1743.jpg 1136.jpg 942.jpg 595.jpg 147.jpg 586.jpg 761.jpg 1131.jpg 1924.jpg 1135.jpg 1350.jpg 1396.jpg 697.jpg 1267.jpg 484.jpg 642.jpg 118.jpg 1936.jpg 1526.jpg

50.txt,183.jpg 1534.jpg 1190.jpg 1832.jpg 932.jpg 1290.jpg 560.jpg 1711.jpg 384.jpg 1432.jpg 415.jpg 1703.jpg 1223.jpg 91.jpg 1469.jpg 54.jpg 1302.jpg 886.jpg 1022.jpg 1363.jpg

51.txt,1727.jpg 1404.jpg 514.jpg 1215.jpg 26.jpg 1207.jpg 1379.jpg 1145.jpg 989.jpg 770.jpg 475.jpg 1263.jpg 1070.jpg 960.jpg 1962.jpg 1052.jpg 1734.jpg 1097.jpg 731.jpg 1889.jpg

52.txt,1926.jpg 346.jpg 1746.jpg 745.jpg 1798.jpg 1137.jpg 620.jpg 1846.jpg 914.jpg 1877.jpg 880.jpg 1236.jpg 

94.txt,1143.jpg 885.jpg 1039.jpg 835.jpg 331.jpg 1116.jpg 286.jpg 1807.jpg 1714.jpg 1408.jpg 1550.jpg 571.jpg 1313.jpg 515.jpg 1835.jpg 160.jpg 1196.jpg 14.jpg 1173.jpg 1689.jpg

95.txt,51.jpg 1335.jpg 492.jpg 814.jpg 771.jpg 1426.jpg 1693.jpg 846.jpg 1943.jpg 703.jpg 630.jpg 1913.jpg 526.jpg 330.jpg 1888.jpg 274.jpg 20.jpg 1991.jpg 1118.jpg 940.jpg

96.txt,1713.jpg 1840.jpg 445.jpg 1724.jpg 634.jpg 696.jpg 953.jpg 1665.jpg 904.jpg 838.jpg 1471.jpg 1366.jpg 159.jpg 1023.jpg 1084.jpg 883.jpg 579.jpg 1866.jpg 979.jpg 1242.jpg

97.txt,690.jpg 1664.jpg 1483.jpg 1033.jpg 1440.jpg 607.jpg 938.jpg 1605.jpg 319.jpg 445.jpg 1211.jpg 1008.jpg 1460.jpg 1487.jpg 1739.jpg 1562.jpg 399.jpg 1853.jpg 1508.jpg 1027.jpg

98.txt,899.jpg 712.jpg 414.jpg 1821.jpg 1584.jpg 1333.jpg 1734.jpg 1758.jpg 1655.jpg 1289.jpg 770.jpg 1377.jpg 549.jpg 1620.jpg 217.jpg 1020.jpg 996.jpg 1101.jpg 648.jpg 1311.jpg

99.txt,1683.jpg 830.jpg 1825.jpg 1417.jpg 1267.jpg 1685.jpg 1585.jpg 1374.jpg 1576.jpg 1640.jpg 966.jpg 172

141.txt,1127.jpg 37.jpg 1385.jpg 1098.jpg 2.jpg 31.jpg 1736.jpg 636.jpg 1696.jpg 1577.jpg 1568.jpg 670.jpg 1318.jpg 1676.jpg 1552.jpg 1236.jpg 52.jpg 1774.jpg 1415.jpg 1433.jpg

142.txt,890.jpg 1014.jpg 1304.jpg 251.jpg 713.jpg 301.jpg 1160.jpg 988.jpg 423.jpg 1951.jpg 380.jpg 1578.jpg 961.jpg 83.jpg 963.jpg 1863.jpg 1159.jpg 1299.jpg 1182.jpg 1549.jpg

143.txt,1713.jpg 445.jpg 953.jpg 1665.jpg 1724.jpg 1641.jpg 1124.jpg 1664.jpg 784.jpg 1033.jpg 634.jpg 1840.jpg 1366.jpg 1866.jpg 1208.jpg 1242.jpg 669.jpg 696.jpg 117.jpg 1030.jpg

144.txt,1077.jpg 1609.jpg 1024.jpg 717.jpg 843.jpg 1769.jpg 1720.jpg 749.jpg 1222.jpg 1553.jpg 943.jpg 1430.jpg 1185.jpg 1413.jpg 729.jpg 1382.jpg 397.jpg 1500.jpg 626.jpg 647.jpg

145.txt,692.jpg 1563.jpg 694.jpg 1246.jpg 513.jpg 1079.jpg 1869.jpg 1080.jpg 780.jpg 665.jpg 1537.jpg 278.jpg 1652.jpg 1811.jpg 1229.jpg 1983.jpg 945.jpg 396.jpg 1378.jpg 499.jpg

146.txt,111.jpg 1931.jpg 1987.jpg 1833.jpg 1556.jpg 1864.jpg 1618.jpg 1674.jpg 860.jpg 561.jpg 1648.j

188.txt,1104.jpg 1829.jpg 327.jpg 551.jpg 277.jpg 1583.jpg 283.jpg 1766.jpg 241.jpg 1467.jpg 1947.jpg 195.jpg 1390.jpg 447.jpg 1604.jpg 710.jpg 248.jpg 1387.jpg 1946.jpg 472.jpg

189.txt,1632.jpg 148.jpg 802.jpg 986.jpg 1930.jpg 709.jpg 1767.jpg 618.jpg 1403.jpg 325.jpg 85.jpg 925.jpg 474.jpg 852.jpg 71.jpg 161.jpg 547.jpg 573.jpg 1418.jpg 1996.jpg

190.txt,1640.jpg 1579.jpg 1744.jpg 1150.jpg 1859.jpg 1038.jpg 1685.jpg 1728.jpg 405.jpg 1683.jpg 173.jpg 1587.jpg 612.jpg 988.jpg 369.jpg 307.jpg 276.jpg 1578.jpg 1585.jpg 746.jpg

191.txt,1103.jpg 1213.jpg 141.jpg 210.jpg 498.jpg 1046.jpg 1384.jpg 734.jpg 1050.jpg 620.jpg 2.jpg 256.jpg 112.jpg 534.jpg 964.jpg 1087.jpg 1466.jpg 101.jpg 70.jpg 1856.jpg

192.txt,1143.jpg 885.jpg 331.jpg 1807.jpg 1039.jpg 1408.jpg 286.jpg 160.jpg 1134.jpg 1550.jpg 169.jpg 815.jpg 1806.jpg 121.jpg 553.jpg 571.jpg 1068.jpg 1196.jpg 14.jpg 296.jpg

193.txt,54.jpg 1210.jpg 1290.jpg 1363.jpg 1022.jpg 1832.jpg 1703.jpg 1775.jpg 1708.jpg 886.jpg 1123.jpg 1534.jpg 171

234.txt,801.jpg 1697.jpg 1861.jpg 1669.jpg 176.jpg 1908.jpg 1081.jpg 1054.jpg 1372.jpg 613.jpg 1590.jpg 1784.jpg 867.jpg 1619.jpg 874.jpg 109.jpg 452.jpg 8.jpg 211.jpg 697.jpg

235.txt,499.jpg 780.jpg 578.jpg 1378.jpg 1294.jpg 324.jpg 733.jpg 1007.jpg 1019.jpg 1058.jpg 827.jpg 1994.jpg 707.jpg 1964.jpg 1805.jpg 385.jpg 1148.jpg 1256.jpg 278.jpg 129.jpg

236.txt,932.jpg 1832.jpg 1534.jpg 10.jpg 1056.jpg 1703.jpg 886.jpg 560.jpg 1078.jpg 183.jpg 1469.jpg 1190.jpg 1448.jpg 384.jpg 577.jpg 1708.jpg 1210.jpg 1711.jpg 1290.jpg 1223.jpg

237.txt,1307.jpg 708.jpg 440.jpg 439.jpg 64.jpg 1952.jpg 1297.jpg 194.jpg 70.jpg 210.jpg 544.jpg 1745.jpg 1441.jpg 1339.jpg 1235.jpg 1376.jpg 1970.jpg 1621.jpg 673.jpg 1623.jpg

238.txt,1378.jpg 385.jpg 499.jpg 578.jpg 707.jpg 1964.jpg 780.jpg 291.jpg 278.jpg 1294.jpg 1805.jpg 324.jpg 1019.jpg 1422.jpg 1349.jpg 1490.jpg 733.jpg 1356.jpg 1007.jpg 1586.jpg

239.txt,1533.jpg 1118.jpg 1693.jpg 20.jpg 846.jpg 492.jpg 1426.jpg 1888.jpg 1943.jpg 1335.jpg 814.jpg 51.

280.txt,16.jpg 1790.jpg 1701.jpg 262.jpg 1139.jpg 1540.jpg 582.jpg 489.jpg 1444.jpg 718.jpg 1944.jpg 391.jpg 655.jpg 897.jpg 1151.jpg 535.jpg 1933.jpg 1216.jpg 429.jpg 1352.jpg

281.txt,1604.jpg 241.jpg 472.jpg 327.jpg 1747.jpg 581.jpg 664.jpg 1467.jpg 1048.jpg 195.jpg 1946.jpg 955.jpg 1766.jpg 403.jpg 679.jpg 1544.jpg 558.jpg 1829.jpg 1425.jpg 277.jpg

282.txt,471.jpg 960.jpg 26.jpg 1207.jpg 1215.jpg 731.jpg 1101.jpg 1145.jpg 1614.jpg 1187.jpg 71.jpg 1889.jpg 1070.jpg 1778.jpg 971.jpg 573.jpg 1097.jpg 941.jpg 1415.jpg 728.jpg

283.txt,109.jpg 1973.jpg 997.jpg 1341.jpg 1054.jpg 804.jpg 1861.jpg 1934.jpg 1669.jpg 666.jpg 189.jpg 757.jpg 801.jpg 1325.jpg 392.jpg 1759.jpg 1784.jpg 613.jpg 815.jpg 1642.jpg

284.txt,1586.jpg 1169.jpg 385.jpg 759.jpg 1019.jpg 854.jpg 733.jpg 1378.jpg 780.jpg 491.jpg 1964.jpg 1545.jpg 1994.jpg 499.jpg 1805.jpg 1058.jpg 578.jpg 707.jpg 324.jpg 454.jpg

285.txt,369.jpg 466.jpg 1846.jpg 405.jpg 1167.jpg 1728.jpg 1137.jpg 1106.jpg 307.jpg 729.jpg 1280.jpg 407.jpg

327.txt,1732.jpg 1406.jpg 534.jpg 536.jpg 1722.jpg 1715.jpg 1062.jpg 1036.jpg 1445.jpg 1042.jpg 1602.jpg 1520.jpg 1416.jpg 684.jpg 1082.jpg 1721.jpg 1539.jpg 1115.jpg 31.jpg 522.jpg

328.txt,964.jpg 210.jpg 522.jpg 1213.jpg 1400.jpg 498.jpg 101.jpg 1602.jpg 744.jpg 69.jpg 1062.jpg 534.jpg 921.jpg 512.jpg 1224.jpg 734.jpg 1715.jpg 536.jpg 1972.jpg 1732.jpg

329.txt,1374.jpg 1576.jpg 1683.jpg 1825.jpg 966.jpg 1585.jpg 1323.jpg 1892.jpg 357.jpg 1267.jpg 830.jpg 1117.jpg 1756.jpg 164.jpg 1178.jpg 1417.jpg 138.jpg 832.jpg 776.jpg 1204.jpg

330.txt,1640.jpg 752.jpg 686.jpg 1760.jpg 1859.jpg 1093.jpg 1329.jpg 1438.jpg 1708.jpg 1150.jpg 1775.jpg 494.jpg 418.jpg 427.jpg 239.jpg 460.jpg 1579.jpg 1140.jpg 1368.jpg 1900.jpg

331.txt,1033.jpg 1366.jpg 1340.jpg 1665.jpg 184.jpg 1208.jpg 1574.jpg 1716.jpg 1475.jpg 1499.jpg 1421.jpg 696.jpg 1124.jpg 1702.jpg 1648.jpg 607.jpg 649.jpg 1344.jpg 866.jpg 821.jpg

332.txt,572.jpg 1029.jpg 1959.jpg 5.jpg 261.jpg 538.jpg 23.jpg 1806.jpg 1742.jpg 200.jpg 820.j

374.txt,397.jpg 1185.jpg 1769.jpg 1609.jpg 90.jpg 799.jpg 1035.jpg 1513.jpg 913.jpg 686.jpg 1755.jpg 1514.jpg 75.jpg 654.jpg 1865.jpg 1024.jpg 872.jpg 1383.jpg 800.jpg 1553.jpg

375.txt,1384.jpg 1298.jpg 849.jpg 620.jpg 70.jpg 1561.jpg 112.jpg 921.jpg 210.jpg 1451.jpg 947.jpg 1862.jpg 116.jpg 1510.jpg 549.jpg 1838.jpg 1213.jpg 498.jpg 1087.jpg 930.jpg

376.txt,1701.jpg 16.jpg 1472.jpg 1790.jpg 1444.jpg 1139.jpg 582.jpg 489.jpg 718.jpg 262.jpg 1944.jpg 1540.jpg 1216.jpg 429.jpg 1815.jpg 1660.jpg 655.jpg 1885.jpg 1352.jpg 1151.jpg

377.txt,1622.jpg 1001.jpg 1948.jpg 727.jpg 1918.jpg 162.jpg 692.jpg 719.jpg 1079.jpg 1324.jpg 639.jpg 548.jpg 874.jpg 103.jpg 1983.jpg 166.jpg 1397.jpg 1031.jpg 1037.jpg 1975.jpg

378.txt,50.jpg 1286.jpg 1250.jpg 226.jpg 93.jpg 541.jpg 502.jpg 1047.jpg 599.jpg 678.jpg 1018.jpg 92.jpg 305.jpg 594.jpg 1410.jpg 202.jpg 723.jpg 698.jpg 246.jpg 1521.jpg

379.txt,1757.jpg 668.jpg 1147.jpg 968.jpg 1341.jpg 809.jpg 738.jpg 1381.jpg 6.jpg 107.jpg 1628.jpg 562.jpg 1507.

421.txt,1937.jpg 12.jpg 286.jpg 1456.jpg 1526.jpg 1679.jpg 1481.jpg 1204.jpg 1110.jpg 626.jpg 586.jpg 121.jpg 721.jpg 118.jpg 926.jpg 729.jpg 1726.jpg 1135.jpg 353.jpg 1504.jpg

422.txt,1012.jpg 853.jpg 688.jpg 1441.jpg 128.jpg 1621.jpg 214.jpg 1623.jpg 269.jpg 1813.jpg 151.jpg 721.jpg 544.jpg 1984.jpg 1364.jpg 1893.jpg 87.jpg 1376.jpg 906.jpg 64.jpg

423.txt,1187.jpg 269.jpg 214.jpg 853.jpg 1012.jpg 289.jpg 128.jpg 194.jpg 1376.jpg 1765.jpg 1893.jpg 1936.jpg 1984.jpg 1203.jpg 1715.jpg 544.jpg 64.jpg 1400.jpg 1621.jpg 1364.jpg

424.txt,1044.jpg 235.jpg 1420.jpg 541.jpg 747.jpg 1000.jpg 1047.jpg 502.jpg 1361.jpg 1521.jpg 656.jpg 594.jpg 374.jpg 773.jpg 246.jpg 1250.jpg 167.jpg 93.jpg 1286.jpg 202.jpg

425.txt,1249.jpg 1285.jpg 1961.jpg 1270.jpg 1488.jpg 168.jpg 1085.jpg 689.jpg 1328.jpg 1155.jpg 685.jpg 1694.jpg 448.jpg 627.jpg 481.jpg 987.jpg 409.jpg 794.jpg 1900.jpg 1302.jpg

426.txt,418.jpg 1263.jpg 1231.jpg 1900.jpg 1270.jpg 1804.jpg 256.jpg 902.jpg 54.jpg 1262.jpg 1165.jpg 1329.jpg

468.txt,708.jpg 1621.jpg 1813.jpg 544.jpg 439.jpg 1364.jpg 1297.jpg 1952.jpg 64.jpg 1970.jpg 1473.jpg 128.jpg 777.jpg 1012.jpg 269.jpg 1235.jpg 194.jpg 929.jpg 688.jpg 853.jpg

469.txt,1365.jpg 266.jpg 579.jpg 1336.jpg 1901.jpg 1557.jpg 1525.jpg 343.jpg 1611.jpg 1690.jpg 1896.jpg 1346.jpg 979.jpg 982.jpg 24.jpg 1013.jpg 1389.jpg 1004.jpg 1010.jpg 1031.jpg

470.txt,499.jpg 1019.jpg 1805.jpg 706.jpg 952.jpg 385.jpg 1378.jpg 827.jpg 1854.jpg 1586.jpg 324.jpg 707.jpg 1356.jpg 578.jpg 780.jpg 1058.jpg 1964.jpg 491.jpg 129.jpg 1274.jpg

471.txt,247.jpg 80.jpg 1507.jpg 668.jpg 738.jpg 482.jpg 6.jpg 314.jpg 818.jpg 1999.jpg 527.jpg 149.jpg 1141.jpg 1369.jpg 1334.jpg 1807.jpg 1143.jpg 1158.jpg 1102.jpg 1615.jpg

472.txt,410.jpg 384.jpg 951.jpg 807.jpg 1802.jpg 1890.jpg 1624.jpg 143.jpg 627.jpg 1711.jpg 1132.jpg 1932.jpg 1491.jpg 989.jpg 728.jpg 1449.jpg 1903.jpg 1905.jpg 409.jpg 1190.jpg

473.txt,1278.jpg 517.jpg 315.jpg 363.jpg 713.jpg 988.jpg 854.jpg 301.jpg 1252.jpg 1688.jpg 795.jpg 622.jpg 

515.txt,856.jpg 831.jpg 193.jpg 1546.jpg 461.jpg 610.jpg 125.jpg 123.jpg 1869.jpg 503.jpg 1963.jpg 352.jpg 1838.jpg 442.jpg 974.jpg 1957.jpg 297.jpg 1142.jpg 1629.jpg 1858.jpg

516.txt,15.jpg 821.jpg 768.jpg 934.jpg 1987.jpg 1059.jpg 1084.jpg 1840.jpg 111.jpg 1421.jpg 1023.jpg 1618.jpg 120.jpg 260.jpg 1665.jpg 1674.jpg 1931.jpg 1833.jpg 134.jpg 1648.jpg

517.txt,1293.jpg 1649.jpg 1332.jpg 876.jpg 889.jpg 1531.jpg 490.jpg 855.jpg 520.jpg 1419.jpg 1495.jpg 1939.jpg 1687.jpg 961.jpg 119.jpg 11.jpg 1303.jpg 311.jpg 1055.jpg 1163.jpg

518.txt,759.jpg 1169.jpg 1019.jpg 1058.jpg 385.jpg 454.jpg 780.jpg 733.jpg 1964.jpg 491.jpg 499.jpg 1545.jpg 578.jpg 324.jpg 854.jpg 827.jpg 1994.jpg 1378.jpg 795.jpg 1586.jpg

519.txt,1925.jpg 1200.jpg 307.jpg 653.jpg 1167.jpg 1171.jpg 612.jpg 270.jpg 1728.jpg 405.jpg 1106.jpg 464.jpg 308.jpg 1497.jpg 1587.jpg 787.jpg 32.jpg 468.jpg 1695.jpg 1827.jpg

520.txt,409.jpg 627.jpg 1085.jpg 987.jpg 448.jpg 1285.jpg 1694.jpg 689.jpg 1249.jpg 415.jpg 168.jpg 1223.jpg 

561.txt,1233.jpg 692.jpg 934.jpg 1811.jpg 62.jpg 1391.jpg 1229.jpg 1048.jpg 831.jpg 694.jpg 1563.jpg 311.jpg 461.jpg 1537.jpg 1899.jpg 123.jpg 621.jpg 1079.jpg 1931.jpg 1730.jpg

562.txt,1017.jpg 1395.jpg 483.jpg 1527.jpg 1451.jpg 1092.jpg 967.jpg 1369.jpg 949.jpg 1099.jpg 529.jpg 1428.jpg 1636.jpg 149.jpg 1205.jpg 1756.jpg 1360.jpg 1120.jpg 1726.jpg 1237.jpg

563.txt,620.jpg 1307.jpg 921.jpg 964.jpg 210.jpg 1434.jpg 439.jpg 70.jpg 1952.jpg 498.jpg 1213.jpg 744.jpg 1235.jpg 64.jpg 708.jpg 440.jpg 1376.jpg 734.jpg 194.jpg 544.jpg

564.txt,1520.jpg 684.jpg 1732.jpg 1633.jpg 1036.jpg 1602.jpg 1406.jpg 1722.jpg 536.jpg 1715.jpg 101.jpg 1445.jpg 1870.jpg 74.jpg 1074.jpg 522.jpg 1062.jpg 1042.jpg 1974.jpg 1681.jpg

565.txt,1811.jpg 1563.jpg 1537.jpg 123.jpg 694.jpg 1869.jpg 819.jpg 1079.jpg 945.jpg 1246.jpg 692.jpg 1506.jpg 1080.jpg 513.jpg 1548.jpg 1229.jpg 383.jpg 831.jpg 100.jpg 931.jpg

566.txt,448.jpg 689.jpg 1694.jpg 1085.jpg 1285.jpg 1961.jpg 1488.jpg 987.jpg 1249.jpg 91.jpg 794.jpg 4

607.txt,886.jpg 1056.jpg 54.jpg 1832.jpg 1703.jpg 1363.jpg 1534.jpg 1290.jpg 1022.jpg 560.jpg 1775.jpg 1711.jpg 1210.jpg 1448.jpg 1190.jpg 1078.jpg 183.jpg 1123.jpg 591.jpg 1616.jpg

608.txt,54.jpg 1708.jpg 1210.jpg 1703.jpg 886.jpg 1290.jpg 59.jpg 418.jpg 1534.jpg 1775.jpg 686.jpg 239.jpg 944.jpg 320.jpg 560.jpg 1961.jpg 432.jpg 1056.jpg 1362.jpg 1363.jpg

609.txt,1059.jpg 1665.jpg 1421.jpg 1030.jpg 1084.jpg 649.jpg 1471.jpg 1208.jpg 1366.jpg 696.jpg 1023.jpg 821.jpg 904.jpg 763.jpg 1840.jpg 634.jpg 1437.jpg 1475.jpg 1340.jpg 1724.jpg

610.txt,558.jpg 1829.jpg 1947.jpg 195.jpg 1244.jpg 241.jpg 327.jpg 1390.jpg 472.jpg 277.jpg 551.jpg 1583.jpg 1604.jpg 1747.jpg 1104.jpg 1884.jpg 283.jpg 1467.jpg 248.jpg 1766.jpg

611.txt,1732.jpg 1445.jpg 1722.jpg 1042.jpg 1870.jpg 684.jpg 536.jpg 1036.jpg 1633.jpg 1681.jpg 1074.jpg 1520.jpg 1602.jpg 1406.jpg 584.jpg 1721.jpg 1974.jpg 1115.jpg 565.jpg 1062.jpg

612.txt,45.jpg 1536.jpg 656.jpg 234.jpg 1149.jpg 19.jpg 1176.jpg 1928.jpg 1691.jpg 340.jpg 6

653.txt,986.jpg 85.jpg 148.jpg 218.jpg 1767.jpg 852.jpg 1632.jpg 618.jpg 1403.jpg 1930.jpg 925.jpg 71.jpg 709.jpg 325.jpg 1997.jpg 802.jpg 188.jpg 446.jpg 547.jpg 161.jpg

654.txt,841.jpg 1484.jpg 633.jpg 717.jpg 1547.jpg 268.jpg 1057.jpg 1330.jpg 1500.jpg 1816.jpg 389.jpg 208.jpg 683.jpg 999.jpg 153.jpg 1382.jpg 629.jpg 1837.jpg 1222.jpg 192.jpg

655.txt,70.jpg 101.jpg 921.jpg 498.jpg 744.jpg 74.jpg 534.jpg 1602.jpg 684.jpg 210.jpg 1213.jpg 964.jpg 1715.jpg 1454.jpg 1732.jpg 522.jpg 1062.jpg 1520.jpg 1406.jpg 734.jpg

656.txt,1019.jpg 780.jpg 385.jpg 1378.jpg 499.jpg 707.jpg 827.jpg 324.jpg 1964.jpg 578.jpg 1805.jpg 1058.jpg 1994.jpg 278.jpg 706.jpg 1007.jpg 1422.jpg 1294.jpg 1586.jpg 1356.jpg

657.txt,1039.jpg 553.jpg 1134.jpg 885.jpg 169.jpg 515.jpg 331.jpg 1029.jpg 1806.jpg 1807.jpg 1196.jpg 538.jpg 815.jpg 296.jpg 571.jpg 1143.jpg 238.jpg 1408.jpg 1989.jpg 968.jpg

658.txt,1804.jpg 902.jpg 1263.jpg 939.jpg 1105.jpg 936.jpg 336.jpg 88.jpg 995.jpg 978.jpg 434.jpg 1028.jpg 1050.jpg 4

700.txt,729.jpg 466.jpg 1409.jpg 653.jpg 152.jpg 1135.jpg 776.jpg 435.jpg 1280.jpg 1420.jpg 453.jpg 1481.jpg 421.jpg 1698.jpg 1679.jpg 1204.jpg 1535.jpg 1131.jpg 586.jpg 1137.jpg

701.txt,1869.jpg 856.jpg 1546.jpg 123.jpg 1079.jpg 1537.jpg 1563.jpg 1963.jpg 831.jpg 1229.jpg 1246.jpg 1194.jpg 503.jpg 974.jpg 443.jpg 1519.jpg 1908.jpg 694.jpg 442.jpg 1652.jpg

702.txt,898.jpg 427.jpg 285.jpg 1394.jpg 243.jpg 1.jpg 698.jpg 447.jpg 304.jpg 1073.jpg 1140.jpg 1760.jpg 124.jpg 720.jpg 288.jpg 1852.jpg 1836.jpg 1420.jpg 1171.jpg 1834.jpg

703.txt,247.jpg 1141.jpg 1999.jpg 80.jpg 1102.jpg 1177.jpg 1917.jpg 668.jpg 1507.jpg 6.jpg 482.jpg 738.jpg 1615.jpg 107.jpg 1820.jpg 1184.jpg 818.jpg 314.jpg 1143.jpg 149.jpg

704.txt,743.jpg 1128.jpg 824.jpg 884.jpg 207.jpg 1301.jpg 750.jpg 1595.jpg 1358.jpg 573.jpg 716.jpg 122.jpg 212.jpg 715.jpg 145.jpg 1357.jpg 1552.jpg 275.jpg 1189.jpg 1063.jpg

705.txt,814.jpg 51.jpg 771.jpg 1335.jpg 887.jpg 492.jpg 1693.jpg 274.jpg 703.jpg 330.jpg 1943.jpg 630.jpg 846.

747.txt,654.jpg 1035.jpg 799.jpg 397.jpg 1513.jpg 512.jpg 66.jpg 1231.jpg 686.jpg 1865.jpg 256.jpg 75.jpg 390.jpg 800.jpg 1816.jpg 1514.jpg 1486.jpg 930.jpg 498.jpg 514.jpg

748.txt,480.jpg 331.jpg 1134.jpg 179.jpg 726.jpg 428.jpg 154.jpg 1989.jpg 1029.jpg 553.jpg 587.jpg 160.jpg 296.jpg 1807.jpg 1017.jpg 1120.jpg 682.jpg 238.jpg 1981.jpg 850.jpg

749.txt,1383.jpg 981.jpg 445.jpg 765.jpg 1033.jpg 663.jpg 953.jpg 55.jpg 1330.jpg 1713.jpg 843.jpg 192.jpg 1720.jpg 669.jpg 117.jpg 426.jpg 159.jpg 1365.jpg 1573.jpg 545.jpg

750.txt,1310.jpg 1468.jpg 1093.jpg 1634.jpg 752.jpg 652.jpg 1712.jpg 1368.jpg 1887.jpg 701.jpg 460.jpg 1326.jpg 585.jpg 1427.jpg 48.jpg 376.jpg 704.jpg 1391.jpg 1719.jpg 96.jpg

751.txt,1340.jpg 649.jpg 1421.jpg 1208.jpg 1030.jpg 1059.jpg 1475.jpg 607.jpg 184.jpg 763.jpg 1437.jpg 1574.jpg 860.jpg 1366.jpg 1084.jpg 1665.jpg 1702.jpg 1027.jpg 1471.jpg 1840.jpg

752.txt,104.jpg 1671.jpg 58.jpg 1564.jpg 1407.jpg 782.jpg 1986.jpg 614.jpg 1026.jpg 1231.jpg 1163.jpg 1276.jpg 65

794.txt,856.jpg 123.jpg 831.jpg 1869.jpg 1546.jpg 503.jpg 974.jpg 442.jpg 1963.jpg 461.jpg 791.jpg 1519.jpg 610.jpg 401.jpg 847.jpg 193.jpg 1751.jpg 125.jpg 100.jpg 1142.jpg

795.txt,1267.jpg 830.jpg 1683.jpg 1825.jpg 1417.jpg 1861.jpg 147.jpg 1341.jpg 1576.jpg 189.jpg 1585.jpg 984.jpg 1784.jpg 1374.jpg 109.jpg 966.jpg 1631.jpg 640.jpg 757.jpg 1814.jpg

796.txt,146.jpg 954.jpg 1157.jpg 1502.jpg 1827.jpg 1860.jpg 1329.jpg 1589.jpg 1763.jpg 686.jpg 792.jpg 1932.jpg 624.jpg 1220.jpg 1167.jpg 836.jpg 799.jpg 1260.jpg 654.jpg 335.jpg

797.txt,314.jpg 6.jpg 1141.jpg 80.jpg 107.jpg 1999.jpg 818.jpg 482.jpg 1102.jpg 1114.jpg 1313.jpg 198.jpg 1507.jpg 968.jpg 527.jpg 457.jpg 1143.jpg 738.jpg 247.jpg 1184.jpg

798.txt,1420.jpg 353.jpg 1105.jpg 93.jpg 594.jpg 1131.jpg 721.jpg 742.jpg 1521.jpg 255.jpg 502.jpg 1047.jpg 292.jpg 359.jpg 375.jpg 1343.jpg 281.jpg 1980.jpg 1698.jpg 942.jpg

799.txt,1488.jpg 1270.jpg 685.jpg 1249.jpg 1239.jpg 481.jpg 1961.jpg 1694.jpg 1328.jpg 689.jpg 1857.jpg 1900.jpg 7

841.txt,499.jpg 1805.jpg 1019.jpg 1378.jpg 385.jpg 706.jpg 780.jpg 1586.jpg 952.jpg 324.jpg 707.jpg 827.jpg 578.jpg 1356.jpg 1994.jpg 1854.jpg 491.jpg 1964.jpg 1422.jpg 1058.jpg

842.txt,499.jpg 780.jpg 706.jpg 324.jpg 1019.jpg 1058.jpg 1964.jpg 827.jpg 578.jpg 385.jpg 1805.jpg 1378.jpg 707.jpg 1294.jpg 733.jpg 1148.jpg 491.jpg 1356.jpg 1422.jpg 129.jpg

843.txt,435.jpg 948.jpg 562.jpg 742.jpg 601.jpg 152.jpg 12.jpg 1679.jpg 942.jpg 1603.jpg 348.jpg 1597.jpg 1219.jpg 1174.jpg 1411.jpg 687.jpg 647.jpg 484.jpg 150.jpg 265.jpg

844.txt,292.jpg 375.jpg 359.jpg 1033.jpg 939.jpg 669.jpg 678.jpg 1218.jpg 1105.jpg 336.jpg 231.jpg 1480.jpg 1883.jpg 637.jpg 1924.jpg 902.jpg 1888.jpg 561.jpg 445.jpg 322.jpg

845.txt,71.jpg 1461.jpg 223.jpg 1149.jpg 1000.jpg 1921.jpg 165.jpg 1617.jpg 340.jpg 1379.jpg 26.jpg 1928.jpg 1051.jpg 1176.jpg 1648.jpg 963.jpg 1126.jpg 1453.jpg 467.jpg 1361.jpg

846.txt,921.jpg 210.jpg 964.jpg 498.jpg 1213.jpg 70.jpg 620.jpg 744.jpg 1434.jpg 734.jpg 69.jpg 138.jpg 914.jpg 5

888.txt,241.jpg 327.jpg 1604.jpg 1829.jpg 195.jpg 1467.jpg 1104.jpg 551.jpg 1947.jpg 1766.jpg 1946.jpg 277.jpg 283.jpg 477.jpg 1747.jpg 472.jpg 710.jpg 558.jpg 1583.jpg 1244.jpg

889.txt,1832.jpg 932.jpg 560.jpg 10.jpg 183.jpg 1534.jpg 1190.jpg 1703.jpg 1711.jpg 384.jpg 1290.jpg 1078.jpg 1848.jpg 1302.jpg 1056.jpg 886.jpg 1469.jpg 415.jpg 1772.jpg 1362.jpg

890.txt,666.jpg 1065.jpg 253.jpg 1988.jpg 326.jpg 109.jpg 1642.jpg 1962.jpg 1704.jpg 1341.jpg 189.jpg 934.jpg 1344.jpg 1138.jpg 609.jpg 500.jpg 1931.jpg 1814.jpg 147.jpg 1391.jpg

891.txt,374.jpg 1415.jpg 750.jpg 1778.jpg 26.jpg 1215.jpg 960.jpg 207.jpg 817.jpg 1126.jpg 471.jpg 824.jpg 1765.jpg 1070.jpg 1097.jpg 1318.jpg 884.jpg 1831.jpg 506.jpg 1189.jpg

892.txt,1593.jpg 672.jpg 18.jpg 1975.jpg 1986.jpg 1280.jpg 1136.jpg 1324.jpg 1299.jpg 722.jpg 1743.jpg 383.jpg 4.jpg 595.jpg 1718.jpg 1188.jpg 181.jpg 1238.jpg 517.jpg 1951.jpg

893.txt,366.jpg 816.jpg 365.jpg 1055.jpg 1639.jpg 1742.jpg 119.jpg 533.jpg 1916.jpg 11.jpg 1172.jpg 178.

935.txt,1106.jpg 1099.jpg 948.jpg 1753.jpg 1852.jpg 562.jpg 1129.jpg 1171.jpg 1200.jpg 1280.jpg 1497.jpg 1489.jpg 1342.jpg 653.jpg 926.jpg 1827.jpg 976.jpg 150.jpg 57.jpg 687.jpg

936.txt,1167.jpg 1827.jpg 1728.jpg 1106.jpg 307.jpg 1342.jpg 405.jpg 1582.jpg 295.jpg 1137.jpg 612.jpg 926.jpg 1280.jpg 146.jpg 1096.jpg 1204.jpg 287.jpg 468.jpg 910.jpg 1758.jpg

937.txt,1116.jpg 835.jpg 1807.jpg 738.jpg 508.jpg 818.jpg 1143.jpg 1689.jpg 482.jpg 1835.jpg 23.jpg 331.jpg 920.jpg 463.jpg 527.jpg 538.jpg 1959.jpg 1714.jpg 968.jpg 1173.jpg

938.txt,1536.jpg 1176.jpg 234.jpg 418.jpg 1368.jpg 1270.jpg 339.jpg 1463.jpg 1149.jpg 785.jpg 686.jpg 886.jpg 685.jpg 136.jpg 59.jpg 54.jpg 1961.jpg 1900.jpg 1081.jpg 1051.jpg

939.txt,1363.jpg 1123.jpg 54.jpg 1022.jpg 1290.jpg 886.jpg 1711.jpg 1703.jpg 1210.jpg 1708.jpg 1832.jpg 1534.jpg 1775.jpg 560.jpg 1056.jpg 1190.jpg 1362.jpg 1875.jpg 183.jpg 1616.jpg

940.txt,439.jpg 1621.jpg 777.jpg 194.jpg 128.jpg 1012.jpg 544.jpg 1364.jpg 708.jpg 1441.jpg 1984.jpg 64

982.txt,806.jpg 34.jpg 793.jpg 1072.jpg 9.jpg 810.jpg 313.jpg 621.jpg 1699.jpg 1951.jpg 861.jpg 874.jpg 1741.jpg 754.jpg 917.jpg 206.jpg 1113.jpg 1636.jpg 483.jpg 713.jpg

983.txt,1740.jpg 5.jpg 1173.jpg 1723.jpg 200.jpg 818.jpg 1226.jpg 1049.jpg 201.jpg 61.jpg 515.jpg 508.jpg 1116.jpg 835.jpg 1835.jpg 1689.jpg 1199.jpg 682.jpg 1006.jpg 1785.jpg

984.txt,886.jpg 54.jpg 1703.jpg 1056.jpg 1775.jpg 1363.jpg 1534.jpg 1362.jpg 1832.jpg 1448.jpg 1022.jpg 1210.jpg 1290.jpg 1469.jpg 591.jpg 1123.jpg 560.jpg 1711.jpg 1078.jpg 1616.jpg

985.txt,722.jpg 896.jpg 1240.jpg 18.jpg 919.jpg 612.jpg 4.jpg 1951.jpg 988.jpg 9.jpg 1324.jpg 713.jpg 622.jpg 1670.jpg 746.jpg 548.jpg 672.jpg 1103.jpg 1160.jpg 1188.jpg

986.txt,320.jpg 1953.jpg 779.jpg 1125.jpg 1450.jpg 59.jpg 1463.jpg 432.jpg 944.jpg 452.jpg 1279.jpg 677.jpg 764.jpg 1819.jpg 239.jpg 479.jpg 661.jpg 1530.jpg 1002.jpg 650.jpg

987.txt,248.jpg 277.jpg 775.jpg 1829.jpg 1104.jpg 1283.jpg 327.jpg 166.jpg 241.jpg 1604.jpg 1390.jpg 1467.jpg 551.jpg 19

1028.txt,1310.jpg 1468.jpg 1093.jpg 1712.jpg 1634.jpg 652.jpg 752.jpg 460.jpg 1368.jpg 585.jpg 1326.jpg 1887.jpg 701.jpg 376.jpg 1427.jpg 48.jpg 1485.jpg 704.jpg 1719.jpg 1530.jpg

1029.txt,1821.jpg 256.jpg 243.jpg 1350.jpg 1329.jpg 639.jpg 1900.jpg 1165.jpg 1948.jpg 136.jpg 1804.jpg 1882.jpg 162.jpg 1817.jpg 772.jpg 693.jpg 1124.jpg 325.jpg 1214.jpg 216.jpg

1030.txt,633.jpg 1950.jpg 192.jpg 1960.jpg 568.jpg 1330.jpg 1622.jpg 739.jpg 1547.jpg 1538.jpg 371.jpg 394.jpg 224.jpg 103.jpg 981.jpg 1864.jpg 828.jpg 662.jpg 110.jpg 223.jpg

1031.txt,1133.jpg 1149.jpg 223.jpg 1902.jpg 1505.jpg 1176.jpg 234.jpg 496.jpg 1536.jpg 45.jpg 785.jpg 340.jpg 19.jpg 1253.jpg 1461.jpg 1051.jpg 1928.jpg 1600.jpg 17.jpg 174.jpg

1032.txt,373.jpg 688.jpg 1623.jpg 1441.jpg 1676.jpg 1082.jpg 289.jpg 1127.jpg 1012.jpg 194.jpg 37.jpg 151.jpg 269.jpg 1364.jpg 1970.jpg 637.jpg 1203.jpg 1535.jpg 1416.jpg 268.jpg

1033.txt,1368.jpg 1176.jpg 174.jpg 223.jpg 1536.jpg 810.jpg 1149.jpg 340.jpg 1634.jpg 1133.jpg 1928.jpg

1074.txt,442.jpg 974.jpg 856.jpg 461.jpg 123.jpg 1546.jpg 401.jpg 831.jpg 503.jpg 1519.jpg 1751.jpg 610.jpg 125.jpg 1588.jpg 1399.jpg 1034.jpg 847.jpg 100.jpg 1963.jpg 791.jpg

1075.txt,1538.jpg 111.jpg 1431.jpg 1783.jpg 875.jpg 1931.jpg 1950.jpg 394.jpg 1326.jpg 1391.jpg 1619.jpg 768.jpg 821.jpg 1641.jpg 934.jpg 1073.jpg 1556.jpg 1598.jpg 652.jpg 1367.jpg

1076.txt,281.jpg 801.jpg 388.jpg 381.jpg 1343.jpg 1697.jpg 311.jpg 874.jpg 1391.jpg 1861.jpg 1372.jpg 946.jpg 67.jpg 875.jpg 1017.jpg 1699.jpg 215.jpg 1948.jpg 425.jpg 130.jpg

1077.txt,203.jpg 413.jpg 1552.jpg 374.jpg 747.jpg 1620.jpg 1696.jpg 1189.jpg 207.jpg 275.jpg 1879.jpg 1637.jpg 770.jpg 716.jpg 1831.jpg 1765.jpg 1301.jpg 1152.jpg 933.jpg 750.jpg

1078.txt,1696.jpg 46.jpg 1888.jpg 846.jpg 1568.jpg 1830.jpg 760.jpg 370.jpg 1913.jpg 1098.jpg 1127.jpg 137.jpg 82.jpg 389.jpg 105.jpg 354.jpg 1118.jpg 614.jpg 309.jpg 274.jpg

1079.txt,568.jpg 633.jpg 290.jpg 192.jpg 1057.jpg 1962.jpg 1330.jpg 1960.jpg 739.jpg 1919.jpg 828.jpg 1348.

1120.txt,104.jpg 1407.jpg 1671.jpg 782.jpg 1163.jpg 1026.jpg 1564.jpg 1795.jpg 816.jpg 657.jpg 702.jpg 58.jpg 1231.jpg 199.jpg 142.jpg 961.jpg 870.jpg 1531.jpg 889.jpg 424.jpg

1121.txt,835.jpg 1116.jpg 818.jpg 920.jpg 1173.jpg 508.jpg 1325.jpg 1689.jpg 5.jpg 1835.jpg 1723.jpg 1740.jpg 1006.jpg 1794.jpg 682.jpg 23.jpg 200.jpg 515.jpg 1313.jpg 1199.jpg

1122.txt,1118.jpg 1693.jpg 1888.jpg 46.jpg 20.jpg 814.jpg 1533.jpg 492.jpg 137.jpg 1218.jpg 1696.jpg 846.jpg 1830.jpg 1913.jpg 1426.jpg 1895.jpg 82.jpg 1335.jpg 321.jpg 1761.jpg

1123.txt,414.jpg 1151.jpg 217.jpg 1289.jpg 489.jpg 1265.jpg 156.jpg 402.jpg 996.jpg 910.jpg 897.jpg 1020.jpg 555.jpg 648.jpg 718.jpg 458.jpg 1096.jpg 1377.jpg 1584.jpg 1885.jpg

1124.txt,1378.jpg 385.jpg 1586.jpg 1349.jpg 499.jpg 1545.jpg 1169.jpg 1019.jpg 1805.jpg 1422.jpg 291.jpg 454.jpg 578.jpg 278.jpg 780.jpg 1964.jpg 952.jpg 324.jpg 707.jpg 1356.jpg

1125.txt,1420.jpg 594.jpg 246.jpg 1250.jpg 93.jpg 1521.jpg 202.jpg 599.jpg 678.jpg 50.jpg 502.jpg 1286.jpg 3

1166.txt,1038.jpg 1685.jpg 1640.jpg 1900.jpg 418.jpg 1961.jpg 1329.jpg 54.jpg 685.jpg 1249.jpg 1488.jpg 1744.jpg 686.jpg 1150.jpg 1157.jpg 689.jpg 1859.jpg 1438.jpg 481.jpg 1363.jpg

1167.txt,798.jpg 1319.jpg 624.jpg 143.jpg 1157.jpg 954.jpg 1841.jpg 1095.jpg 410.jpg 1763.jpg 1860.jpg 1251.jpg 1491.jpg 1449.jpg 1329.jpg 857.jpg 91.jpg 146.jpg 807.jpg 1686.jpg

1168.txt,1621.jpg 1364.jpg 1813.jpg 708.jpg 853.jpg 128.jpg 269.jpg 64.jpg 544.jpg 1012.jpg 1984.jpg 1235.jpg 688.jpg 439.jpg 1473.jpg 777.jpg 194.jpg 1970.jpg 1623.jpg 1297.jpg

1169.txt,888.jpg 682.jpg 1029.jpg 587.jpg 1006.jpg 1828.jpg 1809.jpg 529.jpg 1737.jpg 1353.jpg 411.jpg 144.jpg 1615.jpg 538.jpg 1891.jpg 1914.jpg 225.jpg 1134.jpg 1871.jpg 571.jpg

1170.txt,32.jpg 287.jpg 295.jpg 1846.jpg 407.jpg 1137.jpg 270.jpg 1728.jpg 307.jpg 745.jpg 1877.jpg 416.jpg 1921.jpg 1798.jpg 1106.jpg 612.jpg 308.jpg 405.jpg 1260.jpg 1167.jpg

1171.txt,152.jpg 12.jpg 7.jpg 1481.jpg 1110.jpg 1076.jpg 1937.jpg 1679.jpg 1726.jpg 776.jpg 1117.jp

1212.txt,614.jpg 1913.jpg 554.jpg 370.jpg 570.jpg 20.jpg 339.jpg 1581.jpg 1830.jpg 1818.jpg 1700.jpg 361.jpg 1968.jpg 1424.jpg 309.jpg 1536.jpg 1886.jpg 1691.jpg 1335.jpg 814.jpg

1213.txt,1909.jpg 1906.jpg 1752.jpg 303.jpg 437.jpg 1405.jpg 993.jpg 662.jpg 1464.jpg 1998.jpg 456.jpg 675.jpg 272.jpg 625.jpg 790.jpg 1493.jpg 1225.jpg 660.jpg 928.jpg 980.jpg

1214.txt,1567.jpg 549.jpg 410.jpg 1795.jpg 47.jpg 1133.jpg 1261.jpg 70.jpg 1253.jpg 870.jpg 1179.jpg 514.jpg 89.jpg 1622.jpg 617.jpg 1004.jpg 498.jpg 1918.jpg 1791.jpg 627.jpg

1215.txt,484.jpg 1076.jpg 1135.jpg 1816.jpg 1535.jpg 1105.jpg 1231.jpg 942.jpg 1131.jpg 292.jpg 594.jpg 256.jpg 1203.jpg 413.jpg 1620.jpg 736.jpg 1395.jpg 1481.jpg 1606.jpg 978.jpg

1216.txt,780.jpg 1545.jpg 1169.jpg 759.jpg 952.jpg 1058.jpg 454.jpg 1019.jpg 1964.jpg 491.jpg 499.jpg 324.jpg 733.jpg 827.jpg 578.jpg 795.jpg 1994.jpg 385.jpg 854.jpg 1378.jpg

1217.txt,719.jpg 1622.jpg 1346.jpg 245.jpg 419.jpg 1918.jpg 1847.jpg 103.jpg 1261.jpg 1948.jpg 1031.jpg 26

1258.txt,1367.jpg 1478.jpg 1684.jpg 1241.jpg 1854.jpg 1083.jpg 1245.jpg 741.jpg 1490.jpg 628.jpg 99.jpg 665.jpg 1496.jpg 1667.jpg 556.jpg 1792.jpg 129.jpg 952.jpg 681.jpg 827.jpg

1259.txt,1365.jpg 1901.jpg 1336.jpg 1525.jpg 1690.jpg 844.jpg 1010.jpg 266.jpg 1013.jpg 982.jpg 1611.jpg 866.jpg 848.jpg 1706.jpg 1644.jpg 420.jpg 343.jpg 579.jpg 979.jpg 1896.jpg

1260.txt,889.jpg 1293.jpg 1939.jpg 490.jpg 1531.jpg 855.jpg 1419.jpg 1332.jpg 961.jpg 1687.jpg 596.jpg 876.jpg 533.jpg 520.jpg 1649.jpg 1303.jpg 424.jpg 11.jpg 293.jpg 1026.jpg

1261.txt,1684.jpg 1245.jpg 1626.jpg 1478.jpg 1780.jpg 935.jpg 1268.jpg 396.jpg 681.jpg 1083.jpg 301.jpg 806.jpg 129.jpg 1777.jpg 232.jpg 1007.jpg 1090.jpg 665.jpg 1914.jpg 1792.jpg

1262.txt,20.jpg 1696.jpg 51.jpg 46.jpg 1913.jpg 1118.jpg 1888.jpg 846.jpg 389.jpg 1335.jpg 526.jpg 1426.jpg 138.jpg 814.jpg 1886.jpg 82.jpg 940.jpg 1830.jpg 1761.jpg 1400.jpg

1263.txt,1961.jpg 1155.jpg 1249.jpg 1488.jpg 168.jpg 689.jpg 1285.jpg 1085.jpg 685.jpg 1328.jpg 1270.jp

1304.txt,414.jpg 1758.jpg 217.jpg 1096.jpg 1020.jpg 996.jpg 33.jpg 897.jpg 1289.jpg 910.jpg 1151.jpg 1655.jpg 1584.jpg 583.jpg 712.jpg 156.jpg 1458.jpg 489.jpg 718.jpg 1275.jpg

1305.txt,1804.jpg 939.jpg 1480.jpg 434.jpg 1388.jpg 1263.jpg 1165.jpg 88.jpg 375.jpg 1180.jpg 862.jpg 1166.jpg 936.jpg 995.jpg 973.jpg 639.jpg 1771.jpg 683.jpg 711.jpg 216.jpg

1306.txt,1528.jpg 1953.jpg 661.jpg 1450.jpg 677.jpg 320.jpg 779.jpg 1279.jpg 650.jpg 59.jpg 479.jpg 1125.jpg 239.jpg 1002.jpg 944.jpg 807.jpg 432.jpg 605.jpg 764.jpg 1819.jpg

1307.txt,1693.jpg 1118.jpg 1895.jpg 1761.jpg 1533.jpg 1296.jpg 703.jpg 526.jpg 1335.jpg 1426.jpg 814.jpg 492.jpg 1402.jpg 771.jpg 1830.jpg 82.jpg 1943.jpg 51.jpg 1355.jpg 321.jpg

1308.txt,885.jpg 1807.jpg 815.jpg 553.jpg 1134.jpg 1143.jpg 1039.jpg 331.jpg 515.jpg 169.jpg 286.jpg 508.jpg 1196.jpg 571.jpg 1806.jpg 1726.jpg 160.jpg 296.jpg 238.jpg 538.jpg

1309.txt,208.jpg 1864.jpg 1674.jpg 1833.jpg 1931.jpg 1618.jpg 310.jpg 1987.jpg 111.jpg 1556.jpg 1277.jpg 1538.jp

1350.txt,1683.jpg 1825.jpg 1685.jpg 830.jpg 1374.jpg 966.jpg 1640.jpg 1576.jpg 1585.jpg 1859.jpg 1728.jpg 1150.jpg 1579.jpg 1267.jpg 1744.jpg 1178.jpg 1417.jpg 1038.jpg 1323.jpg 164.jpg

1351.txt,434.jpg 939.jpg 936.jpg 995.jpg 637.jpg 336.jpg 375.jpg 902.jpg 973.jpg 862.jpg 1388.jpg 1804.jpg 978.jpg 25.jpg 1105.jpg 1180.jpg 88.jpg 1166.jpg 421.jpg 1028.jpg

1352.txt,339.jpg 1515.jpg 1581.jpg 338.jpg 1185.jpg 785.jpg 1600.jpg 523.jpg 656.jpg 1248.jpg 45.jpg 1231.jpg 1479.jpg 969.jpg 1463.jpg 361.jpg 1776.jpg 370.jpg 1971.jpg 309.jpg

1353.txt,396.jpg 1378.jpg 1007.jpg 291.jpg 324.jpg 707.jpg 1349.jpg 278.jpg 1805.jpg 1019.jpg 780.jpg 385.jpg 1994.jpg 491.jpg 1245.jpg 1422.jpg 499.jpg 1586.jpg 1256.jpg 1058.jpg

1354.txt,560.jpg 932.jpg 1832.jpg 886.jpg 183.jpg 1534.jpg 1290.jpg 1190.jpg 1703.jpg 1469.jpg 54.jpg 1210.jpg 1711.jpg 384.jpg 1223.jpg 1775.jpg 1448.jpg 1302.jpg 10.jpg 1056.jpg

1355.txt,156.jpg 555.jpg 910.jpg 897.jpg 259.jpg 655.jpg 1289.jpg 1151.jpg 217.jpg 489.jpg 1582.jp

1396.txt,1901.jpg 266.jpg 1346.jpg 1365.jpg 1690.jpg 1557.jpg 1389.jpg 837.jpg 1336.jpg 1644.jpg 1525.jpg 393.jpg 1031.jpg 1455.jpg 781.jpg 1847.jpg 1611.jpg 343.jpg 923.jpg 1948.jpg

1397.txt,1079.jpg 1869.jpg 819.jpg 1246.jpg 1652.jpg 1563.jpg 34.jpg 974.jpg 1548.jpg 123.jpg 1506.jpg 812.jpg 1537.jpg 692.jpg 125.jpg 100.jpg 1566.jpg 694.jpg 615.jpg 1229.jpg

1398.txt,1275.jpg 908.jpg 910.jpg 897.jpg 535.jpg 217.jpg 996.jpg 1096.jpg 1444.jpg 718.jpg 489.jpg 156.jpg 414.jpg 16.jpg 1758.jpg 1020.jpg 1458.jpg 1855.jpg 1701.jpg 259.jpg

1399.txt,143.jpg 624.jpg 1095.jpg 1491.jpg 1905.jpg 1841.jpg 954.jpg 410.jpg 1932.jpg 1686.jpg 1860.jpg 857.jpg 798.jpg 1449.jpg 1764.jpg 1763.jpg 1319.jpg 1890.jpg 1157.jpg 455.jpg

1400.txt,620.jpg 498.jpg 1746.jpg 734.jpg 70.jpg 921.jpg 914.jpg 52.jpg 1213.jpg 210.jpg 1434.jpg 964.jpg 534.jpg 744.jpg 346.jpg 1236.jpg 37.jpg 670.jpg 31.jpg 1926.jpg

1401.txt,1505.jpg 1461.jpg 545.jpg 1648.jpg 19.jpg 223.jpg 147.jpg 1149.jpg 134.jpg 1971.jpg 1791.jpg 1321

1442.txt,664.jpg 403.jpg 1544.jpg 1604.jpg 241.jpg 679.jpg 1766.jpg 1747.jpg 1104.jpg 1425.jpg 581.jpg 327.jpg 1946.jpg 472.jpg 1467.jpg 710.jpg 195.jpg 1829.jpg 1283.jpg 1583.jpg

1443.txt,374.jpg 750.jpg 817.jpg 1552.jpg 884.jpg 1189.jpg 207.jpg 1128.jpg 824.jpg 1301.jpg 1152.jpg 747.jpg 1778.jpg 190.jpg 716.jpg 1595.jpg 1288.jpg 1831.jpg 1801.jpg 145.jpg

1444.txt,315.jpg 1278.jpg 746.jpg 363.jpg 988.jpg 454.jpg 1951.jpg 713.jpg 1299.jpg 501.jpg 1169.jpg 658.jpg 759.jpg 1730.jpg 1257.jpg 470.jpg 35.jpg 1549.jpg 963.jpg 517.jpg

1445.txt,801.jpg 946.jpg 1337.jpg 1697.jpg 1989.jpg 1672.jpg 165.jpg 1017.jpg 1861.jpg 1590.jpg 1652.jpg 365.jpg 176.jpg 1942.jpg 1669.jpg 1908.jpg 381.jpg 613.jpg 424.jpg 1631.jpg

1446.txt,1937.jpg 121.jpg 12.jpg 729.jpg 653.jpg 1481.jpg 421.jpg 1106.jpg 152.jpg 1807.jpg 745.jpg 1342.jpg 859.jpg 1816.jpg 118.jpg 1430.jpg 973.jpg 1526.jpg 268.jpg 1535.jpg

1447.txt,90.jpg 1760.jpg 1708.jpg 1329.jpg 418.jpg 1702.jpg 1775.jpg 1931.jpg 1609.jpg 1827.jpg 111.jpg

1488.txt,664.jpg 1425.jpg 1544.jpg 1604.jpg 581.jpg 241.jpg 283.jpg 404.jpg 403.jpg 1946.jpg 1467.jpg 327.jpg 710.jpg 1104.jpg 1766.jpg 382.jpg 300.jpg 1747.jpg 679.jpg 195.jpg

1489.txt,55.jpg 1547.jpg 943.jpg 843.jpg 157.jpg 1720.jpg 192.jpg 1771.jpg 981.jpg 633.jpg 153.jpg 568.jpg 1553.jpg 691.jpg 1383.jpg 113.jpg 1330.jpg 224.jpg 1443.jpg 290.jpg

1490.txt,1821.jpg 1795.jpg 545.jpg 732.jpg 1817.jpg 699.jpg 1124.jpg 256.jpg 1423.jpg 1819.jpg 554.jpg 647.jpg 1553.jpg 1403.jpg 1862.jpg 1024.jpg 432.jpg 90.jpg 413.jpg 147.jpg

1491.txt,841.jpg 1222.jpg 717.jpg 1484.jpg 683.jpg 648.jpg 749.jpg 1500.jpg 1024.jpg 881.jpg 629.jpg 1382.jpg 1910.jpg 1965.jpg 1402.jpg 1816.jpg 1553.jpg 1277.jpg 999.jpg 943.jpg

1492.txt,845.jpg 933.jpg 716.jpg 1152.jpg 1831.jpg 1288.jpg 1189.jpg 1943.jpg 203.jpg 1879.jpg 145.jpg 1357.jpg 1552.jpg 1301.jpg 275.jpg 1637.jpg 715.jpg 1162.jpg 190.jpg 1128.jpg

1493.txt,1732.jpg 1722.jpg 1445.jpg 1602.jpg 684.jpg 1036.jpg 1870.jpg 1042.jpg 1633.jpg 536.jpg 1115.jp

1534.txt,544.jpg 708.jpg 1297.jpg 1970.jpg 1364.jpg 1813.jpg 194.jpg 64.jpg 269.jpg 439.jpg 1621.jpg 777.jpg 1952.jpg 1473.jpg 128.jpg 688.jpg 1012.jpg 440.jpg 268.jpg 1416.jpg

1535.txt,471.jpg 26.jpg 1070.jpg 1215.jpg 960.jpg 1097.jpg 1889.jpg 1145.jpg 1207.jpg 1727.jpg 374.jpg 817.jpg 750.jpg 731.jpg 825.jpg 207.jpg 1318.jpg 267.jpg 1801.jpg 1492.jpg

1536.txt,97.jpg 909.jpg 408.jpg 755.jpg 695.jpg 1060.jpg 641.jpg 254.jpg 229.jpg 1889.jpg 1651.jpg 1493.jpg 993.jpg 990.jpg 790.jpg 825.jpg 915.jpg 1320.jpg 731.jpg 980.jpg

1537.txt,1807.jpg 121.jpg 571.jpg 482.jpg 538.jpg 1408.jpg 668.jpg 644.jpg 738.jpg 1116.jpg 1177.jpg 1143.jpg 885.jpg 1733.jpg 818.jpg 331.jpg 1714.jpg 378.jpg 1601.jpg 1334.jpg

1538.txt,620.jpg 734.jpg 1746.jpg 914.jpg 921.jpg 498.jpg 70.jpg 744.jpg 1434.jpg 1213.jpg 964.jpg 534.jpg 346.jpg 52.jpg 1236.jpg 670.jpg 880.jpg 210.jpg 78.jpg 627.jpg

1539.txt,1150.jpg 53.jpg 1859.jpg 1764.jpg 986.jpg 1640.jpg 1685.jpg 1220.jpg 455.jpg 1491.jpg 1438.jpg 1841.jpg 1095.j

1581.txt,996.jpg 718.jpg 655.jpg 910.jpg 1275.jpg 489.jpg 1458.jpg 1151.jpg 897.jpg 908.jpg 259.jpg 16.jpg 156.jpg 1289.jpg 217.jpg 1465.jpg 555.jpg 535.jpg 33.jpg 977.jpg

1582.txt,1829.jpg 1947.jpg 558.jpg 195.jpg 1390.jpg 327.jpg 1244.jpg 551.jpg 241.jpg 1583.jpg 1747.jpg 277.jpg 1884.jpg 1104.jpg 1766.jpg 477.jpg 1467.jpg 283.jpg 1604.jpg 710.jpg

1583.txt,1827.jpg 1728.jpg 32.jpg 612.jpg 1260.jpg 270.jpg 295.jpg 1106.jpg 1167.jpg 1329.jpg 1200.jpg 307.jpg 1763.jpg 954.jpg 405.jpg 1304.jpg 1497.jpg 1762.jpg 1342.jpg 146.jpg

1584.txt,1137.jpg 1846.jpg 407.jpg 307.jpg 32.jpg 270.jpg 1167.jpg 295.jpg 1926.jpg 287.jpg 1342.jpg 369.jpg 1921.jpg 1746.jpg 1106.jpg 346.jpg 1415.jpg 1827.jpg 1877.jpg 1646.jpg

1585.txt,746.jpg 1578.jpg 470.jpg 988.jpg 35.jpg 713.jpg 1951.jpg 4.jpg 658.jpg 1299.jpg 1549.jpg 890.jpg 548.jpg 301.jpg 380.jpg 1257.jpg 919.jpg 1863.jpg 963.jpg 1159.jpg

1586.txt,1134.jpg 1017.jpg 296.jpg 331.jpg 1039.jpg 1807.jpg 1143.jpg 1196.jpg 169.jpg 211.jpg 815.jpg 885.jpg

1627.txt,596.jpg 83.jpg 855.jpg 1939.jpg 520.jpg 1055.jpg 1293.jpg 1419.jpg 889.jpg 490.jpg 11.jpg 1531.jpg 1332.jpg 533.jpg 1649.jpg 1638.jpg 27.jpg 424.jpg 876.jpg 1163.jpg

1628.txt,254.jpg 97.jpg 408.jpg 755.jpg 915.jpg 1493.jpg 1060.jpg 228.jpg 909.jpg 1225.jpg 790.jpg 43.jpg 229.jpg 980.jpg 993.jpg 990.jpg 695.jpg 1651.jpg 1661.jpg 1405.jpg

1629.txt,1517.jpg 94.jpg 78.jpg 1469.jpg 989.jpg 627.jpg 987.jpg 1220.jpg 1157.jpg 807.jpg 1890.jpg 1085.jpg 1841.jpg 1155.jpg 409.jpg 384.jpg 1932.jpg 1279.jpg 1150.jpg 1903.jpg

1630.txt,961.jpg 1531.jpg 855.jpg 889.jpg 1293.jpg 293.jpg 1939.jpg 1419.jpg 1332.jpg 424.jpg 490.jpg 876.jpg 11.jpg 1303.jpg 596.jpg 1687.jpg 520.jpg 1026.jpg 423.jpg 1649.jpg

1631.txt,1416.jpg 1350.jpg 1722.jpg 1445.jpg 1042.jpg 1721.jpg 565.jpg 1036.jpg 256.jpg 1732.jpg 536.jpg 1602.jpg 1568.jpg 1115.jpg 639.jpg 1633.jpg 1870.jpg 684.jpg 1406.jpg 1681.jpg

1632.txt,1351.jpg 76.jpg 348.jpg 1516.jpg 1726.jpg 877.jpg 1679.jpg 789.jpg 726.jpg 1395.jpg 495.jpg 587.jp

1673.txt,1288.jpg 750.jpg 824.jpg 1831.jpg 1189.jpg 1801.jpg 933.jpg 1595.jpg 716.jpg 884.jpg 1301.jpg 715.jpg 1128.jpg 1152.jpg 1357.jpg 207.jpg 1552.jpg 1345.jpg 1063.jpg 212.jpg

1674.txt,1722.jpg 1406.jpg 1036.jpg 1870.jpg 1520.jpg 684.jpg 1602.jpg 536.jpg 1732.jpg 1074.jpg 1518.jpg 1681.jpg 1445.jpg 1633.jpg 1062.jpg 1721.jpg 1206.jpg 74.jpg 1115.jpg 1972.jpg

1675.txt,1728.jpg 386.jpg 466.jpg 1260.jpg 672.jpg 532.jpg 295.jpg 612.jpg 787.jpg 1827.jpg 1579.jpg 405.jpg 1106.jpg 1846.jpg 1670.jpg 926.jpg 18.jpg 308.jpg 1304.jpg 1167.jpg

1676.txt,696.jpg 1512.jpg 159.jpg 372.jpg 1471.jpg 426.jpg 1720.jpg 883.jpg 322.jpg 1499.jpg 838.jpg 1500.jpg 1107.jpg 175.jpg 1218.jpg 1533.jpg 781.jpg 1389.jpg 1611.jpg 1644.jpg

1677.txt,1732.jpg 1722.jpg 1445.jpg 536.jpg 1036.jpg 1602.jpg 1406.jpg 1870.jpg 1681.jpg 1074.jpg 1520.jpg 1721.jpg 1042.jpg 684.jpg 1633.jpg 584.jpg 1062.jpg 1518.jpg 1972.jpg 534.jpg

1678.txt,439.jpg 1307.jpg 708.jpg 1297.jpg 544.jpg 1473.jpg 1952.jpg 1623.jpg 1235.jpg 

1719.txt,1261.jpg 913.jpg 719.jpg 1031.jpg 1397.jpg 1443.jpg 531.jpg 1948.jpg 1918.jpg 419.jpg 1622.jpg 1557.jpg 826.jpg 113.jpg 727.jpg 837.jpg 1346.jpg 1024.jpg 857.jpg 245.jpg

1720.txt,485.jpg 615.jpg 1566.jpg 383.jpg 1718.jpg 1276.jpg 58.jpg 1652.jpg 1983.jpg 233.jpg 1100.jpg 639.jpg 1986.jpg 575.jpg 1498.jpg 162.jpg 1537.jpg 808.jpg 595.jpg 922.jpg

1721.txt,215.jpg 1194.jpg 182.jpg 1477.jpg 144.jpg 1699.jpg 357.jpg 1741.jpg 741.jpg 874.jpg 1697.jpg 788.jpg 378.jpg 801.jpg 187.jpg 1707.jpg 1907.jpg 281.jpg 1081.jpg 179.jpg

1722.txt,562.jpg 435.jpg 473.jpg 1400.jpg 1204.jpg 138.jpg 1117.jpg 956.jpg 1050.jpg 948.jpg 1224.jpg 1417.jpg 1451.jpg 1529.jpg 912.jpg 601.jpg 1092.jpg 493.jpg 832.jpg 265.jpg

1723.txt,1020.jpg 1289.jpg 1265.jpg 1584.jpg 712.jpg 1151.jpg 33.jpg 414.jpg 1933.jpg 458.jpg 217.jpg 555.jpg 583.jpg 156.jpg 1333.jpg 1655.jpg 1758.jpg 996.jpg 1465.jpg 1096.jpg

1724.txt,1391.jpg 264.jpg 1962.jpg 1004.jpg 111.jpg 1810.jpg 860.jpg 719.jpg 472.jpg 1604.jpg 480.jpg 120

1765.txt,1909.jpg 303.jpg 272.jpg 1752.jpg 1906.jpg 437.jpg 1405.jpg 1998.jpg 625.jpg 662.jpg 1464.jpg 993.jpg 456.jpg 675.jpg 1493.jpg 790.jpg 257.jpg 1225.jpg 928.jpg 1067.jpg

1766.txt,1286.jpg 202.jpg 226.jpg 93.jpg 246.jpg 1521.jpg 541.jpg 698.jpg 50.jpg 599.jpg 1047.jpg 92.jpg 1410.jpg 723.jpg 1250.jpg 353.jpg 1420.jpg 502.jpg 305.jpg 1980.jpg

1767.txt,1143.jpg 1807.jpg 885.jpg 286.jpg 1039.jpg 1408.jpg 331.jpg 14.jpg 644.jpg 1196.jpg 482.jpg 1550.jpg 121.jpg 538.jpg 160.jpg 571.jpg 169.jpg 835.jpg 1068.jpg 833.jpg

1768.txt,421.jpg 721.jpg 1135.jpg 1131.jpg 359.jpg 1535.jpg 375.jpg 1105.jpg 292.jpg 942.jpg 906.jpg 586.jpg 255.jpg 1924.jpg 604.jpg 1698.jpg 28.jpg 594.jpg 1782.jpg 1117.jpg

1769.txt,71.jpg 441.jpg 618.jpg 709.jpg 925.jpg 1453.jpg 573.jpg 26.jpg 1996.jpg 1418.jpg 1767.jpg 1632.jpg 1187.jpg 85.jpg 148.jpg 1492.jpg 1126.jpg 506.jpg 218.jpg 1620.jpg

1770.txt,1662.jpg 153.jpg 290.jpg 1547.jpg 981.jpg 1771.jpg 943.jpg 1024.jpg 691.jpg 633.jpg 1383.jpg 1553.jpg 157.jpg

1811.txt,776.jpg 46.jpg 526.jpg 1696.jpg 1510.jpg 1076.jpg 829.jpg 357.jpg 20.jpg 1729.jpg 1481.jpg 1888.jpg 1166.jpg 619.jpg 82.jpg 814.jpg 1535.jpg 1161.jpg 1110.jpg 1913.jpg

1812.txt,1528.jpg 1534.jpg 183.jpg 560.jpg 1832.jpg 1223.jpg 415.jpg 1703.jpg 1363.jpg 384.jpg 1290.jpg 932.jpg 1190.jpg 1362.jpg 1432.jpg 91.jpg 1461.jpg 10.jpg 54.jpg 1022.jpg

1813.txt,16.jpg 1701.jpg 1944.jpg 582.jpg 262.jpg 1444.jpg 718.jpg 1458.jpg 897.jpg 1352.jpg 1151.jpg 1790.jpg 489.jpg 655.jpg 1540.jpg 1472.jpg 156.jpg 1275.jpg 1933.jpg 391.jpg

1814.txt,1403.jpg 1632.jpg 709.jpg 743.jpg 618.jpg 148.jpg 1767.jpg 573.jpg 71.jpg 1418.jpg 1511.jpg 1514.jpg 474.jpg 1571.jpg 925.jpg 986.jpg 1930.jpg 234.jpg 161.jpg 1248.jpg

1815.txt,320.jpg 1819.jpg 1450.jpg 779.jpg 1953.jpg 432.jpg 59.jpg 1795.jpg 661.jpg 677.jpg 1125.jpg 1279.jpg 944.jpg 452.jpg 549.jpg 650.jpg 764.jpg 1821.jpg 479.jpg 1463.jpg

1816.txt,1190.jpg 1290.jpg 1711.jpg 183.jpg 560.jpg 1832.jpg 1534.jpg 1123.jpg 932.jpg 54.jpg 91.jpg 1022.jp

1857.txt,874.jpg 65.jpg 1081.jpg 751.jpg 801.jpg 1861.jpg 1091.jpg 875.jpg 1784.jpg 1590.jpg 1675.jpg 1741.jpg 1372.jpg 1697.jpg 187.jpg 1051.jpg 1709.jpg 205.jpg 1619.jpg 851.jpg

1858.txt,278.jpg 1007.jpg 578.jpg 1478.jpg 396.jpg 1019.jpg 1349.jpg 385.jpg 1805.jpg 1554.jpg 1545.jpg 1490.jpg 1378.jpg 952.jpg 438.jpg 707.jpg 556.jpg 1994.jpg 671.jpg 827.jpg

1859.txt,241.jpg 1604.jpg 327.jpg 1747.jpg 1467.jpg 1946.jpg 195.jpg 1104.jpg 551.jpg 1829.jpg 277.jpg 710.jpg 1947.jpg 1390.jpg 664.jpg 404.jpg 283.jpg 477.jpg 581.jpg 1766.jpg

1860.txt,1552.jpg 203.jpg 1189.jpg 1637.jpg 413.jpg 933.jpg 716.jpg 275.jpg 1152.jpg 190.jpg 1879.jpg 1568.jpg 747.jpg 1301.jpg 1696.jpg 817.jpg 243.jpg 1423.jpg 1126.jpg 1831.jpg

1861.txt,1829.jpg 558.jpg 327.jpg 241.jpg 195.jpg 1947.jpg 277.jpg 1390.jpg 1244.jpg 1104.jpg 1747.jpg 551.jpg 1604.jpg 1467.jpg 1583.jpg 472.jpg 1766.jpg 248.jpg 1884.jpg 283.jpg

1862.txt,84.jpg 793.jpg 1626.jpg 935.jpg 1452.jpg 1309.jpg 1684.jpg 1268.jpg 762.jpg 387.jpg 232.j

1903.txt,1488.jpg 689.jpg 1961.jpg 1694.jpg 1249.jpg 1285.jpg 448.jpg 1085.jpg 168.jpg 1270.jpg 1155.jpg 987.jpg 1328.jpg 685.jpg 1239.jpg 481.jpg 1900.jpg 409.jpg 1857.jpg 794.jpg

1904.txt,833.jpg 1156.jpg 1753.jpg 1417.jpg 562.jpg 1529.jpg 948.jpg 589.jpg 758.jpg 1757.jpg 1907.jpg 1071.jpg 1489.jpg 875.jpg 1337.jpg 1372.jpg 1861.jpg 809.jpg 1590.jpg 435.jpg

1905.txt,1684.jpg 1268.jpg 1090.jpg 1072.jpg 1626.jpg 232.jpg 793.jpg 1245.jpg 806.jpg 102.jpg 84.jpg 209.jpg 1113.jpg 1658.jpg 1314.jpg 935.jpg 524.jpg 911.jpg 917.jpg 861.jpg

1906.txt,639.jpg 1948.jpg 1918.jpg 243.jpg 1568.jpg 719.jpg 1622.jpg 162.jpg 256.jpg 1817.jpg 1804.jpg 772.jpg 103.jpg 1.jpg 1350.jpg 1057.jpg 1261.jpg 1329.jpg 464.jpg 727.jpg

1907.txt,192.jpg 1547.jpg 843.jpg 633.jpg 1330.jpg 568.jpg 981.jpg 691.jpg 1553.jpg 55.jpg 943.jpg 1720.jpg 157.jpg 153.jpg 1960.jpg 1443.jpg 1024.jpg 676.jpg 224.jpg 1383.jpg

1908.txt,1286.jpg 599.jpg 246.jpg 50.jpg 93.jpg 1047.jpg 723.jpg 1410.jpg 678.jpg 305.jpg 202.jpg 226.j

1949.txt,1829.jpg 1390.jpg 277.jpg 551.jpg 248.jpg 327.jpg 1947.jpg 241.jpg 195.jpg 1104.jpg 1747.jpg 1583.jpg 1884.jpg 558.jpg 1467.jpg 1766.jpg 1244.jpg 1604.jpg 283.jpg 710.jpg

1950.txt,1346.jpg 1557.jpg 837.jpg 245.jpg 719.jpg 923.jpg 1397.jpg 1031.jpg 1543.jpg 1901.jpg 1847.jpg 1622.jpg 103.jpg 1389.jpg 1950.jpg 826.jpg 266.jpg 1948.jpg 1336.jpg 113.jpg

1951.txt,1621.jpg 128.jpg 1235.jpg 1012.jpg 64.jpg 1364.jpg 1813.jpg 853.jpg 269.jpg 708.jpg 688.jpg 439.jpg 194.jpg 544.jpg 1473.jpg 1376.jpg 777.jpg 214.jpg 1623.jpg 929.jpg

1952.txt,67.jpg 590.jpg 1810.jpg 1814.jpg 1688.jpg 1754.jpg 247.jpg 668.jpg 1391.jpg 701.jpg 1807.jpg 185.jpg 1326.jpg 149.jpg 1049.jpg 1039.jpg 874.jpg 6.jpg 169.jpg 470.jpg

1953.txt,544.jpg 708.jpg 1621.jpg 269.jpg 1813.jpg 1364.jpg 1012.jpg 439.jpg 128.jpg 1970.jpg 64.jpg 777.jpg 194.jpg 853.jpg 1984.jpg 1473.jpg 1297.jpg 1235.jpg 688.jpg 1623.jpg

1954.txt,1937.jpg 859.jpg 118.jpg 12.jpg 1481.jpg 1280.jpg 595.jpg 1743.jpg 729.jpg 1679.jpg 1342.jpg 653

1995.txt,1033.jpg 445.jpg 607.jpg 1724.jpg 1713.jpg 1840.jpg 1866.jpg 159.jpg 934.jpg 42.jpg 953.jpg 634.jpg 838.jpg 1962.jpg 511.jpg 1702.jpg 184.jpg 323.jpg 883.jpg 866.jpg

1996.txt,748.jpg 1853.jpg 1164.jpg 180.jpg 319.jpg 398.jpg 860.jpg 1027.jpg 399.jpg 1508.jpg 938.jpg 680.jpg 1605.jpg 1739.jpg 1211.jpg 1008.jpg 184.jpg 1460.jpg 1392.jpg 1962.jpg

1997.txt,104.jpg 657.jpg 1026.jpg 293.jpg 1163.jpg 58.jpg 1638.jpg 961.jpg 1266.jpg 782.jpg 1564.jpg 1407.jpg 342.jpg 1555.jpg 1061.jpg 816.jpg 1271.jpg 1773.jpg 11.jpg 876.jpg

1998.txt,483.jpg 206.jpg 1069.jpg 861.jpg 597.jpg 1117.jpg 1273.jpg 983.jpg 141.jpg 1451.jpg 911.jpg 922.jpg 1204.jpg 912.jpg 806.jpg 1050.jpg 832.jpg 562.jpg 1092.jpg 1892.jpg

1999.txt,729.jpg 1827.jpg 307.jpg 405.jpg 1106.jpg 1342.jpg 243.jpg 453.jpg 745.jpg 308.jpg 1167.jpg 1728.jpg 32.jpg 1260.jpg 1137.jpg 369.jpg 1846.jpg 285.jpg 653.jpg 772.jpg

