In [1]:
import numpy as np

path_prefix = "./all/data/"
word_to_index = {} # map word to index
g_word_list = [] # sorted by frequence low to high
total_word_dict = {}
skip_words = set(['', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'as', 'an', 'and', 'are', 'at', 'by', 'down', 'for', 'from', 'front', 'has', 'in', 'is', 'it', 'near', 'next', 'of', 'on', 'out', 'over', 'several', 'sits', 'some', 'that', 'the', 'there', 'through', 'to', 'top', 'up', 'while', 'with'])
train_des = [] #0/1/2 array of word
test_des = [] #0/1/2 array of word
train_feature_list = [] # list of feature_array by index
test_feature_list = []
all_predict_test_des = []
train_g_category_tag = []
train_g_item_tag = []
test_g_category_tag = []
test_g_item_tag = []
train_captions = []
test_captions = []
MAX_INPUT = 10000
MAX_OUTPUT = 2000
COMPONENTS = 400 # need to run again
PCA_NUMBER = 2000 # need to run again
ITER = 500

In [2]:
def read_file_to_string(file_name, keep_colon):
    f = open(file_name, "r")
    content = f.read()
    f.close()
    content = content.lower()
    content = content.replace(",", " ").replace(".", " ").replace("'", " ").replace("\"", " ")
    if (keep_colon == False):
        content = content.replace(":", " ")
    return content

def read_file_to_total_word_dict(file_name, keep_colon):
    word_list = read_file_to_string(file_name, keep_colon).split()
    for name in word_list:
        if name in skip_words:
            continue
        if name in total_word_dict:
            total_word_dict[name] += 1
            continue
        else:
            total_word_dict[name] = 1
            continue

def print_word_in_array(a):
    ret = ""
    for i in range(len(a)):
        if a[i] != 0:
            ret = ret + str(a[i]) + g_word_list[i] + " "
    print(ret)

In [3]:
total_word_dict = {}
for i in range(MAX_INPUT):
    read_file_to_total_word_dict(path_prefix+"descriptions_train/"+str(i)+".txt", False)
    read_file_to_total_word_dict(path_prefix+"tags_train/"+str(i)+".txt", True)
    read_file_to_total_word_dict(path_prefix+"captions_train/"+str(i)+".txt", True)

In [4]:
import functools
def cmp(a, b):
    a_num = abs(float(a.split("___")[0]))
    b_num = abs(float(b.split("___")[0]))
    if (a_num < b_num):
        return -1
    return 1

In [5]:
# load g_word_list
g_word_list = []
word_to_index = {}
tmp_list = []
#TODO: maybe try filter on number
for word in total_word_dict:
    if total_word_dict[word] <= 0:
        continue
    tmp_list.append(str(total_word_dict[word])+"___"+word)

tmp_list = sorted(tmp_list, key=functools.cmp_to_key(cmp))

for i in range(len(tmp_list)):
    word = tmp_list[i].split("___")[1]
    g_word_list.append(word)
    word_to_index[word] = i

In [6]:
# read to tags
train_g_category_tag = [0] * MAX_INPUT
train_g_item_tag = [0] * MAX_INPUT
test_g_category_tag = [0] * MAX_OUTPUT
test_g_item_tag = [0] * MAX_OUTPUT

def is_in_tag(file_number, word, train):
    if train:
        return (word in train_g_category_tag[file_number]) or (word in train_g_item_tag[file_number])
    return (word in test_g_category_tag[file_number]) or (word in test_g_item_tag[file_number])

def read_tags(file_name, train):
    lines = read_file_to_string(file_name, True).split("\n")
    index = int(file_name.split("/")[-1].replace(".txt", ""))
    current_category_set = set([])
    current_item_set = set([])
    
    for line in lines:
        cat = line.split(":")[0].strip()
        if cat in word_to_index:
            current_category_set.add(cat)

        item = ''
        if (cat.strip() != line.replace(":", "").strip()):
            item = line.split(":")[1].strip()
        if item in word_to_index:
            current_item_set.add(item)
    if (train):
        train_g_category_tag[index] = current_category_set
        train_g_item_tag[index] = current_item_set
    else:
        test_g_category_tag[index] = current_category_set
        test_g_item_tag[index] = current_item_set
    

for i in range(MAX_INPUT):
    read_tags(path_prefix+"tags_train/"+str(i)+".txt", True)
for i in range(MAX_OUTPUT):
    read_tags(path_prefix+"tags_test/"+str(i)+".txt", False)

In [7]:
train_captions = [0] * MAX_INPUT
test_captions = [0] * MAX_OUTPUT

# read captions to tags
def read_captions(file_name, train):
    lines = read_file_to_string(file_name, False).split()
    index = int(file_name.split("/")[-1].replace(".txt", ""))
    current_word_set = set([])

    for line in lines:
        word_list = line.strip().split()
        for word in word_list:
            if word in word_to_index:
                current_word_set.add(word)
    if (train):
        train_captions[index] = current_word_set
    else:
        test_captions[index] = current_word_set

for i in range(MAX_INPUT):
    read_captions(path_prefix+"captions_train/"+str(i)+".txt", True)
for i in range(MAX_OUTPUT):
    read_captions(path_prefix+"captions_test/"+str(i)+".txt", False)

In [8]:
# where to make the change
# todo: remove count to match test output
# lenpi ci, yaoshi you dehua, jianfen
# also try norm

# count_max_weight = 2.0
# uniqueness_max_weight = 2.0
# TODO: add words in tag_item to pic
def my_weight_func(index, count, train, file_num):
    if (count <= 0):
        return 0
#     count_apply = 0
#     if is_in_tag(file_num, g_word_list[index], train):
#         count_apply = 1
#     elif count >= 3:
#         count_apply = 1
#     return 1 + (len(g_word_list)-index)*uniqueness_max_weight/len(g_word_list) + count_apply*count_max_weight

#     if count >= 5:
#         return count
#     if is_in_tag(file_num, g_word_list[index], train):
#         return 5
    return 1

def weight_occurance_array(occurance_array, train, file_num):
    ret = [0] * len(occurance_array)
    for index in range(len(occurance_array)):
        ret[index] = my_weight_func(index, occurance_array[index], train, file_num)
    return ret

def read_des_to_list(path, file_num):
    ret = []
    train = (path.find("train") != -1)
    for i in range(file_num):
        int_array = [0] * len(g_word_list)
        temp_list = read_file_to_string(path+str(i)+".txt", False).split()
        if train:
            temp_list.extend(train_captions[i])
        else:
            temp_list.extend(test_captions[i])
        for word in temp_list:
            if not word in word_to_index:
                continue
            int_array[word_to_index[word]] += 1
        ret.append(weight_occurance_array(int_array, train, i))
    return ret

train_des = read_des_to_list(path_prefix+"descriptions_train/", MAX_INPUT)
test_des = read_des_to_list(path_prefix+"descriptions_test/", MAX_OUTPUT)

In [9]:
# add tag to desc list

#TODO: careful with tag number
def add_tag_to_train_des():
    for sentence_index in range(MAX_INPUT):
        array_to_add = [0] * len(g_word_list)
        for tag in train_g_item_tag[sentence_index]:
            array_to_add[word_to_index[tag]] = 1
        
        ret = train_des[sentence_index].copy()
        for word_index in range(len(g_word_list)):
            ret[word_index] = max(ret[word_index], array_to_add[word_index])
        train_des[sentence_index] = ret

def add_tag_to_test_des():
    for sentence_index in range(MAX_OUTPUT):
        array_to_add = [0] * len(g_word_list)
        for tag in test_g_item_tag[sentence_index]:
            array_to_add[word_to_index[tag]] = 1
        
        ret = all_predict_test_des[sentence_index].copy()
        print(all_predict_test_des[sentence_index])
        for word_index in range(len(g_word_list)):
            ret[word_index] = max(ret[word_index], array_to_add[word_index])
        all_predict_test_des[sentence_index] = ret


In [10]:
add_tag_to_train_des()

In [11]:
# load feature list
def load_feature_into_list(filename):
    f = open(filename, "r")
    content = f.readlines()
    f.close()
    train = filename.find("train")
    for line in content:
        name_index = int(line.split(".jpg,")[0].split("/")[1])
        feature_list = line.split(".jpg,")[1].split(",")
        if train != -1:
            if name_index >= MAX_INPUT:
                continue
            train_feature_list[name_index] = feature_list
        else:
            if name_index >= MAX_OUTPUT:
                continue
            test_feature_list[name_index] = feature_list

train_feature_list = [0] * MAX_INPUT
test_feature_list = [0] * MAX_OUTPUT
# load_feature_into_list(path_prefix+"features_train/features_resnet1000_train.csv")
# load_feature_into_list(path_prefix+"features_test/features_resnet1000_test.csv")
load_feature_into_list(path_prefix+"features_train/features_resnet1000intermediate_train.csv")
load_feature_into_list(path_prefix+"features_test/features_resnet1000intermediate_test.csv")

train_feature_list = np.asarray(train_feature_list, dtype=np.float64)
test_feature_list = np.asarray(test_feature_list, dtype=np.float64)

In [12]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components = PCA_NUMBER)
# pca.fit(train_des)
# train_des_pca = pca.transform(train_des)
# test_des_pca = pca.transform(test_des)
train_des_pca = np.asarray(train_des)
test_des_pca = np.asarray(test_des)

print(train_des_pca.shape)
print(test_des_pca.shape)

# pca2 = PCA(n_components = PCA_NUMBER)
# pca2.fit(train_feature_list)
# train_feature_list = pca2.transform(train_feature_list)
# test_feature_list = pca2.transform(test_feature_list)
train_feature_list = np.asarray(train_feature_list)
test_feature_list = np.asarray(test_feature_list)

print(train_feature_list.shape)
print(test_feature_list.shape)

from sklearn.cross_decomposition import PLSRegression
print("Done 0")
model = PLSRegression(COMPONENTS, max_iter=ITER)
print("Done 1")
model.fit(train_feature_list, train_des_pca)
print("Done 2")

(10000, 9901)
(2000, 9901)
(10000, 2048)
(2000, 2048)
Done 0
Done 1


C:\Users\ranji\Anaconda3\lib\site-packages\sklearn\cross_decomposition\pls_.py:77: UserWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached')


Done 2


In [13]:
print("Start 3")
all_predict_test_des = model.predict(test_feature_list)
print("Done 3")

Start 3
Done 3


In [14]:
add_tag_to_test_des()

[ 2.98509616e-04  2.98509616e-04  4.31875001e-04 ...  0.00000000e+00
  3.77702623e-01 -3.19856032e-02]
[0.00140041 0.00140041 0.00257581 ... 0.         0.19929253 0.26987791]
[6.11082070e-04 6.11082070e-04 1.16659374e-03 ... 0.00000000e+00
 2.40152308e-01 8.00235896e-01]
[ 0.00181648  0.00181648 -0.00104554 ...  0.          0.30578907
  0.22287202]
[ 7.18116875e-04  7.18116875e-04  6.44978658e-04 ...  0.00000000e+00
  8.83521261e-01 -3.36080670e-02]
[ 0.00098108  0.00098108 -0.00101241 ...  0.          0.19250355
 -0.0545234 ]
[0.00165095 0.00165095 0.00410868 ... 0.         0.7275168  0.14569211]
[ 5.70950835e-04  5.70950835e-04  9.98541785e-04 ...  0.00000000e+00
 -2.88169379e-02  7.87486669e-01]
[ 9.70517631e-04  9.70517631e-04 -4.51104348e-04 ...  0.00000000e+00
  6.81655539e-01  2.60919478e-02]
[ 2.65760833e-05  2.65760833e-05 -2.53769243e-03 ...  0.00000000e+00
  9.89066583e-01 -2.31165345e-02]
[ 0.00024423  0.00024423 -0.00220541 ...  0.          0.14165545
  0.14717709]
[ 2.387

  0.70862355]
[7.90178183e-05 7.90178183e-05 3.57613352e-03 ... 0.00000000e+00
 4.24128701e-01 2.97918788e-02]
[1.23332452e-04 1.23332452e-04 4.31630815e-03 ... 0.00000000e+00
 2.19761992e-01 9.38423628e-02]
[ 0.00202321  0.00202321 -0.00238527 ...  0.          0.21173561
  0.14298721]
[0.00404696 0.00404696 0.00739221 ... 0.         0.08491229 0.05529547]
[-7.12444291e-05 -7.12444291e-05 -5.22505145e-04 ...  0.00000000e+00
  2.79231929e-01  5.96884138e-03]
[-1.21408107e-04 -1.21408107e-04  1.26573370e-03 ...  0.00000000e+00
  1.72990442e-01  3.80231606e-01]
[ 0.00137617  0.00137617 -0.00102697 ...  0.          0.27106369
 -0.1486361 ]
[ 0.00058812  0.00058812 -0.00498621 ...  0.          0.35031
 -0.00258126]
[-7.22469330e-04 -7.22469330e-04 -1.39278393e-03 ...  0.00000000e+00
  1.18205009e+00  8.24885439e-01]
[ 4.18110165e-04  4.18110165e-04 -1.80796958e-03 ...  0.00000000e+00
  1.99005575e-01  1.08338503e+00]
[ 0.00212183  0.00212183 -0.00145192 ...  0.         -0.31208349
  0.61824

[-0.00137056 -0.00137056  0.00075492 ...  0.          0.52540129
  0.42046371]
[ 1.21050595e-03  1.21050595e-03 -2.15807397e-05 ...  0.00000000e+00
  5.61837242e-01 -1.18475506e-01]
[ 0.00247199  0.00247199  0.00180723 ...  0.         -0.16033565
  0.97529478]
[ 2.88273137e-04  2.88273137e-04 -6.05983230e-04 ...  0.00000000e+00
  5.40146328e-01 -9.28484925e-02]
[-0.00120676 -0.00120676 -0.00104181 ...  0.          0.3386938
  0.33231546]
[-0.00096533 -0.00096533 -0.00101575 ...  0.          0.5431402
  0.12464445]
[-1.57060255e-04 -1.57060255e-04 -1.05564756e-03 ...  0.00000000e+00
  8.12617158e-01  5.23693880e-01]
[4.29643517e-04 4.29643517e-04 3.01966294e-04 ... 0.00000000e+00
 4.48398528e-01 8.56018762e-01]
[ 0.0008303   0.0008303  -0.00118025 ...  0.          0.40063284
 -0.04882324]
[ 2.77363189e-04  2.77363189e-04 -1.11780059e-04 ...  0.00000000e+00
  2.33518572e-01  5.28541588e-03]
[-0.00193291 -0.00193291  0.00502886 ...  0.          0.24285288
 -0.2325797 ]
[8.69595352e-04 8.6

[-0.00226809 -0.00226809  0.00220302 ...  0.         -0.06544185
  0.42156179]
[-0.00049201 -0.00049201 -0.00296674 ...  0.          0.2778937
  0.4202275 ]
[ 0.00220043  0.00220043  0.00101318 ...  0.          0.13003444
 -0.10159553]
[ 0.00105889  0.00105889 -0.00156891 ...  0.          0.1378834
  0.94842877]
[2.11301959e-03 2.11301959e-03 4.23351466e-04 ... 0.00000000e+00
 7.96014090e-01 2.25773622e-01]
[ 1.55259411e-04  1.55259411e-04 -9.48184636e-04 ...  0.00000000e+00
  3.48726420e-01  5.70816014e-01]
[ 0.00457677  0.00457677 -0.00249646 ...  0.          0.71077225
 -0.09630429]
[-4.69960400e-06 -4.69960400e-06  1.75683845e-03 ...  0.00000000e+00
  4.60484510e-01  1.71288021e-01]
[-1.41896108e-03 -1.41896108e-03 -2.04248068e-04 ...  0.00000000e+00
  6.90608054e-01  1.13204935e-01]
[-0.00133511 -0.00133511  0.00072065 ...  0.          0.70701963
 -0.14727851]
[-9.07528970e-04 -9.07528970e-04  1.31090136e-04 ...  0.00000000e+00
  5.68111020e-01  2.00901174e-01]
[ 0.00318059  0.003

[-1.46114953e-04 -1.46114953e-04 -2.33458209e-03 ...  0.00000000e+00
  2.61637626e-01 -1.91752864e-03]
[ 0.00110064  0.00110064  0.00240518 ...  0.          0.61922671
 -0.01292289]
[-1.13126178e-03 -1.13126178e-03 -7.34200209e-04 ...  0.00000000e+00
  8.20956991e-02  9.65926302e-01]
[-0.00264278 -0.00264278  0.00114411 ...  0.          0.31339727
  0.6314853 ]
[ 0.00256208  0.00256208  0.00306159 ...  0.         -0.04586102
  1.10233652]
[ 0.0009068   0.0009068  -0.00231795 ...  0.          0.22372393
 -0.09858657]
[0.00205662 0.00205662 0.00123391 ... 0.         0.47789917 0.06500779]
[-0.00202273 -0.00202273 -0.00179887 ...  0.          0.2302973
 -0.31996241]
[7.70751790e-05 7.70751790e-05 5.17169949e-03 ... 0.00000000e+00
 5.13494237e-01 9.37745596e-02]
[ 0.00034879  0.00034879 -0.00050077 ...  0.          0.25051247
  0.13519821]
[0.00116087 0.00116087 0.00142662 ... 0.         0.49843333 0.81959982]
[-1.23478393e-04 -1.23478393e-04 -1.60301903e-03 ...  0.00000000e+00
  5.1878822

[-0.00162365 -0.00162365  0.00252663 ...  0.          0.40637297
  0.24666341]
[ 0.00259318  0.00259318 -0.00208778 ...  0.          0.45827283
  0.23756337]
[ 7.37157007e-04  7.37157007e-04  4.85972780e-04 ...  0.00000000e+00
 -5.37957630e-03  6.23797255e-01]
[-0.00227464 -0.00227464 -0.00142139 ...  0.          0.92512682
 -0.12972071]
[-0.0008732  -0.0008732   0.00429321 ...  0.          0.24464851
 -0.04182141]
[-1.53175680e-03 -1.53175680e-03  9.12574449e-05 ...  0.00000000e+00
  7.44450687e-02  8.76342751e-01]
[ 6.54555350e-05  6.54555350e-05 -4.13218670e-04 ...  0.00000000e+00
  9.83498042e-02  3.21377170e-01]
[-0.00123674 -0.00123674 -0.00262953 ...  0.          0.212307
  0.1943406 ]
[ 1.31164433e-04  1.31164433e-04 -2.92112717e-03 ...  0.00000000e+00
  6.00384309e-01  1.07568081e+00]
[0.00087239 0.00087239 0.00133781 ... 0.         0.48139709 0.03223508]
[-0.00128433 -0.00128433 -0.00314188 ...  0.          0.51661607
  0.18234173]
[-0.00217117 -0.00217117 -0.00143353 ...  0.

[ 8.85495492e-05  8.85495492e-05 -2.43382612e-03 ...  0.00000000e+00
  6.21676891e-01  4.94175463e-01]
[-0.00153284 -0.00153284  0.00209018 ...  0.          0.7369936
  0.72785845]
[ 3.38402846e-03  3.38402846e-03  2.48654795e-04 ...  0.00000000e+00
  3.98483766e-01 -7.60492550e-02]
[ 2.32313476e-04  2.32313476e-04  6.71607557e-04 ...  0.00000000e+00
  6.64825279e-01 -2.86643761e-02]
[-0.00030107 -0.00030107  0.00277747 ...  0.          0.11312324
  0.16802775]
[-6.41705785e-04 -6.41705785e-04 -7.98916147e-04 ...  0.00000000e+00
  5.66152979e-01  6.88275948e-01]
[2.37819928e-04 2.37819928e-04 1.19160589e-03 ... 0.00000000e+00
 2.60678584e-01 2.77279981e-01]
[-0.00181118 -0.00181118 -0.00196678 ...  0.          0.08291047
  0.7833648 ]
[-9.52195159e-05 -9.52195159e-05  2.49629021e-03 ...  0.00000000e+00
  3.56483522e-01  1.05746895e+00]
[-0.00231091 -0.00231091  0.00206343 ...  0.          0.98214642
  0.05062261]
[6.16505027e-04 6.16505027e-04 2.04744450e-03 ... 0.00000000e+00
 4.22621

[-4.32795165e-04 -4.32795165e-04  1.33450583e-04 ...  0.00000000e+00
  3.69865483e-01  7.66982244e-01]
[-0.00085504 -0.00085504  0.00266325 ...  0.          0.04331206
  0.81683353]
[-0.00052617 -0.00052617 -0.00013529 ...  0.         -0.12361535
  0.07453301]
[ 0.00061237  0.00061237  0.00034815 ...  0.         -0.10021864
 -0.02404668]
[-1.24209484e-04 -1.24209484e-04  5.76484475e-04 ...  0.00000000e+00
  4.09446223e-01  6.28535036e-01]
[ 0.00093597  0.00093597 -0.00255812 ...  0.          0.46831845
 -0.10564472]
[-0.00035512 -0.00035512 -0.00378269 ...  0.          0.17620662
 -0.02349831]
[-0.00114985 -0.00114985 -0.00144536 ...  0.          0.4249953
 -0.1273174 ]
[ 0.00093806  0.00093806 -0.00040164 ...  0.          0.12609783
 -0.01632225]
[0.00041517 0.00041517 0.00396206 ... 0.         0.22689029 0.10636872]
[-0.00101785 -0.00101785  0.00112841 ...  0.          0.38932357
  0.05702401]
[-0.00246694 -0.00246694  0.00105042 ...  0.          0.31265432
  0.30448193]
[-6.76763072

[-0.00036668 -0.00036668  0.00037274 ...  0.          0.35968239
  0.25443534]
[-0.00168857 -0.00168857 -0.00058184 ...  0.          0.2273821
  0.30977638]
[-0.001126   -0.001126    0.00137053 ...  0.          0.87915264
 -0.22309382]
[0.00118666 0.00118666 0.00050918 ... 0.         0.25814808 0.26892279]
[-0.00099712 -0.00099712 -0.00104089 ...  0.          0.77365417
  0.79463874]
[-3.12543655e-04 -3.12543655e-04 -4.35773314e-03 ...  0.00000000e+00
  4.87312945e-01  1.64115009e-01]
[-0.00141369 -0.00141369  0.00098479 ...  0.          0.50143275
 -0.03367167]
[-0.00076759 -0.00076759  0.0016444  ...  0.          0.18745073
 -0.0203864 ]
[-0.00174862 -0.00174862 -0.00092534 ...  0.          0.42289169
 -0.11229598]
[-8.66009359e-05 -8.66009359e-05 -2.44863918e-03 ...  0.00000000e+00
 -3.31474740e-04 -5.19645144e-02]
[-0.0027219  -0.0027219   0.00284403 ...  0.          0.6914597
  0.10745508]
[0.00149112 0.00149112 0.00101947 ... 0.         0.55349117 0.45943052]
[ 9.17075882e-04  9.

[-0.0012505  -0.0012505   0.00466717 ...  0.          0.02886737
 -0.20498481]
[-0.00110663 -0.00110663 -0.00135264 ...  0.          0.27670048
  0.76034858]
[ 0.00096557  0.00096557 -0.00290998 ...  0.          0.31082197
 -0.06336974]
[1.10534934e-03 1.10534934e-03 1.02029551e-04 ... 0.00000000e+00
 8.40091047e-01 3.20620569e-02]
[-4.76152762e-04 -4.76152762e-04 -1.06106977e-03 ...  0.00000000e+00
  1.06277967e+00 -2.53522988e-02]
[0.00630591 0.00630591 0.00047071 ... 0.         0.03523139 0.29549452]
[-0.00108471 -0.00108471 -0.00562029 ...  0.          0.27214468
  0.03899982]
[1.36102591e-03 1.36102591e-03 4.04281171e-04 ... 0.00000000e+00
 7.33079818e-01 8.59722045e-01]
[2.59694678e-03 2.59694678e-03 4.32700893e-04 ... 0.00000000e+00
 4.62567401e-01 2.33634722e-01]
[ 0.00112988  0.00112988 -0.00063921 ...  0.          0.18367579
  0.44263708]
[-0.00257542 -0.00257542 -0.00057779 ...  0.          0.4950532
  0.37467399]
[-3.25515380e-04 -3.25515380e-04 -1.10812280e-03 ...  0.00000

[-5.97782034e-04 -5.97782034e-04  2.55247481e-03 ...  0.00000000e+00
  7.15758767e-01 -1.14479217e-01]
[0.00264387 0.00264387 0.00242664 ... 0.         0.42152305 0.57557842]
[-0.00072376 -0.00072376  0.00150638 ...  0.          0.23110177
  0.07163127]
[-0.00107591 -0.00107591 -0.00101332 ...  0.          0.19574065
 -0.00129947]
[ 1.49354278e-03  1.49354278e-03  2.40914609e-04 ...  0.00000000e+00
  6.77912896e-01 -7.19705448e-03]
[-1.85143448e-04 -1.85143448e-04 -3.56552884e-04 ...  0.00000000e+00
 -1.19793112e-02  5.69214620e-01]
[-0.00043682 -0.00043682  0.00281831 ...  0.          0.25144576
  0.18669988]
[0.00128681 0.00128681 0.00109643 ... 0.         0.57455159 0.28888963]
[-1.48874835e-03 -1.48874835e-03 -6.96749106e-05 ...  0.00000000e+00
  1.04034263e-01 -7.71434788e-02]
[1.93252670e-04 1.93252670e-04 1.62299953e-03 ... 0.00000000e+00
 5.70778046e-01 1.29021362e-02]
[ 2.76652100e-03  2.76652100e-03 -3.78564990e-04 ...  0.00000000e+00
  3.80565166e-01  5.37403259e-01]
[-0.001

 4.96693238e-02 7.77524711e-01]
[-0.00061645 -0.00061645  0.00163766 ...  0.          0.04083479
  0.01700178]
[-0.00229619 -0.00229619  0.00092018 ...  0.          0.12183014
  0.10988502]
[-0.00052895 -0.00052895 -0.00056779 ...  0.         -0.02421468
 -0.00933232]
[-0.00185187 -0.00185187  0.00049743 ...  0.          0.38526509
 -0.09964803]
[-1.64792227e-03 -1.64792227e-03  6.30137884e-04 ...  0.00000000e+00
 -4.92339690e-02  9.12595234e-01]
[-8.46455234e-05 -8.46455234e-05  5.37938484e-04 ...  0.00000000e+00
  8.56566713e-02  6.18347258e-01]
[ 4.91685335e-05  4.91685335e-05  1.60342962e-03 ...  0.00000000e+00
  5.44064569e-02 -1.02098383e-01]
[-2.10536592e-03 -2.10536592e-03  6.33442204e-05 ...  0.00000000e+00
  2.08675042e-01 -6.76774165e-02]
[-8.66100637e-05 -8.66100637e-05  2.04756523e-03 ...  0.00000000e+00
  4.90858941e-01 -9.00784271e-02]
[-0.00140107 -0.00140107  0.00077091 ...  0.          0.49639969
  0.56129279]
[0.00356505 0.00356505 0.00217078 ... 0.         0.5709456

[0.00144161 0.00144161 0.00147841 ... 0.         0.23317089 0.06202297]
[-1.36026913e-04 -1.36026913e-04  1.05141814e-03 ...  0.00000000e+00
  3.22488992e-01  6.27697048e-01]
[-3.88618722e-04 -3.88618722e-04  5.31241249e-03 ...  0.00000000e+00
  4.52070046e-01  6.90511230e-01]
[ 0.00069614  0.00069614  0.00168822 ...  0.          0.64111933
 -0.04976502]
[ 0.00029192  0.00029192 -0.00201901 ...  0.          0.06485882
  0.03761118]
[ 0.00086639  0.00086639 -0.00234864 ...  0.          0.6803706
  0.11565308]
[ 8.80163159e-04  8.80163159e-04 -1.41618028e-03 ...  0.00000000e+00
  5.01827475e-01  1.14929404e+00]
[ 0.00090361  0.00090361 -0.00123542 ...  0.          0.49516807
  0.04694628]
[ 0.0008983   0.0008983  -0.00309293 ...  0.          0.09899925
  0.46091512]
[3.45772308e-04 3.45772308e-04 7.50644151e-04 ... 0.00000000e+00
 5.34276068e-01 2.03480975e-01]
[-9.40657388e-04 -9.40657388e-04 -9.16022651e-04 ...  0.00000000e+00
 -9.66593874e-02  1.14846149e+00]
[-0.00081583 -0.00081583 

[-0.00157989 -0.00157989 -0.00291439 ...  0.          0.60242693
  0.49719659]
[-0.00329603 -0.00329603 -0.000722   ...  0.          0.32401904
  0.30099664]
[ 0.00137507  0.00137507  0.0028009  ...  0.          0.67844417
 -0.22850217]
[ 1.61549590e-04  1.61549590e-04 -2.19956445e-03 ...  0.00000000e+00
 -6.23653883e-02  1.86672566e-01]
[-0.00271281 -0.00271281  0.0020397  ...  0.          0.73615708
  0.22548813]
[ 1.70475261e-03  1.70475261e-03 -2.25036504e-04 ...  0.00000000e+00
  6.55831234e-01  3.51984493e-02]
[ 0.00162375  0.00162375 -0.00343597 ...  0.          0.43362063
  0.279712  ]
[-0.00205384 -0.00205384  0.00115771 ...  0.          0.50222063
  0.1682765 ]
[-1.32035199e-03 -1.32035199e-03  5.50606793e-04 ...  0.00000000e+00
  3.42562790e-01  7.15666881e-01]
[ 0.00151824  0.00151824  0.00106644 ...  0.         -0.11285597
 -0.0893343 ]
[-0.00200382 -0.00200382  0.00107897 ...  0.          0.11215316
  0.48962093]
[ 1.25494530e-03  1.25494530e-03 -9.96292582e-04 ...  0.000

[1.87639078e-03 1.87639078e-03 3.29857343e-04 ... 0.00000000e+00
 3.49392084e-01 8.69793598e-02]
[ 0.00284572  0.00284572 -0.00249015 ...  0.          0.62184645
  0.31980091]
[-0.00047483 -0.00047483 -0.00227084 ...  0.          0.43029684
  0.44359646]
[-0.00134557 -0.00134557  0.00194377 ...  0.          0.68295214
  0.44172281]
[ 3.38567663e-03  3.38567663e-03 -1.81032723e-04 ...  0.00000000e+00
  5.56642948e-01  6.08603498e-01]
[-0.00072256 -0.00072256  0.0008572  ...  0.          0.34366284
  0.46124375]
[-1.68902702e-03 -1.68902702e-03 -4.08869029e-04 ...  0.00000000e+00
  2.71021105e-01  5.75524838e-01]
[ 0.00293784  0.00293784 -0.00305651 ...  0.         -0.02832736
  0.6662802 ]
[ 5.07132851e-04  5.07132851e-04 -1.90604766e-03 ...  0.00000000e+00
  5.14162758e-01  3.45616025e-02]
[ 0.00155404  0.00155404 -0.00063441 ...  0.          0.31546539
  0.24285462]
[-0.00182804 -0.00182804 -0.00228921 ...  0.          0.10862172
  0.87066483]
[ 0.0027882   0.0027882  -0.00045408 ... 

[ 0.00149337  0.00149337 -0.00222968 ...  0.         -0.09117006
  0.79068351]
[-6.81142633e-04 -6.81142633e-04  1.46478109e-04 ...  0.00000000e+00
  6.72327269e-01 -3.46098181e-02]
[-0.00068034 -0.00068034  0.00914844 ...  0.          0.31898158
  0.16438997]
[ 0.00166058  0.00166058 -0.00322139 ...  0.          0.46086688
 -0.08171882]
[ 2.36161288e-04  2.36161288e-04 -4.00621197e-03 ...  0.00000000e+00
  4.84674855e-01  5.19000983e-01]
[-0.00102426 -0.00102426 -0.00073345 ...  0.          0.33515036
 -0.14947247]
[-6.49819453e-04 -6.49819453e-04 -6.28929633e-05 ...  0.00000000e+00
  6.69147341e-01  4.86789657e-01]
[0.00232281 0.00232281 0.00213661 ... 0.         0.0983341  0.92382771]
[-0.0041559  -0.0041559  -0.00183423 ...  0.          0.79596714
  0.7653148 ]
[2.73644114e-03 2.73644114e-03 1.76444455e-04 ... 0.00000000e+00
 2.83585884e-01 1.54193345e-01]
[-0.00154351 -0.00154351  0.00344612 ...  0.          0.34191808
 -0.03673753]
[-8.33708287e-04 -8.33708287e-04  3.00093109e-04

[ 2.69987264e-04  2.69987264e-04 -8.08148877e-04 ...  0.00000000e+00
  5.37550445e-01  4.83691685e-02]
[-3.74452930e-04 -3.74452930e-04  1.53175651e-03 ...  0.00000000e+00
 -3.00485498e-02  1.12874255e+00]
[0.00203478 0.00203478 0.00094648 ... 0.         0.66824035 0.03748939]
[ 0.00452218  0.00452218 -0.00232834 ...  0.          0.43531906
  0.21696633]
[-0.00271648 -0.00271648 -0.00395535 ...  0.          0.83408062
  0.91232477]
[ 1.67751934e-04  1.67751934e-04 -6.39106690e-04 ...  0.00000000e+00
  4.99778474e-01  4.85486296e-01]
[-0.00064795 -0.00064795  0.00271625 ...  0.          0.03581463
  0.15712683]
[-0.00092542 -0.00092542  0.00025639 ...  0.         -0.0234244
  0.23885494]
[-0.00076926 -0.00076926 -0.00231709 ...  0.          0.73562363
  0.50205312]
[-1.72345297e-03 -1.72345297e-03  2.68841191e-03 ...  0.00000000e+00
  7.21244222e-01 -3.57005146e-05]
[ 1.92481824e-04  1.92481824e-04 -2.00773866e-03 ...  0.00000000e+00
 -1.08593228e-01  7.45899724e-01]
[ 0.00216229  0.002

[-0.00061869 -0.00061869  0.00167899 ...  0.          0.07974159
 -0.16450435]
[1.50699726e-05 1.50699726e-05 1.15365620e-02 ... 0.00000000e+00
 2.46780076e-01 2.15911943e-01]
[-0.00042825 -0.00042825 -0.00329148 ...  0.          0.22517197
 -0.15893094]
[-4.23569155e-04 -4.23569155e-04 -2.03713134e-03 ...  0.00000000e+00
  4.46107589e-01  3.28369202e-02]
[-0.00191446 -0.00191446  0.01229413 ...  0.          0.33961564
  0.37095932]
[ 5.61374521e-04  5.61374521e-04  2.35013861e-04 ...  0.00000000e+00
  5.37469717e-01 -5.50172412e-02]
[-0.00177259 -0.00177259 -0.00157864 ...  0.          0.62937659
  0.12408047]
[ 5.99454039e-04  5.99454039e-04 -3.21316493e-04 ...  0.00000000e+00
  5.84160751e-01  3.66468337e-01]
[-0.00181831 -0.00181831 -0.00271006 ...  0.          1.10971327
  0.01028717]
[6.17736780e-04 6.17736780e-04 3.55631326e-03 ... 0.00000000e+00
 6.34811131e-01 2.35525312e-01]
[3.81550226e-03 3.81550226e-03 1.16477557e-04 ... 0.00000000e+00
 6.14675749e-01 1.94836281e-01]
[ 0.0

[-2.97118278e-03 -2.97118278e-03 -2.32089873e-04 ...  0.00000000e+00
  1.14094451e-02  2.76478763e-01]
[0.00171965 0.00171965 0.00264276 ... 0.         0.34079349 0.40854996]
[ 0.00253483  0.00253483 -0.0011226  ...  0.          0.65771975
 -0.0614166 ]
[ 0.00198323  0.00198323 -0.00071659 ...  0.          0.36574055
 -0.0339735 ]
[3.75997511e-03 3.75997511e-03 1.24183038e-04 ... 0.00000000e+00
 2.61152560e-01 2.29084350e-01]
[ 0.00194803  0.00194803 -0.00242334 ...  0.          0.02429475
  0.59191072]
[-0.0037698  -0.0037698  -0.0028169  ...  0.          0.35018608
  0.09360808]
[0.00038891 0.00038891 0.00110118 ... 0.         0.28278712 0.17800401]
[-0.00136025 -0.00136025 -0.00126871 ...  0.          0.11436277
  0.39012801]
[ 9.58939355e-04  9.58939355e-04 -6.15303508e-04 ...  0.00000000e+00
  2.63089237e-01  1.03432828e+00]
[ 4.67500676e-04  4.67500676e-04 -3.36434561e-04 ...  0.00000000e+00
  4.31927320e-01  1.73904920e-01]
[ 0.00274061  0.00274061 -0.00153533 ...  0.          0

[ 2.03844258e-03  2.03844258e-03 -7.49885140e-05 ...  0.00000000e+00
  3.10310173e-01  5.95988301e-01]
[ 1.02684804e-03  1.02684804e-03 -7.89226373e-05 ...  0.00000000e+00
  1.02724744e+00 -1.06278218e-01]
[ 0.00382097  0.00382097 -0.00608394 ...  0.          0.8562501
  0.15342999]
[ 0.00042489  0.00042489 -0.00244207 ...  0.          0.4110056
 -0.18520968]
[-0.00321221 -0.00321221 -0.00036341 ...  0.          0.004238
 -0.08306268]
[ 0.00164742  0.00164742 -0.00577279 ...  0.          0.21756136
  0.01049441]
[2.24104488e-03 2.24104488e-03 4.37756106e-04 ... 0.00000000e+00
 6.17334513e-01 2.31351628e-01]
[-0.00061763 -0.00061763 -0.00074911 ...  0.          0.4428254
 -0.04208403]
[-1.00316573e-03 -1.00316573e-03  2.54140450e-04 ...  0.00000000e+00
 -3.48464692e-03  4.39703842e-01]
[ 0.00128988  0.00128988 -0.00196485 ...  0.          0.56858646
 -0.14151687]
[ 1.88962972e-04  1.88962972e-04 -4.18306266e-03 ...  0.00000000e+00
  7.68829541e-01 -9.88366362e-02]
[-0.00146783 -0.001467

[-0.0011665  -0.0011665  -0.00113324 ...  0.          0.58304055
  0.32585061]
[-0.00053171 -0.00053171  0.0024106  ...  0.         -0.05601967
 -0.06895474]
[-0.00070999 -0.00070999 -0.00055385 ...  0.          0.09096737
  0.04335235]
[ 0.00100598  0.00100598 -0.00167575 ...  0.          0.31415477
  0.12745127]
[6.80495060e-04 6.80495060e-04 2.21623821e-04 ... 0.00000000e+00
 2.87927397e-01 6.43752001e-03]
[0.00322359 0.00322359 0.00340926 ... 0.         0.49491038 0.62504057]
[ 0.00102104  0.00102104  0.00832269 ...  0.         -0.37595715
  0.85005773]
[0.00449062 0.00449062 0.00115318 ... 0.         0.10670206 0.21017963]
[ 5.38443575e-04  5.38443575e-04 -3.47633667e-03 ...  0.00000000e+00
  5.67962787e-01  4.90107477e-01]
[1.97741493e-03 1.97741493e-03 9.11859294e-06 ... 0.00000000e+00
 7.17283780e-01 4.81130122e-01]
[-1.38272898e-04 -1.38272898e-04  1.84054873e-04 ...  0.00000000e+00
  1.62323888e-01  1.07998954e+00]
[ 0.0009925   0.0009925  -0.00252672 ...  0.         -0.01860

In [15]:
import sklearn.metrics

# return a score
def compare_feature(target, given):
    return float(sklearn.metrics.pairwise.cosine_distances([np.array(target, dtype=float)], [np.array(given, dtype=float)]))
#     return float(np.linalg.norm(np.array(target, dtype=float) - np.array(given, dtype=float)))

def get_top_20(target):
    ret = []
    for index in range(MAX_OUTPUT):
        given = all_predict_test_des[index]
        score = compare_feature(target, given)
        item = str(score) + "___" + str(index)
        ret.append(item)
    return sorted(ret, key=functools.cmp_to_key(cmp))[:20]

# f = open("reverse_count_"+str(count_max_weight)+"unique"+str(uniqueness_max_weight)+".csv", "w")
f = open("reverse_with_captions.csv", "w")
f.write("Descritpion_ID,Top_20_Image_IDs\n")
for index in range(MAX_OUTPUT):
    target_desc = test_des_pca[index]
    twenty_image_list = get_top_20(target_desc)
    string_to_write = "" + str(index) + ".txt,"
    for name in twenty_image_list:
        file_name = name.split("___")[1] + ".jpg"+" "
        string_to_write += file_name
    string_to_write = string_to_write.strip() + "\n"
    print(string_to_write)
    f.write(string_to_write)

f.close()

0.txt,575.jpg 1105.jpg 93.jpg 1869.jpg 352.jpg 1135.jpg 255.jpg 831.jpg 856.jpg 974.jpg 1420.jpg 1238.jpg 1629.jpg 381.jpg 1131.jpg 123.jpg 1702.jpg 1011.jpg 700.jpg 1811.jpg

1.txt,833.jpg 288.jpg 1.jpg 376.jpg 1156.jpg 285.jpg 589.jpg 1760.jpg 427.jpg 418.jpg 1890.jpg 1841.jpg 1469.jpg 1820.jpg 1438.jpg 314.jpg 627.jpg 1220.jpg 1279.jpg 818.jpg

2.txt,598.jpg 1724.jpg 445.jpg 1840.jpg 159.jpg 1713.jpg 1208.jpg 1030.jpg 838.jpg 332.jpg 1437.jpg 1084.jpg 649.jpg 953.jpg 1665.jpg 1421.jpg 42.jpg 1366.jpg 1651.jpg 1471.jpg

3.txt,1421.jpg 904.jpg 649.jpg 1059.jpg 1208.jpg 1475.jpg 1084.jpg 1471.jpg 1665.jpg 1366.jpg 821.jpg 763.jpg 1023.jpg 1030.jpg 1024.jpg 696.jpg 322.jpg 1330.jpg 979.jpg 1499.jpg

4.txt,95.jpg 233.jpg 1986.jpg 639.jpg 543.jpg 1238.jpg 1593.jpg 18.jpg 1299.jpg 1816.jpg 1670.jpg 672.jpg 722.jpg 1276.jpg 742.jpg 4.jpg 1498.jpg 1324.jpg 292.jpg 922.jpg

5.txt,771.jpg 1991.jpg 51.jpg 492.jpg 330.jpg 1693.jpg 814.jpg 1335.jpg 703.jpg 1874.jpg 630.jpg 846.jpg 1660.jpg 379.jp

47.txt,1133.jpg 1767.jpg 817.jpg 937.jpg 1731.jpg 441.jpg 1149.jpg 17.jpg 148.jpg 340.jpg 1536.jpg 223.jpg 1511.jpg 618.jpg 1126.jpg 1253.jpg 234.jpg 1922.jpg 1632.jpg 1719.jpg

48.txt,1713.jpg 445.jpg 953.jpg 1866.jpg 904.jpg 1665.jpg 838.jpg 60.jpg 1840.jpg 1242.jpg 159.jpg 696.jpg 1664.jpg 1641.jpg 1634.jpg 934.jpg 431.jpg 634.jpg 1724.jpg 1366.jpg

49.txt,1761.jpg 887.jpg 1888.jpg 274.jpg 1818.jpg 1830.jpg 334.jpg 554.jpg 892.jpg 1696.jpg 1895.jpg 1743.jpg 389.jpg 703.jpg 814.jpg 630.jpg 526.jpg 1136.jpg 595.jpg 1693.jpg

50.txt,932.jpg 183.jpg 1711.jpg 1534.jpg 560.jpg 1832.jpg 1190.jpg 384.jpg 1290.jpg 1432.jpg 415.jpg 1302.jpg 54.jpg 1469.jpg 1703.jpg 1210.jpg 1363.jpg 1223.jpg 1022.jpg 1362.jpg

51.txt,1727.jpg 1097.jpg 1379.jpg 1145.jpg 514.jpg 1404.jpg 475.jpg 1886.jpg 1088.jpg 1215.jpg 1818.jpg 26.jpg 1889.jpg 1207.jpg 330.jpg 354.jpg 1630.jpg 554.jpg 1700.jpg 1696.jpg

52.txt,346.jpg 498.jpg 620.jpg 1926.jpg 1746.jpg 52.jpg 914.jpg 1798.jpg 1434.jpg 921.jpg 745.jpg 1213.jpg

94.txt,1143.jpg 885.jpg 1039.jpg 1807.jpg 331.jpg 286.jpg 835.jpg 169.jpg 571.jpg 185.jpg 1116.jpg 160.jpg 1714.jpg 589.jpg 1408.jpg 1313.jpg 14.jpg 818.jpg 1134.jpg 1550.jpg

95.txt,51.jpg 1335.jpg 814.jpg 1426.jpg 492.jpg 1943.jpg 1693.jpg 771.jpg 703.jpg 630.jpg 846.jpg 20.jpg 379.jpg 1913.jpg 526.jpg 1888.jpg 1830.jpg 274.jpg 321.jpg 887.jpg

96.txt,445.jpg 1713.jpg 953.jpg 1665.jpg 1840.jpg 634.jpg 696.jpg 1499.jpg 1124.jpg 1033.jpg 1724.jpg 159.jpg 1471.jpg 1866.jpg 511.jpg 904.jpg 1716.jpg 1084.jpg 838.jpg 769.jpg

97.txt,1739.jpg 607.jpg 1664.jpg 545.jpg 690.jpg 1033.jpg 1211.jpg 445.jpg 1460.jpg 1483.jpg 938.jpg 1440.jpg 1487.jpg 319.jpg 1605.jpg 680.jpg 598.jpg 1866.jpg 180.jpg 399.jpg

98.txt,864.jpg 47.jpg 1004.jpg 899.jpg 1706.jpg 420.jpg 712.jpg 459.jpg 1821.jpg 848.jpg 1600.jpg 1179.jpg 837.jpg 1817.jpg 343.jpg 521.jpg 221.jpg 414.jpg 328.jpg 982.jpg

99.txt,1683.jpg 830.jpg 1825.jpg 1417.jpg 1267.jpg 1631.jpg 1585.jpg 1685.jpg 1576.jpg 1640.jpg 1374.jpg 215.jpg 1861.jpg

141.txt,1127.jpg 37.jpg 2.jpg 31.jpg 1433.jpg 1385.jpg 1098.jpg 734.jpg 1676.jpg 670.jpg 1736.jpg 1696.jpg 636.jpg 1050.jpg 1236.jpg 52.jpg 1577.jpg 1504.jpg 1441.jpg 1131.jpg

142.txt,890.jpg 713.jpg 251.jpg 1014.jpg 1863.jpg 1304.jpg 1951.jpg 961.jpg 301.jpg 380.jpg 423.jpg 83.jpg 1159.jpg 988.jpg 1160.jpg 142.jpg 9.jpg 517.jpg 1549.jpg 1182.jpg

143.txt,1713.jpg 445.jpg 953.jpg 1665.jpg 143.jpg 1124.jpg 1208.jpg 1366.jpg 1664.jpg 1724.jpg 1641.jpg 1033.jpg 634.jpg 1840.jpg 1686.jpg 1340.jpg 784.jpg 696.jpg 1030.jpg 1471.jpg

144.txt,1077.jpg 1099.jpg 197.jpg 1024.jpg 949.jpg 1609.jpg 1381.jpg 1174.jpg 562.jpg 601.jpg 843.jpg 1769.jpg 717.jpg 529.jpg 1880.jpg 1231.jpg 576.jpg 1526.jpg 1679.jpg 626.jpg

145.txt,692.jpg 513.jpg 1563.jpg 694.jpg 1246.jpg 1079.jpg 1652.jpg 212.jpg 145.jpg 1080.jpg 1983.jpg 278.jpg 1357.jpg 1869.jpg 780.jpg 665.jpg 1811.jpg 1537.jpg 884.jpg 715.jpg

146.txt,111.jpg 1833.jpg 1931.jpg 146.jpg 1556.jpg 1864.jpg 1674.jpg 1987.jpg 1618.jpg 561.jpg 1763.jpg 184

188.txt,1104.jpg 803.jpg 1583.jpg 1829.jpg 1766.jpg 327.jpg 447.jpg 277.jpg 1467.jpg 1604.jpg 710.jpg 477.jpg 195.jpg 472.jpg 283.jpg 241.jpg 551.jpg 1946.jpg 581.jpg 248.jpg

189.txt,802.jpg 148.jpg 1930.jpg 1632.jpg 986.jpg 709.jpg 618.jpg 925.jpg 1767.jpg 325.jpg 1403.jpg 109.jpg 85.jpg 161.jpg 1996.jpg 852.jpg 71.jpg 547.jpg 474.jpg 1091.jpg

190.txt,1744.jpg 1640.jpg 1579.jpg 1859.jpg 1288.jpg 716.jpg 884.jpg 1357.jpg 1879.jpg 1038.jpg 145.jpg 1150.jpg 122.jpg 1063.jpg 715.jpg 1831.jpg 212.jpg 190.jpg 905.jpg 1801.jpg

191.txt,2.jpg 1816.jpg 256.jpg 141.jpg 1213.jpg 1050.jpg 1087.jpg 210.jpg 849.jpg 1046.jpg 31.jpg 734.jpg 1384.jpg 1231.jpg 620.jpg 922.jpg 199.jpg 1203.jpg 534.jpg 1466.jpg

192.txt,633.jpg 290.jpg 609.jpg 1330.jpg 1143.jpg 192.jpg 1039.jpg 331.jpg 885.jpg 1807.jpg 1134.jpg 1960.jpg 571.jpg 121.jpg 224.jpg 1408.jpg 981.jpg 1346.jpg 828.jpg 568.jpg

193.txt,54.jpg 1210.jpg 1290.jpg 1363.jpg 1022.jpg 1123.jpg 1703.jpg 1832.jpg 1616.jpg 1775.jpg 1448.jpg 1711.jpg 1534

235.txt,733.jpg 499.jpg 780.jpg 707.jpg 1490.jpg 578.jpg 1378.jpg 324.jpg 1007.jpg 1294.jpg 1964.jpg 1058.jpg 1994.jpg 396.jpg 1148.jpg 1019.jpg 1545.jpg 827.jpg 1805.jpg 278.jpg

236.txt,932.jpg 1903.jpg 384.jpg 1056.jpg 1210.jpg 1802.jpg 1832.jpg 1711.jpg 10.jpg 1132.jpg 695.jpg 1193.jpg 1290.jpg 1190.jpg 1534.jpg 183.jpg 1703.jpg 951.jpg 1123.jpg 577.jpg

237.txt,1441.jpg 64.jpg 194.jpg 708.jpg 439.jpg 440.jpg 214.jpg 1307.jpg 673.jpg 289.jpg 853.jpg 1745.jpg 1623.jpg 544.jpg 1936.jpg 1984.jpg 1376.jpg 1297.jpg 518.jpg 1235.jpg

238.txt,1378.jpg 578.jpg 278.jpg 499.jpg 291.jpg 324.jpg 780.jpg 385.jpg 707.jpg 1964.jpg 1422.jpg 1294.jpg 1349.jpg 1019.jpg 733.jpg 1490.jpg 1805.jpg 1586.jpg 1545.jpg 1007.jpg

239.txt,1118.jpg 1533.jpg 333.jpg 1594.jpg 354.jpg 1218.jpg 1693.jpg 20.jpg 426.jpg 1888.jpg 1429.jpg 106.jpg 1700.jpg 843.jpg 1335.jpg 1913.jpg 846.jpg 322.jpg 1830.jpg 814.jpg

240.txt,1059.jpg 1421.jpg 1208.jpg 649.jpg 1030.jpg 763.jpg 1084.jpg 768.jpg 143.jpg 821.jpg 1890.jpg 1

281.txt,1604.jpg 472.jpg 1747.jpg 281.jpg 241.jpg 1048.jpg 381.jpg 581.jpg 1343.jpg 327.jpg 388.jpg 558.jpg 664.jpg 1544.jpg 955.jpg 1283.jpg 195.jpg 1467.jpg 679.jpg 447.jpg

282.txt,471.jpg 960.jpg 26.jpg 1215.jpg 1889.jpg 1207.jpg 1101.jpg 1070.jpg 1097.jpg 1145.jpg 1614.jpg 971.jpg 1415.jpg 374.jpg 1778.jpg 573.jpg 731.jpg 1187.jpg 207.jpg 71.jpg

283.txt,109.jpg 1973.jpg 1341.jpg 189.jpg 997.jpg 1766.jpg 195.jpg 1829.jpg 241.jpg 472.jpg 1054.jpg 1089.jpg 1784.jpg 804.jpg 1861.jpg 1747.jpg 1390.jpg 1934.jpg 327.jpg 1583.jpg

284.txt,1586.jpg 1019.jpg 385.jpg 759.jpg 1169.jpg 1805.jpg 854.jpg 1378.jpg 499.jpg 491.jpg 780.jpg 795.jpg 733.jpg 894.jpg 952.jpg 1964.jpg 467.jpg 707.jpg 827.jpg 1994.jpg

285.txt,369.jpg 1167.jpg 1827.jpg 1846.jpg 1304.jpg 466.jpg 1329.jpg 1137.jpg 1106.jpg 285.jpg 307.jpg 1860.jpg 270.jpg 1763.jpg 1.jpg 405.jpg 243.jpg 954.jpg 295.jpg 1502.jpg

286.txt,79.jpg 1161.jpg 1924.jpg 1202.jpg 1856.jpg 1782.jpg 1915.jpg 1046.jpg 1738.jpg 1384.jpg 1629.jpg 2.jpg 8

328.txt,101.jpg 70.jpg 964.jpg 210.jpg 498.jpg 744.jpg 921.jpg 534.jpg 512.jpg 514.jpg 1213.jpg 734.jpg 620.jpg 1400.jpg 1602.jpg 522.jpg 1715.jpg 1062.jpg 770.jpg 74.jpg

329.txt,1374.jpg 1683.jpg 1576.jpg 1417.jpg 1825.jpg 1267.jpg 830.jpg 966.jpg 1585.jpg 1117.jpg 164.jpg 1323.jpg 1756.jpg 1178.jpg 357.jpg 1618.jpg 851.jpg 1892.jpg 1631.jpg 41.jpg

330.txt,695.jpg 1889.jpg 641.jpg 1640.jpg 1775.jpg 909.jpg 1093.jpg 26.jpg 1215.jpg 686.jpg 825.jpg 752.jpg 731.jpg 267.jpg 989.jpg 1727.jpg 1859.jpg 1207.jpg 1140.jpg 494.jpg

331.txt,1033.jpg 1116.jpg 1665.jpg 1313.jpg 1340.jpg 1366.jpg 1716.jpg 1835.jpg 184.jpg 1475.jpg 1208.jpg 1499.jpg 818.jpg 1702.jpg 1574.jpg 696.jpg 323.jpg 1124.jpg 866.jpg 607.jpg

332.txt,5.jpg 572.jpg 261.jpg 1029.jpg 1959.jpg 23.jpg 1353.jpg 200.jpg 820.jpg 1006.jpg 1806.jpg 538.jpg 1049.jpg 1740.jpg 571.jpg 1645.jpg 927.jpg 1742.jpg 1408.jpg 1871.jpg

333.txt,65.jpg 751.jpg 1372.jpg 875.jpg 1091.jpg 1590.jpg 350.jpg 874.jpg 1619.jpg 1784.jpg 801.jpg 1861.jpg 

375.txt,947.jpg 978.jpg 434.jpg 1050.jpg 995.jpg 1804.jpg 1298.jpg 1263.jpg 1945.jpg 936.jpg 116.jpg 1384.jpg 939.jpg 1180.jpg 1069.jpg 256.jpg 1231.jpg 1262.jpg 1388.jpg 849.jpg

376.txt,1701.jpg 1790.jpg 16.jpg 582.jpg 1139.jpg 1352.jpg 1472.jpg 1216.jpg 655.jpg 402.jpg 1444.jpg 718.jpg 557.jpg 1660.jpg 262.jpg 429.jpg 489.jpg 1944.jpg 1613.jpg 1815.jpg

377.txt,1948.jpg 1336.jpg 1847.jpg 1004.jpg 837.jpg 1557.jpg 266.jpg 866.jpg 1622.jpg 1346.jpg 343.jpg 419.jpg 1787.jpg 823.jpg 1389.jpg 1817.jpg 464.jpg 1690.jpg 848.jpg 1031.jpg

378.txt,50.jpg 1286.jpg 1250.jpg 678.jpg 502.jpg 93.jpg 226.jpg 541.jpg 594.jpg 305.jpg 1350.jpg 599.jpg 92.jpg 1047.jpg 1018.jpg 1679.jpg 1410.jpg 723.jpg 698.jpg 1521.jpg

379.txt,1757.jpg 1753.jpg 562.jpg 1147.jpg 457.jpg 1628.jpg 191.jpg 1726.jpg 107.jpg 1381.jpg 1477.jpg 80.jpg 601.jpg 948.jpg 1516.jpg 645.jpg 1192.jpg 1195.jpg 198.jpg 529.jpg

380.txt,1115.jpg 1062.jpg 534.jpg 1602.jpg 988.jpg 713.jpg 507.jpg 380.jpg 536.jpg 1307.jpg 1633.jpg 1722.jp

422.txt,688.jpg 1012.jpg 853.jpg 1441.jpg 269.jpg 1623.jpg 1621.jpg 1984.jpg 128.jpg 151.jpg 544.jpg 721.jpg 87.jpg 1813.jpg 214.jpg 1364.jpg 906.jpg 1970.jpg 194.jpg 64.jpg

423.txt,1187.jpg 1893.jpg 214.jpg 1376.jpg 289.jpg 116.jpg 1936.jpg 493.jpg 128.jpg 1012.jpg 1620.jpg 1404.jpg 435.jpg 1765.jpg 1203.jpg 1400.jpg 1204.jpg 256.jpg 853.jpg 1715.jpg

424.txt,747.jpg 1026.jpg 1266.jpg 541.jpg 104.jpg 773.jpg 1420.jpg 235.jpg 1000.jpg 1044.jpg 1163.jpg 1047.jpg 502.jpg 58.jpg 1361.jpg 1271.jpg 293.jpg 1303.jpg 656.jpg 876.jpg

425.txt,1249.jpg 1270.jpg 1328.jpg 1961.jpg 1488.jpg 1285.jpg 168.jpg 1155.jpg 689.jpg 1085.jpg 685.jpg 627.jpg 987.jpg 448.jpg 1694.jpg 481.jpg 409.jpg 1900.jpg 1239.jpg 794.jpg

426.txt,770.jpg 432.jpg 1231.jpg 732.jpg 712.jpg 1900.jpg 413.jpg 549.jpg 1123.jpg 256.jpg 1821.jpg 899.jpg 279.jpg 614.jpg 1795.jpg 1363.jpg 1620.jpg 418.jpg 1262.jpg 1862.jpg

427.txt,1164.jpg 398.jpg 399.jpg 1508.jpg 938.jpg 680.jpg 1008.jpg 748.jpg 646.jpg 962.jpg 304.jpg 1605.jpg 

469.txt,1365.jpg 266.jpg 1525.jpg 1389.jpg 1611.jpg 579.jpg 1336.jpg 1690.jpg 1557.jpg 1896.jpg 1644.jpg 848.jpg 24.jpg 1010.jpg 982.jpg 1179.jpg 1013.jpg 1901.jpg 420.jpg 343.jpg

470.txt,363.jpg 499.jpg 706.jpg 315.jpg 1586.jpg 1019.jpg 952.jpg 1805.jpg 827.jpg 1378.jpg 385.jpg 1241.jpg 780.jpg 1058.jpg 578.jpg 733.jpg 1964.jpg 1994.jpg 491.jpg 1356.jpg

471.txt,247.jpg 1507.jpg 668.jpg 6.jpg 1369.jpg 149.jpg 1999.jpg 738.jpg 1476.jpg 1207.jpg 80.jpg 1141.jpg 527.jpg 482.jpg 967.jpg 314.jpg 1334.jpg 1727.jpg 220.jpg 1802.jpg

472.txt,1802.jpg 384.jpg 410.jpg 951.jpg 1905.jpg 1624.jpg 807.jpg 455.jpg 1491.jpg 805.jpg 1890.jpg 627.jpg 1711.jpg 1132.jpg 143.jpg 728.jpg 1583.jpg 1932.jpg 1903.jpg 989.jpg

473.txt,1278.jpg 517.jpg 1156.jpg 795.jpg 315.jpg 1099.jpg 1977.jpg 1688.jpg 1252.jpg 746.jpg 470.jpg 890.jpg 1863.jpg 298.jpg 562.jpg 622.jpg 1828.jpg 963.jpg 363.jpg 713.jpg

474.txt,85.jpg 148.jpg 986.jpg 1767.jpg 1353.jpg 802.jpg 201.jpg 618.jpg 1173.jpg 1612.jpg 325.jpg 1740.jpg 17

516.txt,15.jpg 822.jpg 1987.jpg 134.jpg 768.jpg 821.jpg 1290.jpg 183.jpg 1190.jpg 384.jpg 448.jpg 954.jpg 1085.jpg 934.jpg 689.jpg 1363.jpg 1711.jpg 1877.jpg 1589.jpg 1469.jpg

517.txt,1293.jpg 1014.jpg 961.jpg 1939.jpg 423.jpg 1495.jpg 876.jpg 490.jpg 890.jpg 1649.jpg 1419.jpg 889.jpg 83.jpg 1332.jpg 11.jpg 855.jpg 1531.jpg 1608.jpg 119.jpg 596.jpg

518.txt,759.jpg 795.jpg 385.jpg 1169.jpg 1019.jpg 1805.jpg 780.jpg 952.jpg 499.jpg 1274.jpg 733.jpg 827.jpg 1058.jpg 578.jpg 1964.jpg 454.jpg 491.jpg 854.jpg 707.jpg 1545.jpg

519.txt,1497.jpg 961.jpg 1925.jpg 83.jpg 1200.jpg 11.jpg 596.jpg 1293.jpg 1939.jpg 1531.jpg 787.jpg 653.jpg 889.jpg 1419.jpg 1163.jpg 855.jpg 424.jpg 293.jpg 1266.jpg 1303.jpg

520.txt,1085.jpg 409.jpg 448.jpg 987.jpg 1285.jpg 627.jpg 415.jpg 1694.jpg 168.jpg 1223.jpg 689.jpg 1249.jpg 91.jpg 1488.jpg 1239.jpg 1961.jpg 384.jpg 1155.jpg 183.jpg 528.jpg

521.txt,751.jpg 1590.jpg 1784.jpg 875.jpg 65.jpg 874.jpg 1619.jpg 1861.jpg 1091.jpg 851.jpg 1908.jpg 350.jpg 801.jpg 

563.txt,620.jpg 1307.jpg 439.jpg 964.jpg 210.jpg 1434.jpg 921.jpg 70.jpg 1213.jpg 440.jpg 1952.jpg 498.jpg 1235.jpg 1558.jpg 744.jpg 64.jpg 1376.jpg 1671.jpg 69.jpg 289.jpg

564.txt,1520.jpg 684.jpg 1715.jpg 1633.jpg 1406.jpg 536.jpg 1732.jpg 1602.jpg 1036.jpg 1722.jpg 101.jpg 74.jpg 1074.jpg 1445.jpg 1870.jpg 522.jpg 1062.jpg 1974.jpg 1042.jpg 1721.jpg

565.txt,1811.jpg 1563.jpg 1537.jpg 1079.jpg 694.jpg 123.jpg 819.jpg 1869.jpg 1506.jpg 1445.jpg 1732.jpg 1722.jpg 1870.jpg 1246.jpg 1681.jpg 945.jpg 684.jpg 1036.jpg 1406.jpg 513.jpg

566.txt,689.jpg 448.jpg 1694.jpg 1085.jpg 1961.jpg 1285.jpg 1488.jpg 1249.jpg 987.jpg 91.jpg 794.jpg 409.jpg 627.jpg 168.jpg 1223.jpg 685.jpg 1270.jpg 528.jpg 1302.jpg 1328.jpg

567.txt,1004.jpg 1787.jpg 521.jpg 420.jpg 343.jpg 1010.jpg 864.jpg 1706.jpg 866.jpg 982.jpg 1690.jpg 1611.jpg 98.jpg 1179.jpg 848.jpg 653.jpg 464.jpg 891.jpg 405.jpg 1336.jpg

568.txt,138.jpg 633.jpg 964.jpg 290.jpg 609.jpg 1330.jpg 1504.jpg 210.jpg 1960.jpg 192.jpg 739.jpg 153.jpg

609.txt,633.jpg 192.jpg 609.jpg 1330.jpg 1665.jpg 290.jpg 981.jpg 860.jpg 1950.jpg 768.jpg 1421.jpg 739.jpg 1574.jpg 1004.jpg 1720.jpg 1084.jpg 1787.jpg 821.jpg 1987.jpg 979.jpg

610.txt,558.jpg 1829.jpg 1244.jpg 195.jpg 1947.jpg 1884.jpg 327.jpg 1390.jpg 1583.jpg 472.jpg 277.jpg 241.jpg 551.jpg 283.jpg 1604.jpg 248.jpg 1747.jpg 477.jpg 1766.jpg 1104.jpg

611.txt,1732.jpg 1445.jpg 1722.jpg 1042.jpg 1870.jpg 684.jpg 536.jpg 1633.jpg 1036.jpg 1406.jpg 1681.jpg 1206.jpg 1520.jpg 1602.jpg 1074.jpg 1972.jpg 1721.jpg 565.jpg 584.jpg 1974.jpg

612.txt,340.jpg 298.jpg 173.jpg 1670.jpg 62.jpg 919.jpg 612.jpg 896.jpg 1951.jpg 1872.jpg 45.jpg 1188.jpg 1536.jpg 9.jpg 1260.jpg 963.jpg 656.jpg 1863.jpg 337.jpg 242.jpg

613.txt,442.jpg 831.jpg 856.jpg 1985.jpg 1399.jpg 503.jpg 1259.jpg 461.jpg 100.jpg 1034.jpg 1963.jpg 974.jpg 1908.jpg 610.jpg 125.jpg 1386.jpg 1869.jpg 341.jpg 946.jpg 801.jpg

614.txt,536.jpg 1732.jpg 1042.jpg 1602.jpg 1722.jpg 1406.jpg 1445.jpg 684.jpg 1633.jpg 1062.jpg 1715.jpg 152

656.txt,1019.jpg 827.jpg 1058.jpg 780.jpg 499.jpg 1586.jpg 1378.jpg 578.jpg 385.jpg 1964.jpg 707.jpg 1805.jpg 1994.jpg 278.jpg 324.jpg 706.jpg 733.jpg 1545.jpg 1274.jpg 1554.jpg

657.txt,169.jpg 160.jpg 1039.jpg 657.jpg 104.jpg 1192.jpg 553.jpg 58.jpg 1134.jpg 571.jpg 495.jpg 331.jpg 76.jpg 1196.jpg 816.jpg 1807.jpg 1110.jpg 1163.jpg 815.jpg 1726.jpg

658.txt,95.jpg 1166.jpg 216.jpg 1945.jpg 902.jpg 88.jpg 199.jpg 1180.jpg 375.jpg 164.jpg 658.jpg 1749.jpg 1804.jpg 453.jpg 36.jpg 711.jpg 939.jpg 507.jpg 1262.jpg 1076.jpg

659.txt,276.jpg 1324.jpg 548.jpg 1299.jpg 1221.jpg 4.jpg 1569.jpg 1951.jpg 18.jpg 1578.jpg 863.jpg 1233.jpg 919.jpg 517.jpg 1881.jpg 9.jpg 1205.jpg 380.jpg 1159.jpg 651.jpg

660.txt,18.jpg 1324.jpg 4.jpg 548.jpg 383.jpg 1566.jpg 1299.jpg 694.jpg 980.jpg 1537.jpg 1670.jpg 1300.jpg 1593.jpg 1975.jpg 1323.jpg 517.jpg 722.jpg 97.jpg 1001.jpg 988.jpg

661.txt,1716.jpg 879.jpg 705.jpg 1499.jpg 981.jpg 866.jpg 727.jpg 1383.jpg 561.jpg 1817.jpg 24.jpg 1124.jpg 63.jpg 539.jpg 7

703.txt,247.jpg 668.jpg 6.jpg 1917.jpg 1141.jpg 1999.jpg 1477.jpg 1177.jpg 1507.jpg 967.jpg 1494.jpg 1102.jpg 80.jpg 1334.jpg 149.jpg 482.jpg 738.jpg 1369.jpg 1158.jpg 1820.jpg

704.txt,743.jpg 573.jpg 1128.jpg 207.jpg 884.jpg 824.jpg 750.jpg 817.jpg 1358.jpg 1595.jpg 441.jpg 1552.jpg 1731.jpg 72.jpg 1418.jpg 1370.jpg 122.jpg 1620.jpg 1101.jpg 1301.jpg

705.txt,1533.jpg 492.jpg 1693.jpg 1335.jpg 814.jpg 1426.jpg 330.jpg 703.jpg 1118.jpg 1943.jpg 771.jpg 846.jpg 630.jpg 887.jpg 1830.jpg 51.jpg 274.jpg 1429.jpg 1254.jpg 526.jpg

706.txt,1854.jpg 438.jpg 1241.jpg 952.jpg 706.jpg 1586.jpg 1007.jpg 1899.jpg 1545.jpg 559.jpg 1019.jpg 491.jpg 1805.jpg 1378.jpg 385.jpg 1898.jpg 1437.jpg 1496.jpg 1294.jpg 578.jpg

707.txt,1660.jpg 1607.jpg 1216.jpg 771.jpg 1874.jpg 1854.jpg 1274.jpg 1320.jpg 1710.jpg 1701.jpg 1991.jpg 1815.jpg 385.jpg 1472.jpg 491.jpg 438.jpg 1855.jpg 1805.jpg 707.jpg 1545.jpg

708.txt,673.jpg 1813.jpg 1623.jpg 1154.jpg 1401.jpg 1551.jpg 439.jpg 544.jpg 1297.jpg 1970.jpg 214.jp

750.txt,1310.jpg 1468.jpg 1093.jpg 1634.jpg 752.jpg 652.jpg 1368.jpg 1712.jpg 585.jpg 1326.jpg 460.jpg 1357.jpg 701.jpg 376.jpg 715.jpg 433.jpg 1128.jpg 884.jpg 145.jpg 1288.jpg

751.txt,1340.jpg 649.jpg 1208.jpg 1421.jpg 1030.jpg 763.jpg 1475.jpg 1059.jpg 607.jpg 1437.jpg 1574.jpg 184.jpg 1366.jpg 860.jpg 1665.jpg 1702.jpg 1648.jpg 1084.jpg 1027.jpg 1784.jpg

752.txt,104.jpg 1795.jpg 1671.jpg 1564.jpg 1407.jpg 782.jpg 58.jpg 1276.jpg 614.jpg 1026.jpg 1468.jpg 704.jpg 1451.jpg 1231.jpg 770.jpg 1986.jpg 199.jpg 116.jpg 1818.jpg 1368.jpg

753.txt,836.jpg 800.jpg 1601.jpg 457.jpg 1513.jpg 397.jpg 1035.jpg 107.jpg 1689.jpg 589.jpg 1486.jpg 1313.jpg 390.jpg 1143.jpg 835.jpg 1121.jpg 1609.jpg 1220.jpg 23.jpg 1865.jpg

754.txt,1693.jpg 1991.jpg 771.jpg 492.jpg 51.jpg 814.jpg 1335.jpg 703.jpg 1874.jpg 526.jpg 1943.jpg 1426.jpg 846.jpg 274.jpg 1830.jpg 1660.jpg 330.jpg 630.jpg 1913.jpg 643.jpg

755.txt,980.jpg 97.jpg 408.jpg 254.jpg 915.jpg 755.jpg 43.jpg 909.jpg 229.jpg 1651.jpg 1060.jpg 1493.

797.txt,314.jpg 6.jpg 1141.jpg 968.jpg 80.jpg 482.jpg 1143.jpg 818.jpg 457.jpg 247.jpg 527.jpg 1477.jpg 1507.jpg 1102.jpg 198.jpg 1516.jpg 107.jpg 1820.jpg 1494.jpg 1313.jpg

798.txt,353.jpg 1420.jpg 594.jpg 742.jpg 1105.jpg 502.jpg 93.jpg 292.jpg 721.jpg 1131.jpg 1521.jpg 1047.jpg 255.jpg 375.jpg 1698.jpg 305.jpg 723.jpg 1343.jpg 359.jpg 942.jpg

799.txt,685.jpg 1857.jpg 1961.jpg 1270.jpg 1249.jpg 1488.jpg 689.jpg 1694.jpg 528.jpg 1328.jpg 481.jpg 1900.jpg 168.jpg 1239.jpg 987.jpg 1085.jpg 1285.jpg 409.jpg 907.jpg 1949.jpg

800.txt,1486.jpg 895.jpg 645.jpg 90.jpg 1920.jpg 1978.jpg 799.jpg 325.jpg 397.jpg 243.jpg 800.jpg 75.jpg 1147.jpg 639.jpg 1799.jpg 668.jpg 1750.jpg 1021.jpg 162.jpg 1511.jpg

801.txt,804.jpg 1973.jpg 1428.jpg 869.jpg 57.jpg 350.jpg 1741.jpg 1880.jpg 997.jpg 237.jpg 1669.jpg 757.jpg 1784.jpg 109.jpg 1650.jpg 1911.jpg 613.jpg 282.jpg 1054.jpg 874.jpg

802.txt,990.jpg 97.jpg 1493.jpg 993.jpg 1405.jpg 254.jpg 1651.jpg 980.jpg 43.jpg 1060.jpg 755.jpg 303.jpg 790.jpg 166

844.txt,1004.jpg 669.jpg 1690.jpg 420.jpg 1611.jpg 1033.jpg 866.jpg 1787.jpg 1883.jpg 24.jpg 844.jpg 328.jpg 292.jpg 1525.jpg 579.jpg 1365.jpg 982.jpg 1644.jpg 459.jpg 1013.jpg

845.txt,1126.jpg 1879.jpg 344.jpg 1162.jpg 374.jpg 747.jpg 1620.jpg 203.jpg 1637.jpg 960.jpg 1379.jpg 1361.jpg 1778.jpg 1765.jpg 770.jpg 506.jpg 26.jpg 207.jpg 28.jpg 1070.jpg

846.txt,210.jpg 498.jpg 964.jpg 921.jpg 1213.jpg 620.jpg 52.jpg 70.jpg 1434.jpg 734.jpg 69.jpg 1307.jpg 138.jpg 914.jpg 744.jpg 1591.jpg 1913.jpg 1746.jpg 1886.jpg 534.jpg

847.txt,931.jpg 319.jpg 1546.jpg 123.jpg 341.jpg 697.jpg 1027.jpg 443.jpg 184.jpg 856.jpg 1648.jpg 603.jpg 1562.jpg 901.jpg 860.jpg 1869.jpg 1962.jpg 1392.jpg 1142.jpg 1229.jpg

848.txt,471.jpg 1614.jpg 825.jpg 1207.jpg 1321.jpg 1802.jpg 731.jpg 26.jpg 1889.jpg 641.jpg 1145.jpg 960.jpg 1727.jpg 1215.jpg 155.jpg 249.jpg 1903.jpg 971.jpg 1532.jpg 1101.jpg

849.txt,1826.jpg 213.jpg 760.jpg 1702.jpg 364.jpg 1277.jpg 10.jpg 451.jpg 860.jpg 1775.jpg 1657.jpg 478.jpg 1448.jp

891.txt,374.jpg 1415.jpg 1215.jpg 26.jpg 1126.jpg 1778.jpg 750.jpg 207.jpg 1765.jpg 817.jpg 960.jpg 1097.jpg 1430.jpg 1070.jpg 824.jpg 1318.jpg 1552.jpg 1620.jpg 471.jpg 1486.jpg

892.txt,1593.jpg 1743.jpg 1136.jpg 18.jpg 1975.jpg 1280.jpg 359.jpg 672.jpg 1924.jpg 1238.jpg 595.jpg 383.jpg 736.jpg 1131.jpg 255.jpg 722.jpg 181.jpg 1324.jpg 1718.jpg 292.jpg

893.txt,366.jpg 816.jpg 657.jpg 104.jpg 1015.jpg 533.jpg 1055.jpg 11.jpg 178.jpg 890.jpg 1407.jpg 1014.jpg 1843.jpg 782.jpg 1564.jpg 638.jpg 1163.jpg 299.jpg 1958.jpg 1549.jpg

894.txt,1383.jpg 669.jpg 1499.jpg 705.jpg 953.jpg 1720.jpg 545.jpg 1107.jpg 372.jpg 445.jpg 769.jpg 1987.jpg 1033.jpg 1242.jpg 117.jpg 561.jpg 338.jpg 322.jpg 1627.jpg 844.jpg

895.txt,180.jpg 1460.jpg 962.jpg 399.jpg 680.jpg 1605.jpg 1392.jpg 603.jpg 938.jpg 1508.jpg 1483.jpg 1008.jpg 783.jpg 1853.jpg 398.jpg 1898.jpg 867.jpg 1739.jpg 443.jpg 748.jpg

896.txt,573.jpg 743.jpg 1418.jpg 207.jpg 750.jpg 1128.jpg 824.jpg 18.jpg 441.jpg 884.jpg 1101.jpg 1595.jpg 198

937.txt,1116.jpg 835.jpg 920.jpg 1807.jpg 463.jpg 1689.jpg 508.jpg 738.jpg 1835.jpg 968.jpg 331.jpg 1714.jpg 1143.jpg 527.jpg 169.jpg 682.jpg 1325.jpg 23.jpg 818.jpg 538.jpg

938.txt,1515.jpg 1164.jpg 398.jpg 1853.jpg 748.jpg 349.jpg 680.jpg 646.jpg 1605.jpg 938.jpg 1739.jpg 1460.jpg 399.jpg 1508.jpg 783.jpg 642.jpg 1270.jpg 180.jpg 234.jpg 1536.jpg

939.txt,1363.jpg 1123.jpg 1775.jpg 54.jpg 1711.jpg 1708.jpg 1022.jpg 1290.jpg 1210.jpg 1362.jpg 1875.jpg 1703.jpg 591.jpg 1056.jpg 1832.jpg 886.jpg 1616.jpg 560.jpg 1190.jpg 1263.jpg

940.txt,1297.jpg 777.jpg 439.jpg 1621.jpg 268.jpg 853.jpg 1970.jpg 544.jpg 64.jpg 673.jpg 1364.jpg 1012.jpg 1676.jpg 1984.jpg 87.jpg 929.jpg 194.jpg 1441.jpg 214.jpg 128.jpg

941.txt,1231.jpg 1679.jpg 562.jpg 1816.jpg 495.jpg 1620.jpg 770.jpg 1187.jpg 1726.jpg 726.jpg 1076.jpg 199.jpg 1092.jpg 12.jpg 152.jpg 1215.jpg 1381.jpg 1765.jpg 742.jpg 413.jpg

942.txt,9.jpg 271.jpg 359.jpg 1549.jpg 281.jpg 1131.jpg 255.jpg 1105.jpg 1670.jpg 1535.jpg 736.jpg 1879.jpg 9

984.txt,54.jpg 886.jpg 1703.jpg 1363.jpg 1775.jpg 1056.jpg 1448.jpg 1362.jpg 1616.jpg 1832.jpg 1534.jpg 1022.jpg 591.jpg 1210.jpg 1469.jpg 1290.jpg 1711.jpg 1123.jpg 1078.jpg 494.jpg

985.txt,896.jpg 722.jpg 1629.jpg 1915.jpg 1240.jpg 1838.jpg 1247.jpg 831.jpg 1005.jpg 1202.jpg 4.jpg 1324.jpg 1670.jpg 1986.jpg 18.jpg 507.jpg 766.jpg 1924.jpg 297.jpg 1238.jpg

986.txt,1953.jpg 320.jpg 59.jpg 393.jpg 325.jpg 85.jpg 1463.jpg 452.jpg 1997.jpg 779.jpg 1455.jpg 188.jpg 432.jpg 618.jpg 71.jpg 1767.jpg 1996.jpg 1450.jpg 1125.jpg 944.jpg

987.txt,248.jpg 448.jpg 277.jpg 689.jpg 1694.jpg 1085.jpg 1583.jpg 472.jpg 1089.jpg 1285.jpg 1290.jpg 775.jpg 183.jpg 91.jpg 1249.jpg 168.jpg 987.jpg 1766.jpg 1711.jpg 1961.jpg

988.txt,1249.jpg 1961.jpg 689.jpg 1694.jpg 1488.jpg 1285.jpg 448.jpg 1085.jpg 1270.jpg 168.jpg 987.jpg 794.jpg 1155.jpg 685.jpg 1328.jpg 1900.jpg 1290.jpg 409.jpg 1857.jpg 627.jpg

989.txt,974.jpg 1869.jpg 123.jpg 831.jpg 610.jpg 100.jpg 401.jpg 819.jpg 1537.jpg 1546.jpg 1548.jpg 1751.

1030.txt,1950.jpg 633.jpg 1330.jpg 1023.jpg 192.jpg 1665.jpg 1960.jpg 568.jpg 1622.jpg 768.jpg 981.jpg 739.jpg 1475.jpg 175.jpg 1059.jpg 609.jpg 1538.jpg 579.jpg 904.jpg 724.jpg

1031.txt,837.jpg 1600.jpg 1557.jpg 1004.jpg 1133.jpg 343.jpg 531.jpg 1336.jpg 1567.jpg 1179.jpg 1031.jpg 1272.jpg 266.jpg 496.jpg 826.jpg 923.jpg 1847.jpg 1902.jpg 848.jpg 134.jpg

1032.txt,373.jpg 688.jpg 1623.jpg 1082.jpg 37.jpg 1127.jpg 1535.jpg 1350.jpg 1441.jpg 1416.jpg 1203.jpg 151.jpg 422.jpg 269.jpg 1012.jpg 289.jpg 46.jpg 1676.jpg 28.jpg 194.jpg

1033.txt,1368.jpg 1176.jpg 1536.jpg 174.jpg 1902.jpg 1149.jpg 810.jpg 1634.jpg 223.jpg 19.jpg 1133.jpg 340.jpg 1051.jpg 1928.jpg 1468.jpg 1976.jpg 1505.jpg 1310.jpg 1427.jpg 821.jpg

1034.txt,51.jpg 771.jpg 492.jpg 814.jpg 1693.jpg 1335.jpg 846.jpg 1991.jpg 1874.jpg 330.jpg 526.jpg 1943.jpg 1660.jpg 703.jpg 1830.jpg 630.jpg 1426.jpg 1837.jpg 643.jpg 274.jpg

1035.txt,1381.jpg 1231.jpg 1035.jpg 562.jpg 1795.jpg 1395.jpg 199.jpg 1024.jpg 1407.jpg 435.jpg 1816.j

1076.txt,152.jpg 772.jpg 435.jpg 729.jpg 1395.jpg 949.jpg 562.jpg 1816.jpg 601.jpg 388.jpg 58.jpg 281.jpg 1381.jpg 776.jpg 657.jpg 1391.jpg 865.jpg 1856.jpg 1726.jpg 801.jpg

1077.txt,1879.jpg 998.jpg 1430.jpg 1696.jpg 82.jpg 747.jpg 1816.jpg 1620.jpg 541.jpg 413.jpg 203.jpg 729.jpg 1409.jpg 374.jpg 275.jpg 772.jpg 1552.jpg 20.jpg 604.jpg 1342.jpg

1078.txt,1826.jpg 1696.jpg 1775.jpg 932.jpg 1098.jpg 1362.jpg 46.jpg 1888.jpg 10.jpg 886.jpg 1568.jpg 37.jpg 1534.jpg 1469.jpg 213.jpg 451.jpg 54.jpg 1832.jpg 1711.jpg 1127.jpg

1079.txt,568.jpg 633.jpg 192.jpg 1348.jpg 1057.jpg 1330.jpg 290.jpg 103.jpg 1960.jpg 739.jpg 1919.jpg 609.jpg 828.jpg 981.jpg 1383.jpg 1567.jpg 1962.jpg 531.jpg 923.jpg 724.jpg

1080.txt,1746.jpg 1504.jpg 1646.jpg 670.jpg 880.jpg 1127.jpg 1599.jpg 1610.jpg 78.jpg 1373.jpg 1577.jpg 1710.jpg 994.jpg 37.jpg 346.jpg 989.jpg 1786.jpg 914.jpg 1274.jpg 1224.jpg

1081.txt,1128.jpg 884.jpg 1357.jpg 145.jpg 1301.jpg 715.jpg 212.jpg 1595.jpg 824.jpg 1288.jpg 1189.jpg 122.jpg 13

1122.txt,1888.jpg 1118.jpg 814.jpg 1218.jpg 1693.jpg 1913.jpg 846.jpg 354.jpg 1696.jpg 1533.jpg 20.jpg 137.jpg 358.jpg 46.jpg 492.jpg 887.jpg 703.jpg 1943.jpg 1830.jpg 389.jpg

1123.txt,414.jpg 217.jpg 1151.jpg 1289.jpg 489.jpg 156.jpg 648.jpg 996.jpg 1265.jpg 555.jpg 1020.jpg 33.jpg 1096.jpg 458.jpg 1377.jpg 402.jpg 1333.jpg 1584.jpg 910.jpg 897.jpg

1124.txt,545.jpg 1033.jpg 1627.jpg 1490.jpg 1545.jpg 707.jpg 1378.jpg 705.jpg 1971.jpg 732.jpg 1349.jpg 117.jpg 291.jpg 953.jpg 1124.jpg 690.jpg 328.jpg 647.jpg 396.jpg 445.jpg

1125.txt,246.jpg 1420.jpg 1047.jpg 723.jpg 202.jpg 1521.jpg 599.jpg 594.jpg 226.jpg 50.jpg 502.jpg 94.jpg 432.jpg 1250.jpg 1286.jpg 1819.jpg 93.jpg 235.jpg 678.jpg 353.jpg

1126.txt,1765.jpg 960.jpg 1126.jpg 374.jpg 1778.jpg 506.jpg 344.jpg 438.jpg 1653.jpg 1274.jpg 1415.jpg 207.jpg 441.jpg 1620.jpg 770.jpg 1954.jpg 1101.jpg 750.jpg 1879.jpg 26.jpg

1127.txt,688.jpg 194.jpg 128.jpg 269.jpg 1203.jpg 1012.jpg 1621.jpg 1441.jpg 64.jpg 544.jpg 1364.jpg 268.jpg 1676.jp

1168.txt,128.jpg 1364.jpg 1621.jpg 853.jpg 269.jpg 1012.jpg 688.jpg 1813.jpg 64.jpg 708.jpg 1235.jpg 544.jpg 1984.jpg 1473.jpg 194.jpg 254.jpg 777.jpg 1970.jpg 1623.jpg 439.jpg

1169.txt,888.jpg 682.jpg 587.jpg 1828.jpg 1006.jpg 1737.jpg 411.jpg 1029.jpg 1615.jpg 1873.jpg 1667.jpg 144.jpg 1977.jpg 1914.jpg 1554.jpg 1809.jpg 1138.jpg 1988.jpg 1353.jpg 1891.jpg

1170.txt,32.jpg 787.jpg 295.jpg 287.jpg 1846.jpg 1260.jpg 270.jpg 612.jpg 1304.jpg 1728.jpg 407.jpg 466.jpg 405.jpg 1106.jpg 1827.jpg 1762.jpg 1137.jpg 9.jpg 1497.jpg 1188.jpg

1171.txt,152.jpg 12.jpg 1481.jpg 7.jpg 1110.jpg 1937.jpg 1679.jpg 653.jpg 164.jpg 1342.jpg 1535.jpg 1076.jpg 1726.jpg 942.jpg 1729.jpg 453.jpg 776.jpg 421.jpg 1509.jpg 580.jpg

1172.txt,1726.jpg 1110.jpg 152.jpg 12.jpg 1679.jpg 601.jpg 726.jpg 495.jpg 1481.jpg 877.jpg 1395.jpg 948.jpg 169.jpg 949.jpg 1535.jpg 1120.jpg 626.jpg 1516.jpg 76.jpg 1381.jpg

1173.txt,1116.jpg 1313.jpg 52.jpg 818.jpg 498.jpg 1173.jpg 835.jpg 620.jpg 1143.jpg 1733.jpg 77.jpg 1601.j

1214.txt,549.jpg 1795.jpg 500.jpg 1821.jpg 870.jpg 1678.jpg 640.jpg 1391.jpg 1567.jpg 147.jpg 171.jpg 410.jpg 1560.jpg 1253.jpg 701.jpg 1431.jpg 337.jpg 1156.jpg 1133.jpg 1091.jpg

1215.txt,1215.jpg 26.jpg 1207.jpg 1145.jpg 1889.jpg 1097.jpg 471.jpg 1727.jpg 267.jpg 1404.jpg 1088.jpg 1187.jpg 960.jpg 989.jpg 1070.jpg 825.jpg 1620.jpg 484.jpg 1734.jpg 1816.jpg

1216.txt,759.jpg 780.jpg 385.jpg 1169.jpg 1545.jpg 499.jpg 952.jpg 1019.jpg 733.jpg 1964.jpg 1058.jpg 491.jpg 454.jpg 827.jpg 1274.jpg 578.jpg 324.jpg 707.jpg 894.jpg 909.jpg

1217.txt,719.jpg 1622.jpg 1918.jpg 464.jpg 1948.jpg 1261.jpg 1346.jpg 103.jpg 1847.jpg 1443.jpg 419.jpg 1618.jpg 245.jpg 266.jpg 1037.jpg 1031.jpg 1348.jpg 531.jpg 727.jpg 113.jpg

1218.txt,961.jpg 1293.jpg 1939.jpg 1026.jpg 46.jpg 293.jpg 490.jpg 11.jpg 855.jpg 104.jpg 281.jpg 889.jpg 1495.jpg 424.jpg 1683.jpg 519.jpg 1419.jpg 1014.jpg 1531.jpg 423.jpg

1219.txt,1584.jpg 767.jpg 1020.jpg 33.jpg 1153.jpg 1758.jpg 1333.jpg 1940.jpg 1096.jpg 1289.jpg 217.jpg 

1260.txt,596.jpg 1293.jpg 889.jpg 490.jpg 1939.jpg 855.jpg 1531.jpg 1419.jpg 1332.jpg 961.jpg 1687.jpg 520.jpg 876.jpg 533.jpg 1649.jpg 1495.jpg 1303.jpg 424.jpg 293.jpg 1026.jpg

1261.txt,1684.jpg 806.jpg 1626.jpg 1478.jpg 1245.jpg 1083.jpg 1780.jpg 935.jpg 396.jpg 681.jpg 301.jpg 1777.jpg 1268.jpg 419.jpg 1792.jpg 232.jpg 727.jpg 1622.jpg 1667.jpg 1918.jpg

1262.txt,614.jpg 1886.jpg 940.jpg 20.jpg 1400.jpg 1118.jpg 1818.jpg 46.jpg 554.jpg 562.jpg 1913.jpg 1700.jpg 1696.jpg 630.jpg 274.jpg 1426.jpg 1092.jpg 354.jpg 52.jpg 570.jpg

1263.txt,685.jpg 1488.jpg 1249.jpg 1961.jpg 168.jpg 1900.jpg 1155.jpg 689.jpg 1285.jpg 1328.jpg 1270.jpg 1085.jpg 1239.jpg 481.jpg 1694.jpg 627.jpg 448.jpg 528.jpg 1857.jpg 987.jpg

1264.txt,1190.jpg 183.jpg 1290.jpg 560.jpg 1711.jpg 384.jpg 91.jpg 1875.jpg 1210.jpg 1832.jpg 1223.jpg 1534.jpg 1363.jpg 54.jpg 1123.jpg 1022.jpg 932.jpg 1703.jpg 415.jpg 1469.jpg

1265.txt,716.jpg 1128.jpg 884.jpg 1357.jpg 1189.jpg 824.jpg 1301.jpg 933.jpg 145.jpg 212.jpg 1552.j

1306.txt,349.jpg 398.jpg 1008.jpg 1164.jpg 1211.jpg 680.jpg 1392.jpg 1508.jpg 1605.jpg 1460.jpg 748.jpg 63.jpg 1953.jpg 1898.jpg 677.jpg 1528.jpg 1853.jpg 180.jpg 938.jpg 661.jpg

1307.txt,52.jpg 1591.jpg 1433.jpg 51.jpg 1118.jpg 1888.jpg 1913.jpg 1926.jpg 1693.jpg 526.jpg 846.jpg 914.jpg 814.jpg 1296.jpg 389.jpg 1218.jpg 1335.jpg 1355.jpg 370.jpg 1426.jpg

1308.txt,668.jpg 1177.jpg 1141.jpg 1184.jpg 738.jpg 968.jpg 1999.jpg 1807.jpg 163.jpg 169.jpg 1820.jpg 1114.jpg 1147.jpg 247.jpg 1143.jpg 107.jpg 1979.jpg 1039.jpg 139.jpg 1615.jpg

1309.txt,208.jpg 1674.jpg 1618.jpg 1864.jpg 1833.jpg 310.jpg 1931.jpg 1987.jpg 1538.jpg 111.jpg 1277.jpg 1556.jpg 84.jpg 561.jpg 911.jpg 1783.jpg 1717.jpg 1484.jpg 1512.jpg 1309.jpg

1310.txt,195.jpg 1244.jpg 558.jpg 1829.jpg 1666.jpg 277.jpg 1390.jpg 1884.jpg 327.jpg 1583.jpg 1747.jpg 241.jpg 1766.jpg 551.jpg 472.jpg 1947.jpg 1310.jpg 248.jpg 1104.jpg 1186.jpg

1311.txt,982.jpg 669.jpg 1690.jpg 1611.jpg 1336.jpg 864.jpg 459.jpg 343.jpg 1179.jpg 1644.jpg

1352.txt,1465.jpg 996.jpg 1020.jpg 1584.jpg 217.jpg 1275.jpg 718.jpg 339.jpg 262.jpg 908.jpg 1289.jpg 414.jpg 1333.jpg 458.jpg 489.jpg 897.jpg 583.jpg 1515.jpg 1151.jpg 1655.jpg

1353.txt,396.jpg 1378.jpg 707.jpg 291.jpg 324.jpg 1007.jpg 1805.jpg 278.jpg 1349.jpg 1019.jpg 578.jpg 1545.jpg 780.jpg 1422.jpg 491.jpg 818.jpg 1994.jpg 1550.jpg 1256.jpg 385.jpg

1354.txt,560.jpg 886.jpg 1832.jpg 1534.jpg 1448.jpg 932.jpg 1703.jpg 54.jpg 1056.jpg 1775.jpg 470.jpg 183.jpg 1078.jpg 1469.jpg 591.jpg 1190.jpg 10.jpg 1362.jpg 1210.jpg 1432.jpg

1355.txt,156.jpg 655.jpg 555.jpg 897.jpg 910.jpg 1660.jpg 1289.jpg 259.jpg 1151.jpg 1312.jpg 1444.jpg 217.jpg 1855.jpg 1275.jpg 1582.jpg 718.jpg 996.jpg 489.jpg 1815.jpg 486.jpg

1356.txt,1059.jpg 1421.jpg 649.jpg 1084.jpg 1840.jpg 1208.jpg 1030.jpg 1366.jpg 1471.jpg 1854.jpg 1340.jpg 1665.jpg 904.jpg 763.jpg 696.jpg 1437.jpg 1724.jpg 1378.jpg 186.jpg 1023.jpg

1357.txt,1468.jpg 1731.jpg 1634.jpg 1288.jpg 1310.jpg 1345.jpg 72.jpg 716.jpg 203.jpg 1152.jpg 13

1398.txt,1701.jpg 1275.jpg 1444.jpg 910.jpg 908.jpg 16.jpg 996.jpg 897.jpg 262.jpg 535.jpg 718.jpg 217.jpg 1096.jpg 1020.jpg 489.jpg 1458.jpg 623.jpg 259.jpg 156.jpg 1855.jpg

1399.txt,143.jpg 624.jpg 1491.jpg 1095.jpg 1905.jpg 954.jpg 1932.jpg 1841.jpg 1686.jpg 410.jpg 1860.jpg 798.jpg 1764.jpg 1449.jpg 1890.jpg 1763.jpg 857.jpg 1157.jpg 987.jpg 455.jpg

1400.txt,620.jpg 498.jpg 921.jpg 734.jpg 1213.jpg 70.jpg 210.jpg 964.jpg 1746.jpg 914.jpg 1434.jpg 744.jpg 534.jpg 52.jpg 69.jpg 346.jpg 670.jpg 1236.jpg 78.jpg 617.jpg

1401.txt,673.jpg 214.jpg 1623.jpg 1297.jpg 439.jpg 544.jpg 1505.jpg 440.jpg 1745.jpg 1970.jpg 1473.jpg 1441.jpg 64.jpg 268.jpg 1952.jpg 1774.jpg 1791.jpg 370.jpg 518.jpg 1339.jpg

1402.txt,633.jpg 1330.jpg 290.jpg 981.jpg 887.jpg 330.jpg 492.jpg 1232.jpg 568.jpg 1574.jpg 192.jpg 426.jpg 1702.jpg 1383.jpg 843.jpg 1693.jpg 1533.jpg 322.jpg 1962.jpg 1292.jpg

1403.txt,1582.jpg 1265.jpg 489.jpg 458.jpg 1151.jpg 402.jpg 555.jpg 414.jpg 1465.jpg 1289.jpg 996.jpg 1768.jpg 21

1444.txt,315.jpg 582.jpg 262.jpg 1540.jpg 1933.jpg 1944.jpg 977.jpg 1278.jpg 1444.jpg 1352.jpg 1458.jpg 391.jpg 95.jpg 658.jpg 1423.jpg 1311.jpg 1790.jpg 1874.jpg 1254.jpg 1028.jpg

1445.txt,1722.jpg 684.jpg 1732.jpg 1036.jpg 1870.jpg 1406.jpg 1445.jpg 1633.jpg 1074.jpg 1206.jpg 1681.jpg 1115.jpg 1972.jpg 1520.jpg 1602.jpg 536.jpg 1042.jpg 101.jpg 584.jpg 1721.jpg

1446.txt,1937.jpg 12.jpg 729.jpg 121.jpg 1441.jpg 1481.jpg 118.jpg 1676.jpg 37.jpg 1984.jpg 1738.jpg 31.jpg 1526.jpg 1466.jpg 1729.jpg 1816.jpg 1131.jpg 777.jpg 484.jpg 1657.jpg

1447.txt,196.jpg 1077.jpg 90.jpg 1931.jpg 164.jpg 111.jpg 397.jpg 1827.jpg 36.jpg 216.jpg 799.jpg 1106.jpg 1262.jpg 1367.jpg 639.jpg 66.jpg 760.jpg 199.jpg 1945.jpg 1509.jpg

1448.txt,549.jpg 1123.jpg 1448.jpg 1056.jpg 1708.jpg 1210.jpg 1832.jpg 1795.jpg 1703.jpg 577.jpg 1956.jpg 1363.jpg 1671.jpg 1193.jpg 870.jpg 1022.jpg 54.jpg 1772.jpg 1534.jpg 886.jpg

1449.txt,143.jpg 1319.jpg 1263.jpg 1804.jpg 1438.jpg 1231.jpg 1329.jpg 624.jpg 1932.jpg 336.jp

1490.txt,707.jpg 1805.jpg 1378.jpg 385.jpg 1490.jpg 1007.jpg 1994.jpg 1854.jpg 491.jpg 1349.jpg 1274.jpg 759.jpg 324.jpg 578.jpg 1710.jpg 291.jpg 1356.jpg 499.jpg 278.jpg 1019.jpg

1491.txt,410.jpg 857.jpg 1995.jpg 143.jpg 1491.jpg 798.jpg 1686.jpg 1319.jpg 240.jpg 624.jpg 1589.jpg 1095.jpg 954.jpg 1905.jpg 1024.jpg 1841.jpg 1802.jpg 1624.jpg 1449.jpg 648.jpg

1492.txt,1152.jpg 937.jpg 1831.jpg 1731.jpg 817.jpg 190.jpg 1126.jpg 1552.jpg 1189.jpg 441.jpg 933.jpg 203.jpg 716.jpg 845.jpg 1063.jpg 1370.jpg 122.jpg 1301.jpg 145.jpg 1345.jpg

1493.txt,1732.jpg 1036.jpg 1722.jpg 1602.jpg 1870.jpg 1445.jpg 684.jpg 565.jpg 1115.jpg 1042.jpg 536.jpg 1520.jpg 1681.jpg 1633.jpg 1406.jpg 522.jpg 1062.jpg 584.jpg 1454.jpg 1206.jpg

1494.txt,748.jpg 398.jpg 1164.jpg 1508.jpg 1008.jpg 1605.jpg 399.jpg 1853.jpg 680.jpg 646.jpg 938.jpg 1211.jpg 962.jpg 180.jpg 1460.jpg 1027.jpg 1739.jpg 783.jpg 1487.jpg 860.jpg

1495.txt,1335.jpg 51.jpg 814.jpg 1943.jpg 630.jpg 771.jpg 526.jpg 492.jpg 1693.jpg 1426.jpg 

1536.txt,97.jpg 408.jpg 1368.jpg 1536.jpg 909.jpg 1928.jpg 1060.jpg 695.jpg 1176.jpg 1493.jpg 755.jpg 993.jpg 1081.jpg 45.jpg 1149.jpg 234.jpg 790.jpg 1424.jpg 298.jpg 825.jpg

1537.txt,121.jpg 1807.jpg 538.jpg 1869.jpg 668.jpg 571.jpg 692.jpg 1079.jpg 482.jpg 1563.jpg 644.jpg 1246.jpg 1143.jpg 1456.jpg 123.jpg 738.jpg 1177.jpg 819.jpg 1537.jpg 1975.jpg

1538.txt,620.jpg 914.jpg 734.jpg 921.jpg 1746.jpg 498.jpg 744.jpg 70.jpg 1434.jpg 964.jpg 1213.jpg 534.jpg 210.jpg 346.jpg 880.jpg 670.jpg 1236.jpg 69.jpg 52.jpg 78.jpg

1539.txt,1150.jpg 1062.jpg 536.jpg 1602.jpg 1036.jpg 1722.jpg 584.jpg 1732.jpg 53.jpg 534.jpg 1518.jpg 1520.jpg 684.jpg 1406.jpg 1725.jpg 1633.jpg 1870.jpg 593.jpg 986.jpg 1764.jpg

1540.txt,926.jpg 1423.jpg 1167.jpg 1106.jpg 146.jpg 1827.jpg 262.jpg 767.jpg 1137.jpg 1582.jpg 1852.jpg 582.jpg 1352.jpg 28.jpg 1767.jpg 1944.jpg 1511.jpg 1762.jpg 1606.jpg 391.jpg

1541.txt,1520.jpg 1602.jpg 536.jpg 1633.jpg 1062.jpg 1406.jpg 534.jpg 1732.jpg 684.jpg 74.jpg 1715.jpg 1518.j

1582.txt,558.jpg 1947.jpg 1829.jpg 1583.jpg 1244.jpg 1766.jpg 1747.jpg 195.jpg 1390.jpg 327.jpg 551.jpg 1884.jpg 248.jpg 477.jpg 472.jpg 277.jpg 1104.jpg 283.jpg 241.jpg 710.jpg

1583.txt,1827.jpg 1766.jpg 270.jpg 1209.jpg 277.jpg 307.jpg 1583.jpg 1829.jpg 1728.jpg 1763.jpg 32.jpg 1150.jpg 1329.jpg 1244.jpg 612.jpg 295.jpg 195.jpg 1167.jpg 53.jpg 1186.jpg

1584.txt,1137.jpg 307.jpg 1167.jpg 1342.jpg 1846.jpg 1127.jpg 407.jpg 1106.jpg 31.jpg 32.jpg 745.jpg 270.jpg 1415.jpg 1502.jpg 1827.jpg 1746.jpg 295.jpg 1098.jpg 346.jpg 75.jpg

1585.txt,1299.jpg 746.jpg 4.jpg 548.jpg 1324.jpg 988.jpg 1578.jpg 1951.jpg 18.jpg 713.jpg 722.jpg 517.jpg 35.jpg 1221.jpg 276.jpg 1728.jpg 1975.jpg 470.jpg 1188.jpg 301.jpg

1586.txt,1545.jpg 1378.jpg 1241.jpg 324.jpg 706.jpg 780.jpg 499.jpg 1899.jpg 1274.jpg 578.jpg 1805.jpg 924.jpg 385.jpg 129.jpg 491.jpg 1019.jpg 1007.jpg 952.jpg 1964.jpg 1845.jpg

1587.txt,1053.jpg 1188.jpg 1670.jpg 672.jpg 1299.jpg 18.jpg 4.jpg 1456.jpg 1187.jpg 1998.jpg 580.jpg 386.jpg 

1628.txt,254.jpg 97.jpg 408.jpg 43.jpg 228.jpg 915.jpg 755.jpg 1060.jpg 1493.jpg 790.jpg 909.jpg 1225.jpg 229.jpg 980.jpg 1661.jpg 993.jpg 695.jpg 990.jpg 1651.jpg 1320.jpg

1629.txt,1373.jpg 94.jpg 78.jpg 989.jpg 1404.jpg 1517.jpg 1727.jpg 267.jpg 28.jpg 1098.jpg 1629.jpg 1685.jpg 416.jpg 307.jpg 59.jpg 1856.jpg 1202.jpg 1224.jpg 475.jpg 1450.jpg

1630.txt,961.jpg 1531.jpg 293.jpg 855.jpg 1026.jpg 889.jpg 1293.jpg 424.jpg 104.jpg 1939.jpg 11.jpg 1419.jpg 1332.jpg 533.jpg 490.jpg 596.jpg 1687.jpg 251.jpg 1303.jpg 876.jpg

1631.txt,256.jpg 1350.jpg 1683.jpg 639.jpg 164.jpg 1972.jpg 28.jpg 1416.jpg 776.jpg 1722.jpg 772.jpg 1217.jpg 565.jpg 1115.jpg 1206.jpg 1165.jpg 1721.jpg 830.jpg 1042.jpg 1445.jpg

1632.txt,348.jpg 1351.jpg 76.jpg 1753.jpg 1516.jpg 1679.jpg 562.jpg 495.jpg 1726.jpg 726.jpg 877.jpg 587.jpg 789.jpg 1381.jpg 1395.jpg 1564.jpg 1219.jpg 154.jpg 1735.jpg 1003.jpg

1633.txt,1681.jpg 1445.jpg 1722.jpg 1870.jpg 1732.jpg 684.jpg 1206.jpg 1074.jpg 1406.jpg 1036.jpg 1633.jpg 1520

1674.txt,1618.jpg 1864.jpg 111.jpg 1833.jpg 1931.jpg 1674.jpg 593.jpg 1602.jpg 1870.jpg 1722.jpg 522.jpg 1206.jpg 536.jpg 1406.jpg 1520.jpg 1987.jpg 1062.jpg 1518.jpg 1681.jpg 1115.jpg

1675.txt,1784.jpg 1091.jpg 1861.jpg 801.jpg 65.jpg 1728.jpg 1935.jpg 1697.jpg 350.jpg 751.jpg 1619.jpg 1501.jpg 613.jpg 787.jpg 874.jpg 851.jpg 1081.jpg 875.jpg 1631.jpg 1372.jpg

1676.txt,673.jpg 1218.jpg 268.jpg 1107.jpg 1623.jpg 1154.jpg 214.jpg 953.jpg 1813.jpg 1401.jpg 426.jpg 1720.jpg 1512.jpg 445.jpg 1551.jpg 696.jpg 1500.jpg 64.jpg 372.jpg 322.jpg

1677.txt,1732.jpg 536.jpg 1036.jpg 1520.jpg 1722.jpg 1518.jpg 1445.jpg 1602.jpg 1062.jpg 1721.jpg 534.jpg 1042.jpg 1406.jpg 1074.jpg 1132.jpg 1972.jpg 584.jpg 1870.jpg 1681.jpg 1633.jpg

1678.txt,1970.jpg 544.jpg 1441.jpg 439.jpg 1297.jpg 1623.jpg 64.jpg 1473.jpg 1984.jpg 151.jpg 1621.jpg 518.jpg 708.jpg 194.jpg 853.jpg 214.jpg 1952.jpg 777.jpg 1676.jpg 1966.jpg

1679.txt,17.jpg 152.jpg 12.jpg 368.jpg 626.jpg 1428.jpg 1679.jpg 7.jpg 198.jpg 1481.jpg 1

1720.txt,485.jpg 615.jpg 1566.jpg 1718.jpg 1771.jpg 639.jpg 224.jpg 383.jpg 575.jpg 162.jpg 1547.jpg 153.jpg 371.jpg 893.jpg 691.jpg 1005.jpg 1276.jpg 1100.jpg 157.jpg 676.jpg

1721.txt,1722.jpg 684.jpg 1870.jpg 1036.jpg 1732.jpg 1445.jpg 1406.jpg 1681.jpg 1633.jpg 1115.jpg 1520.jpg 1042.jpg 1074.jpg 536.jpg 1602.jpg 1206.jpg 1518.jpg 1194.jpg 1972.jpg 215.jpg

1722.txt,1732.jpg 1206.jpg 1602.jpg 536.jpg 1406.jpg 684.jpg 1870.jpg 1722.jpg 1036.jpg 522.jpg 1115.jpg 1062.jpg 101.jpg 1972.jpg 1445.jpg 1633.jpg 1520.jpg 1715.jpg 534.jpg 1681.jpg

1723.txt,1020.jpg 1289.jpg 1265.jpg 712.jpg 33.jpg 1584.jpg 414.jpg 1151.jpg 1733.jpg 1408.jpg 1742.jpg 1933.jpg 217.jpg 1333.jpg 156.jpg 1096.jpg 555.jpg 458.jpg 1601.jpg 1116.jpg

1724.txt,1437.jpg 768.jpg 184.jpg 1724.jpg 111.jpg 1840.jpg 1962.jpg 1027.jpg 860.jpg 120.jpg 1475.jpg 264.jpg 1208.jpg 1927.jpg 719.jpg 323.jpg 609.jpg 1023.jpg 1391.jpg 1421.jpg

1725.txt,997.jpg 534.jpg 1213.jpg 1062.jpg 1714.jpg 744.jpg 1602.jpg 1973.jpg 1715.jpg 5

1766.txt,202.jpg 1286.jpg 226.jpg 246.jpg 541.jpg 1521.jpg 93.jpg 698.jpg 50.jpg 599.jpg 92.jpg 1047.jpg 723.jpg 1410.jpg 353.jpg 502.jpg 1980.jpg 305.jpg 1420.jpg 94.jpg

1767.txt,148.jpg 1143.jpg 1767.jpg 1807.jpg 286.jpg 85.jpg 885.jpg 1039.jpg 802.jpg 986.jpg 1408.jpg 644.jpg 571.jpg 618.jpg 925.jpg 121.jpg 1550.jpg 538.jpg 852.jpg 482.jpg

1768.txt,421.jpg 721.jpg 1135.jpg 942.jpg 1458.jpg 586.jpg 1275.jpg 1535.jpg 1888.jpg 908.jpg 767.jpg 1131.jpg 1584.jpg 292.jpg 359.jpg 1782.jpg 1698.jpg 594.jpg 1018.jpg 28.jpg

1769.txt,1922.jpg 397.jpg 1185.jpg 1514.jpg 71.jpg 469.jpg 1035.jpg 441.jpg 618.jpg 800.jpg 75.jpg 799.jpg 26.jpg 1486.jpg 1513.jpg 1609.jpg 1571.jpg 573.jpg 1024.jpg 1748.jpg

1770.txt,1662.jpg 153.jpg 290.jpg 1547.jpg 1771.jpg 943.jpg 1383.jpg 981.jpg 1443.jpg 633.jpg 691.jpg 1553.jpg 157.jpg 55.jpg 1024.jpg 1650.jpg 568.jpg 1684.jpg 1788.jpg 843.jpg

1771.txt,1357.jpg 1189.jpg 145.jpg 716.jpg 1552.jpg 1301.jpg 1801.jpg 1063.jpg 122.jpg 1288.jpg 212.jpg 884.jpg 1128.j

1812.txt,1528.jpg 183.jpg 1534.jpg 560.jpg 1223.jpg 415.jpg 384.jpg 1832.jpg 1703.jpg 10.jpg 91.jpg 1290.jpg 1362.jpg 1432.jpg 1363.jpg 1461.jpg 1190.jpg 1116.jpg 932.jpg 1313.jpg

1813.txt,1944.jpg 1458.jpg 16.jpg 262.jpg 486.jpg 1701.jpg 1540.jpg 582.jpg 897.jpg 718.jpg 1444.jpg 1855.jpg 1472.jpg 1790.jpg 1275.jpg 1933.jpg 391.jpg 996.jpg 655.jpg 1151.jpg

1814.txt,709.jpg 1403.jpg 1632.jpg 234.jpg 925.jpg 161.jpg 1814.jpg 71.jpg 618.jpg 743.jpg 1571.jpg 148.jpg 1248.jpg 1514.jpg 1511.jpg 1418.jpg 1795.jpg 1767.jpg 1821.jpg 802.jpg

1815.txt,320.jpg 1819.jpg 432.jpg 1953.jpg 458.jpg 712.jpg 414.jpg 1450.jpg 33.jpg 779.jpg 59.jpg 1125.jpg 650.jpg 1758.jpg 1655.jpg 1151.jpg 489.jpg 899.jpg 1734.jpg 1265.jpg

1816.txt,1190.jpg 1711.jpg 932.jpg 1290.jpg 560.jpg 1832.jpg 183.jpg 1534.jpg 54.jpg 1123.jpg 1703.jpg 1875.jpg 1022.jpg 1775.jpg 1432.jpg 1469.jpg 1448.jpg 91.jpg 1363.jpg 1078.jpg

1817.txt,343.jpg 1004.jpg 1179.jpg 420.jpg 982.jpg 459.jpg 848.jpg 1706.jpg 1690.jpg 1010.jpg 866.j

1858.txt,924.jpg 278.jpg 1007.jpg 578.jpg 1058.jpg 1490.jpg 1554.jpg 396.jpg 1545.jpg 1478.jpg 671.jpg 1805.jpg 1019.jpg 1964.jpg 38.jpg 952.jpg 780.jpg 556.jpg 1349.jpg 827.jpg

1859.txt,241.jpg 1604.jpg 1467.jpg 1747.jpg 327.jpg 1946.jpg 195.jpg 1104.jpg 551.jpg 1829.jpg 710.jpg 277.jpg 1666.jpg 1947.jpg 1390.jpg 477.jpg 283.jpg 404.jpg 664.jpg 558.jpg

1860.txt,243.jpg 1637.jpg 1430.jpg 203.jpg 1370.jpg 1879.jpg 1552.jpg 1423.jpg 413.jpg 1152.jpg 1568.jpg 1342.jpg 1591.jpg 1696.jpg 1486.jpg 1480.jpg 190.jpg 747.jpg 1082.jpg 1189.jpg

1861.txt,558.jpg 1829.jpg 1244.jpg 327.jpg 241.jpg 1947.jpg 195.jpg 277.jpg 472.jpg 1390.jpg 1766.jpg 1747.jpg 1104.jpg 1467.jpg 1604.jpg 1583.jpg 551.jpg 248.jpg 1884.jpg 283.jpg

1862.txt,1452.jpg 592.jpg 1799.jpg 762.jpg 84.jpg 1309.jpg 141.jpg 1316.jpg 1663.jpg 793.jpg 1626.jpg 1489.jpg 959.jpg 1466.jpg 271.jpg 956.jpg 991.jpg 1777.jpg 935.jpg 387.jpg

1863.txt,470.jpg 713.jpg 1673.jpg 1578.jpg 1951.jpg 1549.jpg 658.jpg 746.jpg 1863.jpg 1252.jpg 115

1904.txt,1753.jpg 1156.jpg 1529.jpg 1417.jpg 562.jpg 1051.jpg 8.jpg 948.jpg 1176.jpg 1907.jpg 687.jpg 772.jpg 150.jpg 1081.jpg 265.jpg 1489.jpg 1071.jpg 1675.jpg 1902.jpg 1590.jpg

1905.txt,1684.jpg 1090.jpg 1268.jpg 1626.jpg 232.jpg 793.jpg 1245.jpg 209.jpg 102.jpg 1072.jpg 84.jpg 806.jpg 935.jpg 1314.jpg 1016.jpg 524.jpg 1113.jpg 1658.jpg 1083.jpg 917.jpg

1906.txt,1918.jpg 1948.jpg 639.jpg 1622.jpg 243.jpg 162.jpg 719.jpg 772.jpg 1261.jpg 103.jpg 1568.jpg 1001.jpg 1817.jpg 1057.jpg 1752.jpg 727.jpg 272.jpg 1.jpg 1350.jpg 256.jpg

1907.txt,843.jpg 1547.jpg 192.jpg 676.jpg 157.jpg 691.jpg 55.jpg 1553.jpg 633.jpg 224.jpg 1720.jpg 568.jpg 1330.jpg 1024.jpg 943.jpg 153.jpg 981.jpg 1443.jpg 1771.jpg 1960.jpg

1908.txt,1286.jpg 50.jpg 599.jpg 93.jpg 678.jpg 723.jpg 1047.jpg 246.jpg 1410.jpg 226.jpg 1250.jpg 202.jpg 305.jpg 1521.jpg 502.jpg 698.jpg 594.jpg 92.jpg 1980.jpg 541.jpg

1909.txt,1019.jpg 499.jpg 1058.jpg 1805.jpg 827.jpg 780.jpg 491.jpg 1586.jpg 1378.jpg 706.jpg 324.jpg 1545.jpg 

1950.txt,1950.jpg 1346.jpg 1783.jpg 837.jpg 245.jpg 1557.jpg 1622.jpg 1538.jpg 1031.jpg 923.jpg 719.jpg 103.jpg 1543.jpg 394.jpg 1847.jpg 531.jpg 1397.jpg 1901.jpg 1948.jpg 1864.jpg

1951.txt,1621.jpg 128.jpg 1235.jpg 853.jpg 1012.jpg 1364.jpg 1813.jpg 64.jpg 269.jpg 544.jpg 1376.jpg 708.jpg 214.jpg 194.jpg 1473.jpg 688.jpg 439.jpg 1623.jpg 777.jpg 1401.jpg

1952.txt,67.jpg 590.jpg 1970.jpg 440.jpg 1814.jpg 1297.jpg 439.jpg 1990.jpg 1623.jpg 673.jpg 544.jpg 1688.jpg 87.jpg 64.jpg 1936.jpg 1235.jpg 1376.jpg 1364.jpg 268.jpg 171.jpg

1953.txt,544.jpg 708.jpg 1012.jpg 1364.jpg 1621.jpg 1813.jpg 269.jpg 128.jpg 1984.jpg 1473.jpg 1623.jpg 1970.jpg 439.jpg 194.jpg 688.jpg 853.jpg 1297.jpg 777.jpg 64.jpg 1235.jpg

1954.txt,29.jpg 531.jpg 1937.jpg 1171.jpg 464.jpg 859.jpg 1200.jpg 1847.jpg 845.jpg 727.jpg 1526.jpg 1852.jpg 926.jpg 653.jpg 1497.jpg 1280.jpg 118.jpg 1037.jpg 1653.jpg 497.jpg

1955.txt,963.jpg 1863.jpg 988.jpg 95.jpg 658.jpg 1159.jpg 1578.jpg 470.jpg 746.jpg 301.jpg 890.jpg 1252.

1996.txt,748.jpg 1853.jpg 1164.jpg 319.jpg 398.jpg 860.jpg 180.jpg 938.jpg 1027.jpg 184.jpg 399.jpg 1508.jpg 680.jpg 1962.jpg 1739.jpg 1605.jpg 1460.jpg 646.jpg 1211.jpg 1008.jpg

1997.txt,104.jpg 657.jpg 1026.jpg 1163.jpg 293.jpg 58.jpg 1638.jpg 1266.jpg 782.jpg 1564.jpg 1993.jpg 1773.jpg 403.jpg 1198.jpg 1555.jpg 961.jpg 284.jpg 1061.jpg 1407.jpg 11.jpg

1998.txt,1998.jpg 625.jpg 662.jpg 257.jpg 302.jpg 303.jpg 1464.jpg 1909.jpg 1906.jpg 483.jpg 272.jpg 1338.jpg 993.jpg 1187.jpg 1752.jpg 1069.jpg 1493.jpg 790.jpg 437.jpg 675.jpg

1999.txt,405.jpg 307.jpg 1827.jpg 453.jpg 1509.jpg 729.jpg 1137.jpg 1106.jpg 1728.jpg 1342.jpg 287.jpg 407.jpg 211.jpg 772.jpg 243.jpg 1017.jpg 32.jpg 1329.jpg 1167.jpg 745.jpg

